window.SederCourse={stage:'beitzah-tractate-arc',completeTitle:'You can now read a case through its category and reason.',completeCopy:'You kept one festival case, two positions, a category, and two competing explanations distinct. Continue into the Beitzah source workspace.',nextUrl:'lab.html?tractate=beitzah',nextLabel:'Open the Beitzah source workspace',steps:[
{short:'Locate the case',mode:'CASE ORIENTATION',title:'An egg appears during the festival',ref:'Mishnah Beitzah 1:1',hebrew:'בֵּיצָה שֶׁנּוֹלְדָה בְּיוֹם טוֹב',translation:'An egg that was laid on a festival day.',prompt:'What fact is the source putting under pressure?',answers:['The egg came into being during the festival rather than beforehand.','The egg was prepared before the festival and stored away.','The source is telling a story with no legal category to map.'],correct:0,skill:'beitzah-case-timing',competency:'recognition',feedback:'Right. Timing is the case fact that makes the category question possible.'},
{short:'Keep both voices',mode:'DISPUTE MAP',title:'Shammai and Hillel disagree',ref:'Mishnah Beitzah 1:1',hebrew:'בֵּית שַׁמַּאי אוֹמְרִים תֵּאָכֵל · בֵּית הִלֵּל אוֹמְרִים לֹא תֵּאָכֵל',translation:'Beit Shammai say it may be eaten; Beit Hillel say it may not.',prompt:'What must a reader preserve first?',answers:['Two answers to the same case before deciding why they differ.','That the longer wording automatically wins.','That the two schools are talking about unrelated cases.'],correct:0,skill:'beitzah-two-positions',competency:'argument',feedback:'Good. Map each voice before importing an explanation.'},
{short:'Name the category',mode:'LEGAL CATEGORY',title:'Nolad: newly come into being',ref:'Beitzah 2a',hebrew:'נוֹלָד',translation:'Newly come into being.',prompt:'What does naming nolad allow the learner to do?',answers:['See the egg as one instance of a category rather than an isolated curiosity.','Treat the Hebrew term as a final ruling by itself.','Assume every new object is identical in every legal setting.'],correct:0,skill:'beitzah-nolad-category',competency:'sourceReasoning',feedback:'Exactly. Categories make a specific case portable without erasing further distinctions.'},
{short:'Test the category',mode:'SOURCE CHECK',title:'A category is not a shortcut',ref:'Beitzah 2a',hebrew:'נוֹלָד · מִקְרֶה',translation:'Newly come into being · a case.',prompt:'After identifying a category, what does a careful reader still need to ask?',answers:['Which facts of this case make the category relevant here.','Whether the category ends all further questions.','Which school has the more memorable name.'],correct:0,skill:'beitzah-category-case-fit',competency:'sourceReasoning',feedback:'Yes. A category organizes a case; it does not replace attending to the facts.'},
{short:'Separate ruling and reason',mode:'REASONING DISPUTE',title:'Two reasons, one prohibition',ref:'Beitzah 2a',hebrew:'מִשּׁוּם הֲכָנָה · מִשּׁוּם נוֹלָד',translation:'Because of preparation · because of a newly-created thing.',prompt:'Why does the Gemara test more than one reason for the same ruling?',answers:['Different reasons can change which further cases the ruling reaches.','A ruling is invalid until two reasons are found.','The Gemara has abandoned the original case.'],correct:0,skill:'beitzah-reason-scope',competency:'argument',feedback:'Right. A disagreement about reason can reshape the scope of an agreed ruling.'},
{short:'Trace the consequence',mode:'REASONING MAP',title:'Reason controls the next question',ref:'Beitzah 2a',hebrew:'טַעַם · נִפְקָא מִנָּה',translation:'Reason · a practical difference.',prompt:'What should a reader look for after two reasons are proposed?',answers:['A later case where the reasons would lead to different outcomes.','A way to ignore the original disagreement.','A reason to merge two distinct explanations.'],correct:0,skill:'beitzah-reason-consequence',competency:'argument',feedback:'Good. Testing a reason means asking what difference it would make in another case.'},
{short:'Keep the boundary',mode:'STUDY BOUNDARY',title:'Study is not a personal ruling',ref:'Jewish Learning Academy Beitzah boundary',hebrew:'לִלְמוֹד · לְהָבִין · לִשְׁאוֹל',translation:'To learn · to understand · to ask.',prompt:'What is the responsible use of this source?',answers:['Learn its categories and seek qualified guidance for practical observance.','Apply the source directly to a personal holiday question.','Ignore the source’s practical stakes completely.'],correct:0,skill:'beitzah-learning-boundary',competency:'sourceReasoning',feedback:'Serious study includes recognizing its boundary.'},
{short:'Transfer',mode:'SOURCE CHECK',title:'Read a new category dispute',ref:'Beitzah transfer checkpoint',hebrew:'מִקְרֶה · קָטֵגוֹרְיָה · קוֹל · טַעַם',translation:'Case · category · voice · reason.',independent:true,prompt:'What is the best first map for a new dispute?',answers:['State the case, preserve each voice, name the category, then test the reason’s scope.','Choose the familiar voice before reading the case.','Treat a category word as an answer without looking at reasons.'],correct:0,skill:'beitzah-independent-map',competency:'sourceReasoning',feedback:'You can now follow case, category, and reason without flattening the dispute.'}]};

// [rebalance] distractor lengths evened so the correct answer is not the longest option
window.SederCourse.steps[2].answers[1]="Treat the bare Hebrew term as if it were a final and complete ruling all by itself.";
window.SederCourse.steps[4].answers[2]="The Gemara has by now simply abandoned the original case entirely.";
window.SederCourse.steps[5].answers[1]="A convenient way to quietly ignore the original disagreement altogether.";
window.SederCourse.steps[6].answers[2]="Ignore the source's real practical stakes almost completely.";
window.SederCourse.steps[7].answers[1]="Choose the more familiar voice first, before even reading the case itself.";
