window.SederCourse={stage:'berakhot-mishnah-grammar',completeTitle:'You can now open a compact Mishnah sentence.',completeCopy:'You identified a question, an action, a condition, and a ruling. This lets the learner see the skeleton of a source before getting lost in its details.',nextUrl:'berakhot-unit-5.html',nextLabel:'Continue to cited teachings',steps:[
{short:'Find the action',mode:'SENTENCE MAP',title:'Start with the verb',ref:'Mishnah Berakhot 1:1',hebrew:'קוֹרִין אֶת שְׁמַע',translation:'We recite Shema.',prompt:'What is the action at the center of this phrase?',answers:['Reciting Shema.','Hearing Shema read aloud.','Writing the Shema passages.'],correct:0,skill:'mishnah-grammar-action',competency:'translation',feedback:'Good. In a compact Mishnah, first locate what is being done — korin means active recitation, not hearing or writing, and the difference carries halakhic weight.'},
{short:'Find the condition',mode:'SENTENCE MAP',title:'A phrase narrows the case',ref:'Mishnah Berakhot 1:1',hebrew:'בְּעַרְבִין',translation:'In the evenings.',prompt:'What work does this phrase do?',answers:['It specifies the setting or time of the action.','It names who is obligated in the action.','It states the action’s required duration.'],correct:0,skill:'mishnah-grammar-condition',competency:'translation',feedback:'Exactly. Conditions tell you when, where, or to whom a statement applies — this one answers “when,” not “who” or “for how long.”'},
{short:'Read a question shape',mode:'SENTENCE MAP',title:'Question word plus action',ref:'Mishnah Berakhot 1:1',hebrew:'מֵאֵימָתַי קוֹרִין',translation:'From when do we recite?',prompt:'How is this sentence structured?',answers:['A question word asks for the beginning point of an action.','A question word asks for the reason behind an action.','A question word asks who must perform an action.'],correct:0,skill:'mishnah-grammar-question',competency:'translation',feedback:'Right. Grammar serves orientation: me’eimatai asks “from when” — reason questions use mai taama, and “who” questions use mi.'},
{short:'Locate a measure',mode:'SENTENCE MAP',title:'A number can define a case',ref:'Mishnah Sukkah 1:1',hebrew:'לְמַעְלָה מֵעֶשְׂרִים אַמָּה',translation:'Higher than twenty cubits.',prompt:'What is the measure doing in this sentence?',answers:['Defining a condition that affects the case.','Providing a rough estimate that the ruling can round up or down.','Recording a customary height that carries no legal force.'],correct:0,skill:'mishnah-grammar-measure',competency:'recognition',feedback:'A measure is not decoration or approximation; it creates the exact boundary the Mishnah will reason about.'},
{short:'Locate a ruling',mode:'SENTENCE MAP',title:'What follows from the case?',ref:'Mishnah Sukkah 1:1',hebrew:'פְּסוּלָה',translation:'It is invalid.',prompt:'What job does this word perform?',answers:['It gives the ruling for the described case.','It describes the structure’s physical condition.','It flags the case as still under dispute.'],correct:0,skill:'mishnah-grammar-ruling',competency:'recognition',feedback:'Good. Pesulah is a verdict, not a description — case and ruling are the first map of a Mishnah.'},
{short:'Compare two cases',mode:'COMPARISON',title:'A shared structure transfers',ref:'Mishnah Eruvin 1:1',hebrew:'מָבוֹי שֶׁהוּא גָבוֹהַּ … יְמַעֵט',translation:'An alleyway that is high … one should lower it.',prompt:'What pattern should you recognize?',answers:['A described condition followed by the response it requires.','A question about a measure followed by its scriptural source.','A ruling followed by the exception that limits its scope.'],correct:0,skill:'mishnah-grammar-transfer',competency:'sourceReasoning',feedback:'You are transferring sentence structure from Berakhot to a new tractate — condition then response, the same skeleton in a different legal world.'},
{short:'Independent sentence',mode:'INDEPENDENT READ',title:'Read the skeleton first',ref:'Mishnah grammar checkpoint',hebrew:'מֵאֵימָתַי · קוֹרִין · בְּעַרְבִין',translation:'From when · do we recite · in the evenings.',independent:true,prompt:'What is the fastest responsible first reading?',answers:['Question word, action, then the condition that narrows the action.','Action, its reason, then the source that grounds the reason.','Condition, ruling, then the dissent that challenges the ruling.'],correct:0,skill:'mishnah-grammar-independent',competency:'sourceReasoning',feedback:'You can now see a Mishnah’s structure before translating it word by word — and tell this shape apart from reason-chains and dispute-chains.'},
{short:'Type the meaning',mode:'PRODUCTION CHECK',title:'Recall, don’t just recognize',ref:'Mishnah Berakhot 1:1',hebrew:'קוֹרִין אֶת שְׁמַע',translation:'We recite Shema.',independent:true,typed:true,prompt:'Type the English meaning of this phrase in a few words.',acceptable:['we recite shema','we recite the shema','they recite shema','they recite the shema','we read the shema','we read shema','they read the shema'],skill:'berakhot-unit4-typed-recall',competency:'translation',feedback:'Typing an answer from memory is a stronger test of durable mastery than recognizing it among choices.'}
]};
