window.SederCourse={stage:'berakhot-mishnah-grammar',completeTitle:'You can now open a compact Mishnah sentence.',completeCopy:'You identified a question, an action, a condition, and a ruling. This lets the learner see the skeleton of a source before getting lost in its details.',nextUrl:'berakhot-unit-5.html',nextLabel:'Continue to cited teachings',steps:[
{short:'Find the action',mode:'SENTENCE MAP',title:'Start with the verb',ref:'Mishnah Berakhot 1:1',hebrew:'קוֹרִין אֶת שְׁמַע',translation:'We recite Shema.',prompt:'What is the action at the center of this phrase?',answers:['Reciting Shema.','Measuring a courtyard.','Dividing an object.'],correct:0,skill:'mishnah-grammar-action',competency:'translation',feedback:'Good. In a compact Mishnah, first locate what is being done.'},
{short:'Find the condition',mode:'SENTENCE MAP',title:'A phrase narrows the case',ref:'Mishnah Berakhot 1:1',hebrew:'בְּעַרְבִין',translation:'In the evenings.',prompt:'What work does this phrase do?',answers:['It specifies the setting or time of the action.','It introduces a second speaker.','It resolves an objection.'],correct:0,skill:'mishnah-grammar-condition',competency:'translation',feedback:'Exactly. Conditions tell you when, where, or to whom a statement applies.'},
{short:'Read a question shape',mode:'SENTENCE MAP',title:'Question word plus action',ref:'Mishnah Berakhot 1:1',hebrew:'מֵאֵימָתַי קוֹרִין',translation:'From when do we recite?',prompt:'How is this sentence structured?',answers:['A question word asks for the beginning point of an action.','A source signal introduces a verse.','A conclusion is being drawn.'],correct:0,skill:'mishnah-grammar-question',competency:'translation',feedback:'Right. Grammar serves orientation: it tells you what the sentence is asking.'},
{short:'Locate a measure',mode:'SENTENCE MAP',title:'A number can define a case',ref:'Mishnah Sukkah 1:1',hebrew:'לְמַעְלָה מֵעֶשְׂרִים אַמָּה',translation:'Higher than twenty cubits.',prompt:'What is the measure doing in this sentence?',answers:['Defining a condition that affects the case.','Naming a source author.','Introducing an objection.'],correct:0,skill:'mishnah-grammar-measure',competency:'recognition',feedback:'A measure is not decoration; it creates the boundary the Mishnah will reason about.'},
{short:'Locate a ruling',mode:'SENTENCE MAP',title:'What follows from the case?',ref:'Mishnah Sukkah 1:1',hebrew:'פְּסוּלָה',translation:'It is invalid.',prompt:'What job does this word perform?',answers:['It gives the ruling for the described case.','It asks for a reason.','It introduces a baraita.'],correct:0,skill:'mishnah-grammar-ruling',competency:'recognition',feedback:'Good. Case and ruling are the first map of a Mishnah.'},
{short:'Compare two cases',mode:'COMPARISON',title:'A shared structure transfers',ref:'Mishnah Eruvin 1:1',hebrew:'מָבוֹי שֶׁהוּא גָבוֹהַּ … יְמַעֵט',translation:'An alleyway that is high … one should lower it.',prompt:'What pattern should you recognize?',answers:['A described condition followed by the response it requires.','A question followed by a verse.','An objection followed by a conclusion.'],correct:0,skill:'mishnah-grammar-transfer',competency:'sourceReasoning',feedback:'You are transferring sentence structure from Berakhot to a new tractate.'},
{short:'Independent sentence',mode:'INDEPENDENT READ',title:'Read the skeleton first',ref:'Mishnah grammar checkpoint',hebrew:'מֵאֵימָתַי · קוֹרִין · בְּעַרְבִין',translation:'From when · do we recite · in the evenings.',independent:true,prompt:'What is the fastest responsible first reading?',answers:['Question word, action, then the condition that narrows the action.','Translate each word without noticing its job.','Assume the sentence has no structure.'],correct:0,skill:'mishnah-grammar-independent',competency:'sourceReasoning',feedback:'You can now see a Mishnah’s structure before translating it word by word.'}
]};
