const arc=[
{title:'Core Gemara signals',copy:'Twelve high-frequency words that tell you what the page is doing.',stage:'read-language',url:'language.html',skill:'language-core'},
{title:'Enter Berakhot 2a',copy:'Find the Mishnah, the context-question, and the verse-based answer.',stage:'berakhot-2a-depth',url:'berakhot-deep.html',skill:'berakhot-'},
{title:'Build a proof',copy:'Follow a word-question, answer, sign, and second source on Berakhot 2b.',stage:'berakhot-2b-proof',url:'berakhot-unit-2.html',skill:'berakhot2b-'},
{title:'Transfer the moves',copy:'Read unfamiliar Berakhot signals with translation used only to verify.',stage:'berakhot-independent-transfer',url:'berakhot-unit-3.html',skill:'transfer-'},
{title:'Read Mishnah grammar',copy:'Use compact Hebrew structure to separate case, condition, and ruling.',stage:'berakhot-mishnah-grammar',url:'berakhot-unit-4.html',skill:'mishnah-grammar'},
{title:'Follow a cited teaching',copy:'Track baraita, objection, and response without losing the thread.',stage:'berakhot-baraita-disagreement',url:'berakhot-unit-5.html',skill:'baraita-'},
{title:'Gemara argument toolkit',copy:'Practice connectors, objections, distinctions, and conclusions across contexts.',stage:'gemara-reading-toolkit',url:'gemara-toolkit.html',skill:'connector-'},
{title:'Retrieval session',copy:'Bring back fragile source moves before beginning new material.',stage:'retrieval-room',url:'review.html',skill:'review'},
{title:'Independent reading',copy:'Meet unfamiliar Gemara signals without the scaffold.',stage:'independent-reading-checkpoint',url:'independent-read.html',skill:'independent-'},
{title:'Launch into a new tractate',copy:'Use your Berakhot tools in Eruvin, Shabbat, Pesachim, or Bava Metzia.',stage:'tractate-launch',url:'shas-map-v2.html',skill:'lab-'}
];
const learnerId=Seder.currentLearnerId();
Seder.api(`/api/learners/${learnerId}`).then(r=>r.ok?r.json():null).then(learner=>{const completed=learner?.completedStages||[];const mastery=learner?.mastery||{};document.querySelector('#xp').textContent=`${learner?.xp||0} XP`;const sourceMoves=Object.keys(mastery).filter(k=>mastery[k]>0).length;document.querySelector('#evidence').textContent=`${sourceMoves} SOURCE MOVES PRACTICED`;const lastDone=arc.reduce((count,item)=>count+(completed.includes(item.stage)?1:0),0);document.querySelector('#completed').textContent=`${lastDone} OF ${arc.length} SESSIONS`;let available=true;document.querySelector('#sessions').innerHTML=arc.map((item,index)=>{const done=completed.includes(item.stage);const current=!done&&available;available=available&&done;return `<article class="session ${done?'done':''} ${current?'current':''} ${!done&&!current?'locked':''}"><b>${done?'✓':index+1}</b><div><h2>${item.title}</h2><p>${item.copy}</p><small>${done?'MASTERY EVIDENCE RECORDED':current?'READY NOW':'PREREQUISITE IN PROGRESS'}</small></div><a href="${item.url}">${done?'Revisit →':current?'Begin →':'Locked'}</a></article>`}).join('')}).catch(()=>{});
