window.SederCourse={stage:'berakhot-baraita-disagreement',completeTitle:'You can now follow a source entering an argument.',completeCopy:'You recognized a cited teaching, a challenge, the claim under pressure, and the kind of response that can preserve a discussion. Now apply those moves directly to the Daf.',nextUrl:'daf-workbench.html?tractate=berakhot',nextLabel:'Open the Berakhot Daf Workbench',steps:[
{short:'Cited teaching',mode:'BARAITA',title:'A new teaching joins the page',ref:'Common Gemara signal',hebrew:'תַּנְיָא',translation:'It was taught.',prompt:'What should a learner ask first?',answers:['What issue is this teaching being brought to support, clarify, or challenge?','Whether this teaching agrees completely with the Mishnah already taught.','Whether the prior discussion has ended.'],correct:0,skill:'baraita-purpose',competency:'sourceReasoning',feedback:'Good. A cited teaching has a job in the current discussion.'},
{short:'Locate the claim',mode:'ARGUMENT MAP',title:'An objection needs a target',ref:'Common Gemara signal',hebrew:'מֵיתִיבֵי',translation:'They raise an objection.',prompt:'What must you identify to understand the objection?',answers:['The earlier claim or answer that the source threatens.','A new unrelated topic.','The final ruling of the tractate.'],correct:0,skill:'baraita-objection-target',competency:'argument',feedback:'Exactly. An objection is a relationship between a new source and an earlier claim.'},
{short:'State the pressure',mode:'CHALLENGE',title:'What makes this hard?',ref:'Argument-reading habit',hebrew:'קַשְׁיָא',translation:'A difficulty.',prompt:'What is the learner’s job when a difficulty appears?',answers:['State why the sources or claims seem unable to stand together.','Assume the difficulty is already solved.','Ignore the earlier source.'],correct:0,skill:'baraita-state-pressure',competency:'argument',feedback:'Naming the pressure prevents a learner from losing the thread of the disagreement.'},
{short:'Read a distinction',mode:'RESPONSE',title:'A response can change the case',ref:'Common Gemara response',hebrew:'הָא בְּ… הָא בְּ…',translation:'This is in one case; that is in another.',prompt:'What kind of response is this?',answers:['A distinction that shows why the sources may not actually conflict.','A rejection of all sources.','A new prayer text.'],correct:0,skill:'baraita-distinction-response',competency:'argument',feedback:'Right. Distinctions preserve sources by narrowing their domains.'},
{short:'Compare outcomes',mode:'REASONING',title:'Not every response proves the same thing',ref:'Source reasoning',hebrew:'תְּיוּבְתָּא · קַשְׁיָא',translation:'Refutation · difficulty.',prompt:'Why should a learner distinguish these outcomes?',answers:['A refutation and an unresolved difficulty place different weight on a prior claim.','They are interchangeable page decorations.','Both mean the source has no argument.'],correct:0,skill:'baraita-outcome-compare',competency:'sourceReasoning',feedback:'Good. Precision about outcomes makes disagreement intelligible.'},
{short:'Follow a mini-dispute',mode:'ARGUMENT MAP',title:'Read the sequence by function',ref:'Sugya structure practice',hebrew:'תַּנְיָא · מֵיתִיבֵי · לָא קַשְׁיָא',translation:'It was taught · they raise an objection · it is not difficult.',prompt:'Which map fits this sequence?',answers:['A teaching is cited, challenged, then reconciled by a distinction.','A final ruling is repeated.','Three unrelated subjects appear.'],correct:0,skill:'baraita-mini-dispute',competency:'argument',feedback:'You can now see disagreement as a structured movement rather than a blur of sources.'},
{short:'Independent source',mode:'INDEPENDENT READ',title:'Predict the response',ref:'Disagreement checkpoint',hebrew:'מֵיתִיבֵי … לָא קַשְׁיָא',translation:'They raise an objection … it is not difficult.',independent:true,prompt:'What should you expect to find between these signals?',answers:['A response that explains why the objection does not defeat the earlier claim.','A new tractate with no connection.','A final conclusion before any answer.'],correct:0,skill:'baraita-independent-read',competency:'sourceReasoning',feedback:'You can now predict the logic of a disagreement before every detail is translated.'}
]};
