window.SederCourse={stage:'berakhot-independent-transfer',completeTitle:'You have completed an independent-reading checkpoint.',completeCopy:'You have transferred Gemara reading skills beyond one memorized opening: identify the question, type of evidence, pressure point, and conclusion before leaning on translation.',nextUrl:'shas-map-v2.html',nextLabel:'Enter another tractate',steps:[
{short:'Recognize a new question',mode:'TRANSFER',title:'A source asks what it adds',ref:'Common Gemara move',hebrew:'מַאי קָא מַשְׁמַע לָן?',translation:'What does this teach us?',independent:true,prompt:'What reading task does this phrase set?',answers:['Find the added implication or point of the prior statement.','Find the page number.','Assume the discussion is finished.'],correct:0,skill:'transfer-clarification-question',competency:'argument',feedback:'You are no longer relying on a single Berakhot phrase; you recognize a general Gemara move.'},
{short:'Classify a source',mode:'TRANSFER',title:'A source arrives with a job',ref:'Common Gemara move',hebrew:'תָּא שְׁמַע',translation:'Come and hear.',independent:true,prompt:'How should you approach the next line?',answers:['Test whether the cited source supports the question under discussion.','Treat it as a final ruling before reading it.','Ignore it because it is only a quotation.'],correct:0,skill:'transfer-proof-role',competency:'sourceReasoning',feedback:'A source is not self-explanatory; its role in the argument must be read.'},
{short:'See a pressure point',mode:'TRANSFER',title:'An answer may be challenged',ref:'Common Gemara move',hebrew:'מֵיתִיבֵי',translation:'They raise an objection.',independent:true,prompt:'What should you locate next?',answers:['The source that creates difficulty and the claim it presses against.','A change in tractate.','A final agreement.'],correct:0,skill:'transfer-objection',competency:'argument',feedback:'An objection is intelligible only when you can state what earlier claim it threatens.'},
{short:'Read a distinction',mode:'TRANSFER',title:'Different cases can preserve both sources',ref:'Common Gemara move',hebrew:'לָא קַשְׁיָא; הָא בְּ… הָא בְּ…',translation:'It is not difficult; this is in one case, that is in another.',independent:true,prompt:'What is the Gemara most likely doing?',answers:['Distinguishing cases to show why the sources need not conflict.','Rejecting both sources as useless.','Giving a translation drill.'],correct:0,skill:'transfer-distinction',competency:'argument',feedback:'This is a core move of legal reasoning: similarity can hide an important difference.'},
{short:'Map a mini-sugya',mode:'INDEPENDENT READ',title:'Name the argument without translation',ref:'Sugya structure practice',hebrew:'מַאי טַעְמָא · תָּא שְׁמַע · מֵיתִיבֵי · לָא קַשְׁיָא',translation:'What is the reason? · come and hear · they raise an objection · it is not difficult.',independent:true,prompt:'Which map best fits this sequence?',answers:['Reason-question, evidence, objection, then a distinction that resolves pressure.','Conclusion, story, new tractate, page number.','Four final rulings with no argument.'],correct:0,skill:'transfer-sugya-map',competency:'argument',feedback:'You can now read the architecture of a multi-move passage.'},
{short:'Explain your evidence',mode:'EVIDENCE',title:'A proof has a role, not just a presence',ref:'Berakhot 2b method',hebrew:'סִימָן לַדָּבָר · וְאוֹמֵר',translation:'A sign for the matter · and it says.',prompt:'What distinction should a learner make here?',answers:['A practical sign and a second textual proof may contribute differently.','Every source phrase does exactly the same work.','Neither phrase relates to an argument.'],correct:0,skill:'transfer-evidence-types',competency:'sourceReasoning',feedback:'Strong readers ask not merely “is there a source?” but “what kind of support is this?”'},
{short:'Mastery reflection',mode:'MASTERY CHECK',title:'Choose the next responsible move',ref:'Independent learning habit',hebrew:'שְׁאֵלָה · מָקוֹר · תְּשׁוּבָה',translation:'Question · source · answer.',prompt:'When a new Daf feels dense, what should you do first?',answers:['Find the current question, identify the source or claim under discussion, then name the next line’s job.','Translate every word in isolation before looking at structure.','Assume the page is inaccessible without a partner.'],correct:0,skill:'independent-sugya-reading',competency:'sourceReasoning',feedback:'This habit is the bridge toward real independent study.'}
]};
