window.SederCourse={stage:'berakhot-2b-proof',completeTitle:'You can now follow a short proof sequence.',completeCopy:'You identified a word-problem, a proposed answer, the role of a practical sign, and a second supporting source. Next, test whether those skills transfer when the scaffold falls away.',nextUrl:'berakhot-unit-3.html',nextLabel:'Begin independent reading',steps:[
{short:'Focus on one word',mode:'QUESTION',title:'A word becomes a problem',ref:'Berakhot 2b',hebrew:'וּמַאי וְטָהֵר?',translation:'What does “and it is purified” mean?',prompt:'What is the Gemara doing with this phrase?',answers:['Asking how a particular word in a source should be understood.','Giving a final time ruling.','Introducing a new Mishnah.'],correct:0,skill:'berakhot2b-word-question',competency:'argument',feedback:'Right. Gemara often slows down over a compact word and asks what it means in context.'},
{short:'Read a proposed answer',mode:'ANSWER',title:'An interpretation is offered',ref:'Berakhot 2b',hebrew:'טָהֵר יוֹמָא',translation:'The day becomes clear.',prompt:'What role does this short line play after the question?',answers:['It proposes an interpretation of the word.','It challenges the question as irrelevant.','It changes to a new subject.'],correct:0,skill:'berakhot2b-answer',competency:'argument',feedback:'Exactly. First name the line as an answer before deciding how strong it is.'},
{short:'Use a practical sign',mode:'EVIDENCE',title:'A sign tests the interpretation',ref:'Berakhot 2b',hebrew:'סִימָן לַדָּבָר: צֵאת הַכּוֹכָבִים',translation:'A sign for the matter: the emergence of the stars.',prompt:'What does this line add to the discussion?',answers:['A concrete indicator that helps clarify the disputed time.','A new legal category unrelated to the phrase.','A final conclusion with no evidence.'],correct:0,skill:'berakhot2b-sign',competency:'sourceReasoning',feedback:'Good. Evidence can be practical as well as textual; ask what it helps establish.'},
{short:'Notice a second source',mode:'PROOF',title:'Why does the Gemara say “and it says”?',ref:'Berakhot 2b · Nehemiah 4:16',hebrew:'וְאוֹמֵר: וְהָיוּ לָנוּ הַלַּיְלָה מִשְׁמָר',translation:'And it says: at night they were a guard for us.',prompt:'What job does a second cited source often perform?',answers:['It strengthens or clarifies the earlier proof.','It repeats the practical sign in different words.','It ends the need to read carefully.'],correct:0,skill:'berakhot2b-second-source',competency:'sourceReasoning',feedback:'Right. A second source is often brought because the first source alone leaves an opening.'},
{short:'Compare evidence',mode:'COMPARISON',title:'Do not treat all sources as identical',ref:'Berakhot 2b',hebrew:'סִימָן · רְאָיָה',translation:'Sign · proof.',prompt:'What is a responsible distinction to make?',answers:['Ask whether a source is a practical marker, direct proof, clarification, or challenge.','Assume every citation does the same thing.','Ignore the source type and memorize the conclusion.'],correct:0,skill:'proof-role-comparison',competency:'sourceReasoning',feedback:'Exactly. Mature reading includes asking what kind of support is being offered.'},
{short:'Trace pressure and response',mode:'ARGUMENT MAP',title:'What changes after a challenge?',ref:'Berakhot 2b',hebrew:'שְׁאֵלָה · תְּשׁוּבָה · סִימָן · רְאָיָה',translation:'Question · answer · sign · proof.',prompt:'Which reading habit best follows this sequence?',answers:['Track what each step contributes before deciding whether the answer is secure.','Jump from the question straight to a personal conclusion.','Treat the sign as unrelated decoration.'],correct:0,skill:'challenge-and-answer-flow',competency:'argument',feedback:'Good. The sequence lets you see an argument becoming more secure through evidence.'},
{short:'Independent read I',mode:'INDEPENDENT READ',title:'Predict the job of a source',ref:'Berakhot 2b',hebrew:'וְאוֹמֵר',translation:'And it says.',independent:true,prompt:'Before revealing the translation, what should you expect next?',answers:['Another source that adds support or clarification.','A new legal case with no connection.','The final ruling of the tractate.'],correct:0,skill:'berakhot2b-independent-source',competency:'sourceReasoning',feedback:'You read the source signal itself as an argument map.'},
{short:'Independent read II',mode:'MASTERY CHECK',title:'Read the whole movement',ref:'Berakhot 2b',hebrew:'וּמַאי וְטָהֵר? טָהֵר יוֹמָא · סִימָן לַדָּבָר: צֵאת הַכּוֹכָבִים',translation:'What does “and it is purified” mean? The day becomes clear. A sign for the matter: the emergence of the stars.',independent:true,prompt:'What is the structure of this short passage?',answers:['A word-question, an interpretation, then evidence that helps clarify it.','A rule, an unrelated story, then a new tractate.','A final ruling with no argument.'],correct:0,skill:'berakhot2b-independent-sugya',competency:'argument',feedback:'This is independent sugya reading in miniature: question, answer, evidence.'}
]};
