window.SederCourse={stage:'berakhot-2a-depth',completeTitle:'You can now enter the opening sugya with a map.',completeCopy:'You recognized the Mishnah’s practical question, the Gemara’s context-question, and the verse-based answer. Next, build the proof skills that make the following discussion legible.',nextUrl:'berakhot-unit-2.html',nextLabel:'Continue to Berakhot 2b',steps:[
{short:'Orient to the Mishnah',mode:'ORIENT',title:'Find the practical question',ref:'Mishnah Berakhot 1:1',hebrew:'מֵאֵימָתַי קוֹרִין אֶת שְׁמַע בְּעַרְבִין?',translation:'From when do we recite Shema in the evenings?',prompt:'Before translating every word, what kind of opening is this?',answers:['A question about when a practice begins.','A final ruling about the latest time.','A narrative about someone praying.'],correct:0,skill:'berakhot-orientation',competency:'recognition',feedback:'Right. The Mishnah begins by posing a concrete question of time.'},
{short:'Recognize the question word',mode:'LANGUAGE',title:'Let one word orient you',ref:'Mishnah Berakhot 1:1',hebrew:'מֵאֵימָתַי',translation:'From when?',prompt:'What does this word let you predict about the sentence?',answers:['It is asking for a beginning point.','It is citing a verse.','It is announcing an objection.'],correct:0,skill:'berakhot-meimatai',competency:'translation',feedback:'Exactly. One reliable signal can give a learner footing before every word is known.'},
{short:'Separate Mishnah and Gemara',mode:'TEXT MAP',title:'A new voice enters',ref:'Berakhot 2a',hebrew:'תַּנָּא הֵיכָא קָאֵי דְּקָתָנֵי מֵאֵימָתַי?',translation:'What is the Mishnah addressing that it begins, “From when?”',prompt:'What has changed from the Mishnah’s opening line?',answers:['The Gemara is now asking about the Mishnah’s context.','The Mishnah is giving its final answer.','A different tractate has begun.'],correct:0,skill:'berakhot-mishnah-gemara',competency:'argument',feedback:'Good. Notice the page has moved from the Mishnah’s question to a question about why it begins there.'},
{short:'Name the Gemara move',mode:'ARGUMENT',title:'Ask what the question is about',ref:'Berakhot 2a',hebrew:'הֵיכָא קָאֵי',translation:'What earlier context is it standing on?',prompt:'What does the Gemara want the reader to investigate?',answers:['What prior context makes the Mishnah’s opening make sense.','The pronunciation of Shema.','The final time for the evening recitation.'],correct:0,skill:'berakhot-context-question',competency:'argument',feedback:'Right. Gemara often asks what problem or source a terse Mishnah is answering.'},
{short:'Spot a source signal',mode:'SOURCE SIGNAL',title:'The answer points to Torah',ref:'Berakhot 2a · Deuteronomy 6:7',hebrew:'תַּנָּא אַקְרָא קָאֵי, דִּכְתִיב: בְּשָׁכְבְּךָ וּבְקוּמֶךָ',translation:'The Mishnah relies on the verse, as it is written: “when you lie down and when you rise up.”',prompt:'What does dikhtiv tell you to expect?',answers:['A verse is being brought as evidence.','A personal example is beginning.','The discussion is finished.'],correct:0,skill:'berakhot-dikhtiv',competency:'sourceReasoning',feedback:'Exactly. The Gemara roots the Mishnah’s sequence in the language of Torah.'},
{short:'Explain the answer',mode:'REASONING',title:'Why does evening come first?',ref:'Berakhot 2a · Deuteronomy 6:7',hebrew:'בְּשָׁכְבְּךָ וּבְקוּמֶךָ',translation:'When you lie down and when you rise up.',prompt:'How does this verse answer the Gemara’s context-question?',answers:['It explains why the Mishnah begins with evening before morning.','It gives the exact clock time for Shema.','It changes the subject to a different mitzvah.'],correct:0,skill:'berakhot-verse-role',competency:'sourceReasoning',feedback:'Right. The verse supplies a reason for the Mishnah’s order, not just an ornament.'},
{short:'Trace the sequence',mode:'ARGUMENT MAP',title:'Put the movement in order',ref:'Berakhot 2a',hebrew:'מִשְׁנָה · שְׁאֵלָה · תְּשׁוּבָה מִן הַכָּתוּב',translation:'Mishnah · question · answer from a verse.',prompt:'Which summary best maps the opening sugya?',answers:['A timing question, a question about its context, then a verse-based answer.','A verse, a story, then an unrelated law.','A ruling with no reasoning.'],correct:0,skill:'berakhot-sugya-flow',competency:'argument',feedback:'You have a reusable map: claim or question, Gemara pressure, then a source-grounded response.'},
{short:'Independent read I',mode:'INDEPENDENT READ',title:'Read without the scaffold first',ref:'Berakhot 2a',hebrew:'תַּנָּא אַקְרָא קָאֵי',translation:'The Mishnah relies on a verse.',independent:true,prompt:'Before showing the translation, what is this line most likely doing?',answers:['Explaining the Mishnah through a biblical source.','Asking a new practical time question.','Introducing a disagreement between two people.'],correct:0,skill:'berakhot-independent-source',competency:'sourceReasoning',feedback:'Good. You inferred the job of the line from its signals. Use translation to confirm, not replace, that reading.'},
{short:'Independent read II',mode:'MASTERY CHECK',title:'Carry the move to a new phrase',ref:'Berakhot 2b',hebrew:'וּמַאי וְטָהֵר? טָהֵר יוֹמָא',translation:'What does “and it is purified” mean? The day becomes clear.',independent:true,prompt:'What is the Gemara doing here?',answers:['Focusing closely on the meaning of a word in its source.','Giving a final ruling with no question.','Returning to the Mishnah’s opening schedule.'],correct:0,skill:'berakhot-independent-word',competency:'argument',feedback:'This is the beginning of independent reading: identify the move even when the passage is unfamiliar.'}
]};
