const arcId=new URLSearchParams(location.search).get('track')||'chassidus';
const make=(title,intro,note,stage,nextUrl,nextLabel,steps)=>({title,intro,note,stage,nextUrl,nextLabel,completeTitle:`You completed the ${title} foundation.`,completeCopy:'You worked from a primary source, named the text’s central move, and used structured questions to turn reading into durable understanding.',steps});
const arcs={
chassidus:make('Chassidus: Inner Life Through Text','Read Chassidic sources as arguments about awareness, desire, prayer, and service—not as slogans detached from their textual roots.','Track concept, metaphor, source, and implication. Reflection follows reading; it does not replace it.','chassidus-inner-life','philosophy.html','Continue to Jewish Thought',[
{short:'A source names longing',mode:'CONCEPT',title:'Begin with desire',ref:'Psalms 27:4',hebrew:'אַחַת שָׁאַלְתִּי מֵאֵת ה׳',translation:'One thing I ask of the Lord.',prompt:'What inner question can this verse open?',answers:['What it means for a life to be oriented by a deepest desire.','Which claimant owns an object.','Which category of damages applies.'],correct:0,skill:'chassidus-desire',competency:'sourceReasoning',feedback:'Good. Chassidic reading begins from the source’s language about inner orientation.'},
{short:'Read a metaphor',mode:'METAPHOR',title:'A metaphor carries an idea',ref:'Proverbs 20:27',hebrew:'נֵר ה׳ נִשְׁמַת אָדָם',translation:'The human soul is the lamp of the Lord.',prompt:'What should a learner ask of this metaphor?',answers:['What qualities of a lamp illuminate the source’s account of the soul.','Which legal code settles the verse.','How to avoid interpreting imagery.'],correct:0,skill:'chassidus-metaphor',competency:'sourceReasoning',feedback:'Exactly. Metaphor is not decoration; it is a conceptual tool.'},
{short:'Name a practice',mode:'PRACTICE',title:'Intention joins action',ref:'Pirkei Avot 2:1',hebrew:'הֱוֵי זָהִיר בְּמִצְוָה קַלָּה כְּבַחֲמוּרָה',translation:'Be as careful with a light commandment as with a weighty one.',prompt:'How can a Chassidic reader extend this source responsibly?',answers:['Ask how attention and intention can deepen a practice without changing its legal form.','Replace practice with emotion alone.','Treat reflection as a personal ruling.'],correct:0,skill:'chassidus-intention',competency:'argument',feedback:'Right. Inner work can illuminate practice without displacing halakhic reasoning.'},
{short:'Compare voices',mode:'COMPARISON',title:'One source, more than one emphasis',ref:'Chassidic reading method',hebrew:'שִׂמְחָה · יִרְאָה',translation:'Joy · awe.',prompt:'What is a fair comparative question?',answers:['How might different Chassidic sources balance joy and awe in service?','Which concept makes the other unnecessary?','Why compare sources at all?'],correct:0,skill:'chassidus-compare',competency:'argument',feedback:'Good. Comparison preserves distinct emphases rather than flattening a tradition.'},
{short:'Keep the boundary',mode:'RESPONSIBLE READING',title:'Text before projection',ref:'Seder Chassidus method',hebrew:'מָקוֹר · מוּשָׂג · הַשְׁלָכָה',translation:'Source · concept · implication.',prompt:'What is the responsible order of learning?',answers:['Read the source, define its concept, then consider a possible implication.','Begin with a feeling and make the source agree.','Skip the text for a personal slogan.'],correct:0,skill:'chassidus-reading-order',competency:'sourceReasoning',feedback:'This keeps inner learning anchored in the text.'},
{short:'Independent reflection',mode:'INDEPENDENT READ',title:'Ask a source-grounded question',ref:'Psalms 27:4',hebrew:'לַחֲזוֹת בְּנֹעַם ה׳',translation:'To behold the pleasantness of the Lord.',independent:true,prompt:'What is a source-grounded next question?',answers:['How does the verse describe the relationship between attention, beauty, and divine service?','Which sentence is easiest to memorize?','What ruling should every person follow?'],correct:0,skill:'chassidus-independent',competency:'sourceReasoning',feedback:'You can now use a source to open a careful inner question.'}]),
mussar:make('Mussar: Character Through Sources','Study middot through close reading, realistic situations, repeated practice, and honest reflection. Mussar is moral formation grounded in a tradition, not a score for self-worth.','Name a trait, read a claim, examine a situation, and return to the source over time.','mussar-character-arc','subject.html?track=mussar','Return to Mussar path',[
{short:'Name a middah',mode:'MIDDOT',title:'Humility is a reading question',ref:'Micah 6:8',hebrew:'וְהַצְנֵעַ לֶכֶת עִם אֱלֹהֶיךָ',translation:'Walk humbly with your God.',prompt:'What does a Mussar learner first ask?',answers:['What kind of humility does this source describe, and what does it exclude?','Which person wins a dispute?','What time a prayer begins?'],correct:0,skill:'mussar-name-trait',competency:'sourceReasoning',feedback:'Good. A middah must be defined before it can form a person.'},
{short:'Read a tension',mode:'MIDDOT',title:'Humility is not passivity',ref:'Pirkei Avot 2:5',hebrew:'וְלֹא הַבַּיְשָׁן לָמֵד',translation:'The shy person does not learn.',prompt:'What tension does this source help a learner notice?',answers:['Humility can coexist with the courage to ask and participate.','Humility means never speaking.','Learning has no relation to character.'],correct:0,skill:'mussar-tension',competency:'argument',feedback:'Exactly. Ethical traits need nuance, not caricature.'},
{short:'Move to a case',mode:'SITUATION',title:'A trait meets a moment',ref:'Mussar case practice',hebrew:'כָּבוֹד הַבְּרִיּוֹת',translation:'Human dignity.',prompt:'What should a learner ask before applying a value to a situation?',answers:['Which facts matter, what values are in tension, and what the source actually claims.','Which value sounds nicest in isolation.','How to avoid responsibility.'],correct:0,skill:'mussar-case',competency:'argument',feedback:'Mussar becomes serious when sources meet real complexity.'},
{short:'Form a habit',mode:'PRACTICE',title:'Small repetition matters',ref:'Pirkei Avot 4:2',hebrew:'מִצְוָה גּוֹרֶרֶת מִצְוָה',translation:'One mitzvah leads to another mitzvah.',prompt:'What formation question can this open?',answers:['How repeated acts can shape attention and future choices.','Which source cancels all other sources.','Why habits are irrelevant to character.'],correct:0,skill:'mussar-habit',competency:'sourceReasoning',feedback:'Good. Mussar asks how repeated practice forms a person over time.'},
{short:'Reflect without scoring',mode:'REFLECTION',title:'Evidence is not self-worth',ref:'Seder Mussar method',hebrew:'חֶשְׁבּוֹן · חֶסֶד',translation:'Accountability · kindness.',prompt:'What is a healthy reflective move?',answers:['Notice a pattern honestly and return to a source without turning the reflection into self-condemnation.','Treat every miss as proof of failure.','Avoid reflection entirely.'],correct:0,skill:'mussar-reflection',competency:'sourceReasoning',feedback:'Moral growth needs both accountability and compassion.'},
{short:'Independent ethical read',mode:'INDEPENDENT READ',title:'Name the claim and question',ref:'Micah 6:8',hebrew:'וְעֲשׂוֹת מִשְׁפָּט וְאַהֲבַת חֶסֶד',translation:'Do justice and love kindness.',independent:true,prompt:'What is the best next reading move?',answers:['Ask how justice and kindness relate, especially when a situation makes them feel in tension.','Choose one word and ignore the other.','Treat the verse as a shortcut around judgment.'],correct:0,skill:'mussar-independent',competency:'sourceReasoning',feedback:'You can now let a source frame an ethical question rather than merely supply a slogan.'}]),
history:make('Jewish History: Texts in Time','Read Jewish history through primary sources, communities, institutions, and interpretive debates. Events matter; so do the voices that describe and remember them.','Ask who speaks, to whom, in what setting, and what evidence supports an historical claim.','history-context-arc','subject.html?track=history','Return to History path',[
{short:'Locate a voice',mode:'CONTEXT',title:'Every source has an audience',ref:'Jeremiah 29:7',hebrew:'וּדְרְשׁוּ אֶת־שְׁלוֹם הָעִיר',translation:'Seek the welfare of the city.',prompt:'What historical question should come first?',answers:['Who receives this message, in what political setting, and what response is being asked of them?','Which later reader is automatically correct?','Why context never matters.'],correct:0,skill:'history-audience',competency:'sourceReasoning',feedback:'Good. Historical reading starts by locating a source in a human world.'},
{short:'Distinguish event and memory',mode:'HISTORY',title:'A source is not the whole past',ref:'Historical method',hebrew:'זִכָּרוֹן · עֵדוּת',translation:'Memory · testimony.',prompt:'What distinction helps a learner read a historical source?',answers:['A source may be evidence about an event and also evidence about how someone remembered it.','Every source is a neutral camera.','Memory has no historical value.'],correct:0,skill:'history-memory',competency:'sourceReasoning',feedback:'Exactly. Sources are both windows and voices.'},
{short:'Meet a community',mode:'COMMUNITY',title:'Texts travel with people',ref:'Talmudic diaspora context',hebrew:'בָּבֶל · אֶרֶץ יִשְׂרָאֵל',translation:'Babylonia · Land of Israel.',prompt:'What does this comparison make possible?',answers:['Ask how place, language, institutions, and community shape Jewish learning.','Assume all Jewish communities lived identically.','Treat geography as irrelevant to texts.'],correct:0,skill:'history-community',competency:'sourceReasoning',feedback:'History helps learners see that texts are studied by communities in particular places.'},
{short:'Compare accounts',mode:'INTERPRETATION',title:'More than one narrative can exist',ref:'Historical method',hebrew:'מָקוֹר · פֵּרוּשׁ · רְאָיָה',translation:'Source · interpretation · evidence.',prompt:'What is a responsible comparison move?',answers:['State what each account claims and what evidence it uses before choosing an interpretation.','Choose the account that confirms a prior assumption.','Treat disagreement as proof that history cannot be studied.'],correct:0,skill:'history-compare-accounts',competency:'argument',feedback:'Good. Historical disagreement can be studied through evidence and perspective.'},
{short:'Trace an institution',mode:'INSTITUTION',title:'Ideas take social form',ref:'Jewish communal history',hebrew:'בֵּית מִדְרָשׁ · קְהִלָּה',translation:'Study house · community.',prompt:'What question does this pair invite?',answers:['How institutions sustain learning, practice, authority, and belonging across time.','Which phrase is easiest to translate.','Why communities do not affect texts.'],correct:0,skill:'history-institution',competency:'sourceReasoning',feedback:'Texts, practices, and institutions shape one another.'},
{short:'Independent context read',mode:'INDEPENDENT READ',title:'Ask the historical questions',ref:'Jeremiah 29:7',hebrew:'וּדְרְשׁוּ אֶת־שְׁלוֹם הָעִיר',independent:true,translation:'Seek the welfare of the city.',prompt:'What is the best first historical map for this verse?',answers:['Speaker, audience, setting, purpose, and later reception.','A personal reaction without context.','A final legal ruling for every society.'],correct:0,skill:'history-independent',competency:'sourceReasoning',feedback:'You can now begin placing a source within time, community, and interpretation.'}]),
widerworld:make('Judaism & the Wider World: Comparative Reading','Study Jewish law and thought in dialogue with broader human canons without collapsing differences or imagining that comparison means sameness.','Begin with a Jewish source, name the shared question, locate the setting, then compare concepts and disagreements precisely.','wider-world-arc','philosophy.html','Continue to Jewish Thought',[
{short:'Start from a Jewish source',mode:'COMPARATIVE ORIENTATION',title:'A Jewish source frames the question',ref:'Jeremiah 29:7',hebrew:'וּדְרְשׁוּ אֶת־שְׁלוֹם הָעִיר',translation:'Seek the welfare of the city.',prompt:'What comparative question can this open?',answers:['How Jewish communities understand responsibility toward the societies in which they live.','Whether all civilizations think the same way.','Which external canon replaces Jewish sources.'],correct:0,skill:'widerworld-jewish-start',competency:'sourceReasoning',feedback:'Good. Comparison starts from a real source and a precise question.'},
{short:'Name a shared question',mode:'COMPARISON',title:'Similarity is not identity',ref:'Comparative method',hebrew:'חָכְמָה · תּוֹרָה',translation:'Wisdom · Torah.',prompt:'What is a responsible first comparison?',answers:['Ask how two traditions define a shared word or question before declaring them equivalent.','Assume shared vocabulary proves shared meaning.','Ignore historical context.'],correct:0,skill:'widerworld-shared-question',competency:'argument',feedback:'Exactly. Shared questions can lead to very different conceptual worlds.'},
{short:'Locate an encounter',mode:'HISTORY',title:'Ideas travel through languages and communities',ref:'Medieval Jewish intellectual history',hebrew:'עֲרָבִית · עִבְרִית · לָטִינִית',translation:'Arabic · Hebrew · Latin.',prompt:'What does this linguistic map make possible?',answers:['Study translation, exchange, disagreement, and adaptation across intellectual worlds.','Assume ideas never cross communities.','Reduce history to a list of dates.'],correct:0,skill:'widerworld-encounter',competency:'sourceReasoning',feedback:'Jewish thinkers often worked in multilingual intellectual settings.'},
{short:'Law in society',mode:'HALAKHA CONNECTION',title:'Practice meets public life',ref:'Halakhic comparative method',hebrew:'דִּין · קְהִלָּה · מְדִינָה',translation:'Law · community · polity.',prompt:'What kind of question belongs here?',answers:['How covenantal legal reasoning addresses institutions, commerce, medicine, or public responsibility.','Whether law and society are unrelated.','Whether an app can issue personal rulings.'],correct:0,skill:'widerworld-law-society',competency:'sourceReasoning',feedback:'This is a place where Halakha and wider civic worlds meet without becoming identical.'},
{short:'Thought in dialogue',mode:'PHILOSOPHY CONNECTION',title:'Reason and revelation meet a wider canon',ref:'Jewish Philosophy method',hebrew:'שֵׂכֶל · נְבוּאָה',translation:'Reason · prophecy.',prompt:'What is a careful learning question?',answers:['How Jewish thinkers relate reason and revelation while engaging wider philosophical vocabularies.','Which tradition has no internal differences.','Why texts need no interpretation.'],correct:0,skill:'widerworld-reason-revelation',competency:'argument',feedback:'Good. Dialogue includes reception, disagreement, and creative reinterpretation.'},
{short:'Independent comparison',mode:'INDEPENDENT READ',title:'Compare without flattening',ref:'Comparative reading checkpoint',hebrew:'מָקוֹר · הֶקְשֵׁר · הַשְׁוָאָה',translation:'Source · context · comparison.',independent:true,prompt:'What is the responsible order of comparative learning?',answers:['Read each source in context, name the shared question, then compare similarity and difference.','Start with a broad stereotype and fit the sources to it.','Assume comparison eliminates disagreement.'],correct:0,skill:'widerworld-independent',competency:'sourceReasoning',feedback:'You can now compare traditions with curiosity, accuracy, and respect for difference.'}])};
window.SederCourse=arcs[arcId]||arcs.chassidus;document.querySelector('#header').textContent=window.SederCourse.title.toUpperCase();document.querySelector('#arcTitle').textContent=window.SederCourse.title;document.querySelector('#arcIntro').textContent=window.SederCourse.intro;document.querySelector('#arcNote').textContent=window.SederCourse.note;
