window.SederCourse={stage:'chassidus-joy-awe-arc',completeTitle:'You can now hold joy and awe together as a reading question.',completeCopy:'You named a source-grounded desire, held joy and awe together rather than as opposites, read a metaphor for the soul, and connected inner posture to practice without turning reflection into a personal ruling. A second foundation is ready: <a href="chassidus-ahavat-yisrael.html">read love of a fellow as a Chassidic gateway →</a>',nextUrl:'gemara-continuation.html',nextLabel:'Return to your Gemara path',steps:[
{short:'Name the desire',mode:'CONCEPT',title:'Begin with a single desire',ref:'Psalms 27:4',hebrew:'אַחַת שָׁאַלְתִּי מֵאֵת ה׳',translation:'One thing I ask of the Lord.',prompt:'What inner question does this verse open for a Chassidic reader?',answers:['What it means for a life to be oriented by a single deepest desire.','Which claimant owns an object.','Which category of damages applies.'],correct:0,skill:'chassidus-joy-desire',competency:'sourceReasoning',feedback:'Good. Chassidic reading begins from the source’s language about inner orientation.'},
{short:'Hold two postures together',mode:'COMPARISON',title:'Not opposites, but a pair',ref:'Psalms 2:11',hebrew:'עִבְדוּ אֶת ה׳ בְּיִרְאָה וְגִילוּ בִּרְעָדָה',translation:'Serve the Lord with awe, and rejoice with trembling.',prompt:'What interpretive question is most useful for this pairing?',answers:['How joy and awe may be held together rather than treated as opposites.','Which emotion removes the need for practice.','Which word is easiest to memorize.'],correct:0,skill:'chassidus-joy-awe-pair',competency:'argument',feedback:'Right. Chassidic sources often hold two postures in tension rather than resolving one into the other.'},
{short:'Read the metaphor',mode:'METAPHOR',title:'A metaphor carries an idea',ref:'Proverbs 20:27',hebrew:'נֵר ה׳ נִשְׁמַת אָדָם',translation:'The human soul is the lamp of the Lord.',prompt:'What should a learner ask of this metaphor?',answers:['What qualities of a lamp illuminate the source’s account of the soul.','Which legal code settles the verse.','How to avoid interpreting imagery.'],correct:0,skill:'chassidus-joy-metaphor',competency:'sourceReasoning',feedback:'Exactly. Metaphor is not decoration; it is a conceptual tool.'},
{short:'Connect posture to practice',mode:'PRACTICE',title:'Joy and awe reach into action',ref:'Pirkei Avot 2:1',hebrew:'הֱוֵי זָהִיר בְּמִצְוָה קַלָּה כְּבַחֲמוּרָה',translation:'Be as careful with a light commandment as with a weighty one.',prompt:'How can joy and awe extend this teaching about small and large practice?',answers:['Ask how attention, joy, and awe can deepen a practice without changing its legal form.','Replace practice with emotion alone.','Treat reflection as a personal ruling.'],correct:0,skill:'chassidus-joy-practice',competency:'argument',feedback:'Right. Inner posture can illuminate practice without displacing halakhic reasoning.'},
{short:'Keep the reading order',mode:'RESPONSIBLE READING',title:'Text before projection',ref:'Seder Chassidus method',hebrew:'מָקוֹר · מוּשָׂג · הַשְׁלָכָה',translation:'Source · concept · implication.',prompt:'What is the responsible order of learning here?',answers:['Read the source, define its concept, then consider a possible implication.','Begin with a feeling and make the source agree.','Skip the text for a personal slogan.'],correct:0,skill:'chassidus-joy-order',competency:'sourceReasoning',feedback:'This keeps inner learning anchored in the text.'},
{short:'Deepen the verse',mode:'CONCEPT',title:'What the desire is actually for',ref:'Psalms 27:4',hebrew:'לַחֲזוֹת בְּנֹעַם ה׳',translation:'To behold the pleasantness of the Lord.',prompt:'How does this phrase extend the desire named in step one?',answers:['It names what the single desire is actually oriented toward: beholding pleasantness, not merely wanting.','It cancels the earlier desire entirely.','It has no relationship to the earlier verse.'],correct:0,skill:'chassidus-joy-deepen',competency:'argument',feedback:'Good. A verse can extend and specify an idea introduced earlier in the same passage.'},
{short:'Transfer the tension',mode:'TRANSFER',title:'A Mussar source, a Chassidic question',ref:'Pirkei Avot 2:5',hebrew:'וְלֹא הַבַּיְשָׁן לָמֵד',translation:'The shy person does not learn.',prompt:'This source comes from Mussar study. What question does it also raise for joy and awe?',answers:['Whether awe can tip into a hesitation that blocks the courage joy requires.','Whether shyness is unrelated to religious life.','Whether Mussar and Chassidus never share any concerns.'],correct:0,skill:'chassidus-joy-transfer',competency:'sourceReasoning',feedback:'The same source can open related questions across different subjects.'},
{short:'Independent read',mode:'INDEPENDENT READ',title:'Map the inner posture on your own',ref:'Chassidus checkpoint',hebrew:'אַחַת שָׁאַלְתִּי · שִׂמְחָה · יִרְאָה',translation:'One thing I ask · joy · awe.',independent:true,prompt:'What is the first independent-reading move across these three fragments?',answers:['Name the desire, then ask how joy and awe each shape the way that desire is pursued.','Pick whichever fragment feels most comforting.','Assume the three fragments are unrelated.'],correct:0,skill:'chassidus-joy-independent',competency:'sourceReasoning',feedback:'You can now hold desire, joy, and awe together as one connected reading question.'}
]};
