window.SederCourse={stage:'chullin-tractate-arc',completeTitle:'You can now read a general rule through its own exception.',completeCopy:'You named a broad rule, found its exception, traced the exception\'s own reason, and saw how a second detail — supervision — can override that reason without erasing it. These skills carry into any tractate built from a rule, an exception, and a condition that reshapes both.',nextUrl:'lab.html?tractate=chullin',nextLabel:'Practice on the Chullin working Daf',steps:[
{short:'Find the subject',mode:'CASE ORIENTATION',title:'A broad rule opens the tractate',ref:'Mishnah Chullin 1:1',hebrew:'הַכֹּל שׁוֹחֲטִין וּשְׁחִיטָתָן כְּשֵׁרָה',translation:'All may slaughter, and their slaughter is valid.',prompt:'What does the Mishnah state before listing any qualifications or exceptions?',answers:['A broad statement about who may validly perform an action.','A story about a festival.','A measure of a courtyard.'],correct:0,skill:'chullin-subject',competency:'recognition',feedback:'Good. First locate the scope of the statement — the exceptions have not appeared yet.'},
{short:'Notice the scope',mode:'CASE ORIENTATION',title:'A general word creates work',ref:'Mishnah Chullin 1:1',hebrew:'הַכֹּל',translation:'All.',prompt:'What should a careful Gemara reader ask when seeing “all”?',answers:['Who is really included, and whether any exceptions are about to qualify it.','What page comes next.','Which word is a verse.'],correct:0,skill:'chullin-scope',competency:'sourceReasoning',feedback:'Exactly. General language like “all” often becomes the focus of a close Gemara analysis.'},
{short:'Name the exception',mode:'LEGAL CATEGORY',title:'The rule immediately narrows',ref:'Mishnah Chullin 1:1',hebrew:'חוּץ מֵחֵרֵשׁ שׁוֹטֶה וְקָטָן',translation:'Except a deaf-mute, an imbecile, and a minor.',prompt:'What does naming these three exceptions do to the opening rule?',answers:['It narrows “all” to exclude three specific categories of people from validly performing the act on their own.','It cancels the rule completely.','It adds three more people who may always slaughter.'],correct:0,skill:'chullin-exception',competency:'sourceReasoning',feedback:'Right. A sweeping rule is almost never left unqualified — the exception clause is where the real legal content often lives.'},
{short:'Give the reason',mode:'SOURCE LAYER',title:'The exception has its own reason',ref:'Mishnah Chullin 1:1',hebrew:'שֶׁמָּא יְקַלְקְלוּ',translation:'Lest they spoil it.',prompt:'What kind of concern does this phrase reveal about why these three are excluded?',answers:['A concern about competence and reliability in performing the act correctly, not a personal judgment about their worth.','A concern that has nothing to do with the act of slaughter itself.','A concern that applies equally to every person, with no exceptions at all.'],correct:0,skill:'chullin-reason',competency:'argument',feedback:'Good. “Lest they spoil it” names a functional worry about reliable performance — this is what makes the exception a legal category, not a label.'},
{short:'Weigh the supervision clause',mode:'DISTINCTION',title:'The same rule, one condition later',ref:'Mishnah Chullin 1:1',hebrew:'וְכֻלָּן שֶׁשָּׁחֲטוּ וַאֲחֵרִים רוֹאִין אוֹתָן שְׁחִיטָתָן כְּשֵׁרָה',translation:'But if any of them slaughtered while others were watching, their slaughter is valid.',prompt:'What does this final clause reveal about the true concern behind the exception?',answers:['The concern was reliable performance, not fixed personal status — supervision by others resolves it without changing who the person is.','The exception clause was a mistake that this line simply erases.','Supervision has no legal effect at all.'],correct:0,skill:'chullin-supervision',competency:'argument',feedback:'Exactly. The Mishnah names a concern, then shows a condition that satisfies that same concern — a pattern worth recognizing across Shas.'},
{short:'Name the move',mode:'LEGAL CATEGORY',title:'Rule, exception, condition',ref:'Chullin 2a reading habit',hebrew:'כְּלָל · יוֹצֵא מִן הַכְּלָל · תְּנַאי',translation:'A rule · what departs from the rule · a condition.',prompt:'Which sequence describes the structure you just traced?',answers:['A broad rule, a narrowing exception, and a condition that reopens the rule for the excluded cases.','A final ruling stated once with no discussion.','Three unrelated statements placed next to each other by accident.'],correct:0,skill:'chullin-structure',competency:'argument',feedback:'This three-part shape — rule, exception, condition — recurs across many opening Mishnayot.'},
{short:'Keep the boundary',mode:'RESPONSIBLE LEARNING',title:'Kashrut needs a qualified authority',ref:'Seder learning boundary',hebrew:'לִלְמוֹד · לְהָבִין · לִשְׁאוֹל',translation:'To learn · to understand · to ask.',prompt:'How should a learner treat this source about a practical, halakhically consequential activity?',answers:['Study its structure and reasoning carefully while recognizing that any real kashrut question needs a qualified authority, not this course.','Treat the Mishnah as sufficient personal guidance for a real question about kosher slaughter.','Avoid the topic because it concerns practical law.'],correct:0,skill:'chullin-non-psak-boundary',competency:'sourceReasoning',feedback:'Right. Source literacy includes knowing exactly where study ends and a real practical question begins.'},
{short:'Transfer the habit',mode:'TRANSFER',title:'A fixed detail concealed a reason before',ref:'Ketubot 2a',hebrew:'בָּתֵּי דִינִין יוֹשְׁבִין בָּעֲיָירוֹת בַּשֵּׁנִי וּבַחֲמִישִׁי',translation:'Courts sit in the towns on Monday and Thursday.',prompt:'You already learned that Ketubot’s Wednesday schedule concealed an institutional reason. What does that habit add to reading Chullin’s exception clause?',answers:['A rule or an exception is rarely arbitrary — asking what functional concern it serves often uncovers a condition that can satisfy that same concern.','That every legal detail is decorative and has no underlying reason.','That reasons behind rules can never be recovered from the text.'],correct:0,skill:'chullin-transfer',competency:'sourceReasoning',feedback:'The same discipline — ask what concern a detail serves — reads a wedding schedule and a slaughtering exception with the same care.'},
{short:'Independent read',mode:'INDEPENDENT READ',title:'Map the rule on your own',ref:'Chullin 2a reading checkpoint',hebrew:'הַכֹּל שׁוֹחֲטִין · חוּץ מֵחֵרֵשׁ שׁוֹטֶה וְקָטָן · שֶׁמָּא יְקַלְקְלוּ',translation:'All may slaughter · except a deaf-mute, an imbecile, and a minor · lest they spoil it.',independent:true,prompt:'What is the first independent-reading move across these three fragments?',answers:['Name the broad rule, find its exception, then ask what concern the exception is protecting against.','Assume the rule applies with no exceptions.','Memorize the English without tracking the Hebrew structure.'],correct:0,skill:'chullin-independent-map',competency:'sourceReasoning',feedback:'You can now enter a rule-and-exception sugya with a concrete map.'},
{short:'Type the meaning',mode:'PRODUCTION CHECK',title:'Recall, don’t just recognize',ref:'Mishnah Chullin 1:1',hebrew:'שֶׁמָּא יְקַלְקְלוּ',translation:'Lest they spoil it / ruin it.',independent:true,typed:true,prompt:'Type the English meaning of this phrase in a few words.',acceptable:['lest they spoil it','lest they ruin it','they might ruin it','they might spoil it','lest they spoil','lest they ruin'],skill:'chullin-typed-recall',competency:'translation',feedback:'Typing an answer from memory is a stronger test of durable mastery than recognizing it among choices.'}
]};
// Alternatives distinguish scope and qualification without making the longest answer predictable.
const chullinSteps=window.SederCourse.steps;
chullinSteps[0].answers=['A broad statement about who may validly perform an action.','A festival narrative that happens to mention an action but does not state its legal scope.','A courtyard measurement whose dimensions determine whether the action is valid.'];
chullinSteps[1].answers=['Who is really included, and whether any exceptions are about to qualify it.','Which following page will repeat the same word without changing the scope of the statement.','Whether the word should be treated as a verse rather than as broad language in a Mishnah.'];

// [rebalance] distractor lengths evened so the correct answer is not the longest option
window.SederCourse.steps[2].answers[1]="It cancels the entire opening rule completely and leaves nothing at all in its place.";
window.SederCourse.steps[2].answers[2]="It adds three more categories of people who may now always validly slaughter.";
window.SederCourse.steps[3].answers[1]="A concern that in the end has nothing at all to do with the act of slaughter itself.";
window.SederCourse.steps[3].answers[2]="A concern that applies fully and equally to every single person, with no exceptions at all.";
window.SederCourse.steps[4].answers[1]="The original exception clause was simply a mistake, one that this later line quietly erases altogether.";
window.SederCourse.steps[4].answers[2]="Supervision by others has no legal effect whatsoever on whether the act itself may validly be performed.";
window.SederCourse.steps[5].answers[1]="A single final ruling stated just once, with no further discussion of it at all.";
window.SederCourse.steps[5].answers[2]="Three entirely unrelated statements placed next to one another purely by accident.";
window.SederCourse.steps[6].answers[2]="Avoid the topic altogether simply because it happens to concern difficult matters of practical law.";
window.SederCourse.steps[7].answers[1]="That every single legal detail is purely decorative and carries no underlying reason of its very own at all.";
window.SederCourse.steps[7].answers[2]="That the reasons standing behind the rules can essentially never be recovered from the plain text itself.";
window.SederCourse.steps[8].answers[1]="Assume that the broad rule simply applies everywhere with no exceptions of any kind at all.";
window.SederCourse.steps[8].answers[2]="Memorize only the English translation without ever tracking the Hebrew structure at all.";
