window.SederCourse={stage:'chumash-akeidah-arc',completeTitle:'You can now read biblical narrative as a crafted text.',completeCopy:'You watched a narrator share knowledge the character lacks, followed one word — hineni — through three costly moments, heard repetition frame a silence, held a deliberate ambiguity open, and saw the whole story enter the shofar of Rosh Hashanah. Legal verses were your first Chumash skill; narrative art is now your second. A third genre remains: <a href="chumash-tehillim.html">read the line that says it twice →</a>',nextUrl:'lab.html?tractate=rosh-hashanah',nextLabel:'Meet the Akeidah’s home in practice: Rosh Hashanah',steps:[
{short:'The narrator knows',mode:'NARRATIVE ORIENTATION',title:'The reader is told what Abraham is not',ref:'Genesis 22:1',hebrew:'וְהָאֱלֹהִים נִסָּה אֶת אַבְרָהָם',translation:'And God tested Abraham.',prompt:'The narrator tells the reader this is a test. Abraham is never told. What does this narrative choice create?',answers:['A gap between what the reader knows and what the character knows, which shapes how every following verse is read.','Reassurance that softens the story, since the reader knows Isaac will survive.','A signal that the story is a parable rather than an event to be read literally.'],correct:0,skill:'chumash-akeidah-narrator',competency:'sourceReasoning',feedback:'Good. Biblical narrative is crafted: the disclosure creates a reading position, not comfort — knowing it is a test makes Abraham’s not-knowing heavier, and says nothing about parable versus event.'},
{short:'First hineni',mode:'KEY WORD',title:'One word of readiness',ref:'Genesis 22:1',hebrew:'וַיֹּאמֶר אֵלָיו אַבְרָהָם וַיֹּאמֶר הִנֵּנִי',translation:'He said to him, “Abraham,” and he said, “Here I am.”',prompt:'Abraham answers God’s call with a single word: hineni. What should a close reader do with a one-word answer?',answers:['Mark it, and watch whether the word returns — a repeated word in a spare text usually carries weight.','Translate it precisely, since its grammar carries the verse’s meaning.','Compare how other biblical figures answer when God calls them by name.'],correct:0,skill:'chumash-akeidah-hineni-first',competency:'recognition',feedback:'Exactly. Biblical prose is economical; the word’s weight here comes from its return, not its grammar — and the comparison across figures is a fine later move, after you have followed this story’s own thread.'},
{short:'Mounting phrases',mode:'LITERARY SHAPE',title:'The command slows down',ref:'Genesis 22:2',hebrew:'קַח נָא אֶת בִּנְךָ אֶת יְחִידְךָ אֲשֶׁר אָהַבְתָּ אֶת יִצְחָק',translation:'Take your son, your only one, whom you love — Isaac.',prompt:'The command could have said “take Isaac.” Instead four phrases build toward the name. What does the escalation do?',answers:['It makes the reader feel the weight of the demand growing phrase by phrase before the name lands.','It supplies legal precision, since “your son” alone could mean Ishmael.','It softens the command by recalling how deeply Abraham loves his son.'],correct:0,skill:'chumash-akeidah-escalation',competency:'sourceReasoning',feedback:'Right. The text’s pacing is part of its meaning — the midrash Rashi cites does hear disambiguation in the phrases, but as a dialogue of delay, not legal drafting; and naming the love sharpens the demand rather than softening it.'},
{short:'Repetition frames',mode:'LITERARY SHAPE',title:'One clause, said twice',ref:'Genesis 22:6 · 22:8',hebrew:'וַיֵּלְכוּ שְׁנֵיהֶם יַחְדָּו',translation:'And the two of them walked together.',prompt:'This clause appears twice — before and after the only conversation between father and son on the mountain road. What does the repetition frame?',answers:['It brackets the exchange, inviting the reader to ask whether “together” means the same thing after the conversation as before it.','It emphasizes that father and son remained in full agreement throughout.','It marks the passage of time between two stages of the long journey.'],correct:0,skill:'chumash-akeidah-repetition',competency:'sourceReasoning',feedback:'Exactly. Repetition in a spare text is structure — the frame poses the question of what changed; reading it as agreement or as a time-marker answers that question before asking it.'},
{short:'Second hineni',mode:'KEY WORD',title:'The same word, to a different call',ref:'Genesis 22:7',hebrew:'וַיֹּאמֶר אָבִי וַיֹּאמֶר הִנֶּנִּי בְנִי',translation:'He said, “My father,” and he said, “Here I am, my son.”',prompt:'Isaac calls, and Abraham answers with the same word he gave God — now with “my son” attached. What does the repetition let the reader weigh?',answers:['What full presence costs when the one calling is the son the command concerns — the same readiness now points in two directions.','How a parent’s love for a child mirrors a servant’s devotion to God.','Whether Isaac has begun to suspect what his father intends to do.'],correct:0,skill:'chumash-akeidah-hineni-son',competency:'argument',feedback:'Good. Tracking one word across speakers is how narrative close reading builds an argument — the mirror-reading flattens the tension into harmony, and Isaac’s suspicion is a real question the next verse raises, not this one.'},
{short:'Hold the ambiguity',mode:'INTERPRETATION',title:'An answer that can be read two ways',ref:'Genesis 22:8',hebrew:'אֱלֹהִים יִרְאֶה לּוֹ הַשֶּׂה לְעֹלָה בְּנִי',translation:'God will see to the sheep for the offering, my son.',prompt:'“My son” can be read as address (“…the sheep, my son”) or as the terrible answer itself (“the sheep for the offering is my son”). What is the responsible reading move?',answers:['Notice that the syntax genuinely allows both, and hold the ambiguity as part of what the verse does.','Choose the address reading, since Abraham would surely shield his son from the truth.','Choose the terrible reading, since the story’s trajectory points toward it.'],correct:0,skill:'chumash-akeidah-ambiguity',competency:'argument',feedback:'Right. Some biblical ambiguity is load-bearing — both proposed resolutions have reasons, which is exactly why interpreters across centuries have kept both readings alive rather than closing the verse.'},
{short:'Third hineni',mode:'KEY WORD',title:'The call that interrupts',ref:'Genesis 22:11',hebrew:'אַבְרָהָם אַבְרָהָם וַיֹּאמֶר הִנֵּנִי',translation:'“Abraham! Abraham!” And he said, “Here I am.”',prompt:'At the story’s peak the angel calls the name twice, and Abraham gives his third hineni. What has the repeated word now traced?',answers:['A complete arc of presence — answering God’s command, answering his son’s question, and answering the call that stops the knife.','Abraham’s growing certainty that the command would be withdrawn.','A formula of politeness the text uses whenever anyone is addressed.'],correct:0,skill:'chumash-akeidah-hineni-third',competency:'sourceReasoning',feedback:'Exactly. The doubled name marks urgency; the third hineni completes the word’s journey — an arc of presence, not a prediction of rescue and not mere etiquette.'},
{short:'Reception in practice',mode:'RECEPTION',title:'The story enters the shofar',ref:'Rosh Hashanah 16a',hebrew:'תִּקְעוּ לְפָנַי בְּשׁוֹפָר שֶׁל אַיִל כְּדֵי שֶׁאֶזְכּוֹר לָכֶם עֲקֵידַת יִצְחָק',translation:'Sound before Me a shofar of a ram, so that I will remember for you the binding of Isaac.',prompt:'The Gemara connects the ram’s-horn shofar to this narrative. What kind of reception is this?',answers:['A narrative becoming the stated meaning of a yearly embodied practice — a different afterlife than a verse becoming a legal category.','A legal derivation: the shofar must be a ram’s horn because of the Akeidah.','A homily attached to the shofar after the practice was already fixed.'],correct:0,skill:'chumash-akeidah-reception',competency:'sourceReasoning',feedback:'Good. The Gemara’s language is memory and meaning — “so that I will remember” — which is neither a derivation of the law’s source nor a detachable homily; the story lives inside the practice.'},
{short:'Independent narrative map',mode:'INDEPENDENT READ',title:'Trace the word yourself',ref:'Genesis 22:1 · 22:7 · 22:11',hebrew:'הִנֵּנִי · הִנֶּנִּי בְנִי · הִנֵּנִי',translation:'Here I am · here I am, my son · here I am.',independent:true,prompt:'What should a reader recognize across these three fragments?',answers:['One repeated word structuring a whole narrative — the same reader’s move that traced “when you lie down and rise up” now applied to story.','Three moments of increasing confidence, ending in relief.','A refrain marking the story’s three scenes, like a poem’s chorus.'],correct:0,skill:'chumash-akeidah-independent',competency:'sourceReasoning',feedback:'This is narrative literacy: the word structures the story, but not as a chorus and not as a comfort-arc — each return costs differently, and reading that difference is the skill.'},
{short:'Type the meaning',mode:'PRODUCTION CHECK',title:'Recall, don’t just recognize',ref:'Genesis 22:1',hebrew:'הִנֵּנִי',translation:'Here I am.',independent:true,typed:true,prompt:'Type the English meaning of this word.',acceptable:['here i am','here am i','i am here'],skill:'chumash-akeidah-typed-recall',competency:'translation',feedback:'Typing an answer from memory is a stronger test of durable mastery than recognizing it among choices.'}
]};

// [rebalance] distractor lengths evened so the correct answer is not the longest option
window.SederCourse.steps[3].answers[1]="It emphasizes that father and son stayed in full agreement throughout, as united in purpose at the mountain as they had been when they first set out.";
window.SederCourse.steps[3].answers[2]="It marks nothing more than the passage of ordinary time between two separate stages of a single long and otherwise uneventful journey.";
window.SederCourse.steps[4].answers[1]="How a parent's ordinary love for a child naturally mirrors a devoted servant's readiness to answer the very moment his master calls.";
window.SederCourse.steps[4].answers[2]="Whether Isaac, still walking on beside his father, has quietly begun to suspect what the journey is really meant to accomplish.";
window.SederCourse.steps[6].answers[1]="Abraham's steadily growing private certainty that the terrible command was surely going to be withdrawn well before the end.";
window.SederCourse.steps[6].answers[2]="A mere formula of politeness that the text falls back on automatically whenever any character happens to be addressed by another.";
window.SederCourse.steps[7].answers[1]="A legal derivation, in which the shofar has to be a ram's horn precisely because a ram was offered up in Isaac's place at the Akeidah.";
window.SederCourse.steps[7].answers[2]="A late homily that was loosely attached to the shofar only after the yearly ram's-horn practice had itself already been fixed.";
window.SederCourse.steps[8].answers[1]="Three separate moments of steadily increasing confidence, building one upon another across the story until they finally end in relief.";
window.SederCourse.steps[8].answers[2]="A simple refrain that marks the transitions between the story's three scenes, working much like the recurring chorus of a poem.";
