window.SederCourse={stage:'chumash-shema-arc',completeTitle:'You can now trace a verse into its later reception.',completeCopy:'You began with the verse’s immediate language, noticed its structure, named an interpretive question, and saw how the phrase “when you lie down and when you rise up” enters Berakhot. This is the basis for reading Torah and later canon together. A second kind of Torah reading is ready: <a href="chumash-akeidah.html">follow one word through the Akeidah →</a>',nextUrl:'berakhot-arc.html',nextLabel:'See the verse inside Berakhot',steps:[
{short:'Enter the verse',mode:'VERSE ORIENTATION',title:'Name the address',ref:'Deuteronomy 6:4',hebrew:'שְׁמַע יִשְׂרָאֵל ה׳ אֱלֹהֵינוּ ה׳ אֶחָד',translation:'Hear, O Israel: the Lord is our God, the Lord is one.',prompt:'What is the first close-reading task?',answers:['Identify who is addressed and what claim the verse makes.','Find a later halakhic code immediately.','Treat the verse as a list of disconnected words.'],correct:0,skill:'tanakh-address-claim',competency:'sourceReasoning',feedback:'Good. Start with speaker, audience, and the claim before bringing later interpretations.'},
{short:'Find the command',mode:'VERSE ORIENTATION',title:'What is the person asked to do?',ref:'Deuteronomy 6:5',hebrew:'וְאָהַבְתָּ אֵת ה׳ אֱלֹהֶיךָ',translation:'You shall love the Lord your God.',prompt:'What kind of statement is this?',answers:['A command that names a relationship and orientation.','A historical report about a past event.','A Gemara objection.'],correct:0,skill:'tanakh-command',competency:'recognition',feedback:'Exactly. Name the form of the statement before asking how later readers understand it.'},
{short:'Notice repetition',mode:'LITERARY SHAPE',title:'A word appears across settings',ref:'Deuteronomy 6:7',hebrew:'וְדִבַּרְתָּ בָּם',translation:'You shall speak of them.',prompt:'What should a close reader ask next?',answers:['Where and when does the verse say this speaking should take place?','Which later commentator wins the argument?','Whether the verse has a legal ruling already settled.'],correct:0,skill:'tanakh-follow-language',competency:'sourceReasoning',feedback:'A repeated or extended instruction often carries its meaning through the details that follow.'},
{short:'Read the setting',mode:'CONTEXT',title:'Two times frame the instruction',ref:'Deuteronomy 6:7',hebrew:'בְּשָׁכְבְּךָ וּבְקוּמֶךָ',translation:'When you lie down and when you rise up.',prompt:'What does this phrase first contribute inside the verse?',answers:['It places the instruction in the rhythms of daily life.','It supplies a complete clock calculation.','It introduces a disagreement between sages.'],correct:0,skill:'tanakh-context-phrase',competency:'translation',feedback:'Right. First read the phrase in its verse before asking how later texts turn it into a legal question.'},
{short:'Ask an interpretive question',mode:'INTERPRETATION',title:'One phrase, more than one possible focus',ref:'Deuteronomy 6:7',hebrew:'בְּשָׁכְבְּךָ וּבְקוּמֶךָ',translation:'When you lie down and when you rise up.',prompt:'What is a responsible interpretive question?',answers:['Does the phrase describe ordinary life, particular times, or both—and what evidence guides the reading?','Which meaning feels nicest without needing evidence?','Why should we ignore the surrounding verse?'],correct:0,skill:'tanakh-interpretive-question',competency:'argument',feedback:'Good. Interpretation begins with a precise question grounded in the text.'},
{short:'Meet the Mishnah',mode:'RECEPTION',title:'A later text foregrounds one question',ref:'Mishnah Berakhot 1:1',hebrew:'מֵאֵימָתַי קוֹרִין אֶת שְׁמַע בְּעַרְבִין?',translation:'From when do we recite Shema in the evenings?',prompt:'How does the Mishnah receive the Torah passage?',answers:['It turns the daily-language of the verse into a practical timing question.','It ignores the verse completely.','It replaces Torah with an unrelated narrative.'],correct:0,skill:'tanakh-mishnah-reception',competency:'sourceReasoning',feedback:'Exactly. Canonical reception can highlight one dimension of a verse for a new kind of question.'},
{short:'Meet the Gemara',mode:'RECEPTION',title:'The Gemara asks why the Mishnah begins here',ref:'Berakhot 2a',hebrew:'תַּנָּא אַקְרָא קָאֵי',translation:'The Mishnah relies on a verse.',prompt:'What does the Gemara add to the Mishnah’s use of the verse?',answers:['It explains the textual reason behind the Mishnah’s ordering.','It abandons the verse for a new topic.','It gives a translation exercise only.'],correct:0,skill:'tanakh-gemara-reception',competency:'sourceReasoning',feedback:'You can now see Torah, Mishnah, and Gemara as a connected conversation.'},
{short:'Independent canon map',mode:'INDEPENDENT READ',title:'Trace the source forward',ref:'Deuteronomy 6:7 · Berakhot 2a',hebrew:'בְּשָׁכְבְּךָ וּבְקוּמֶךָ · מֵאֵימָתַי',translation:'When you lie down and when you rise up · from when?',independent:true,prompt:'What relationship should a learner recognize?',answers:['The Mishnah’s question and Gemara’s explanation are later readings of language in the Torah verse.','The phrases have no relationship.','The later texts make the Torah verse unnecessary.'],correct:0,skill:'tanakh-independent-reception',competency:'sourceReasoning',feedback:'This is canonical literacy: reading each layer clearly while tracing the line between them.'},
{short:'Type the meaning',mode:'PRODUCTION CHECK',title:'Recall, don’t just recognize',ref:'Deuteronomy 6:7',hebrew:'בְּשָׁכְבְּךָ וּבְקוּמֶךָ',translation:'When you lie down and when you rise up.',independent:true,typed:true,prompt:'Type the English meaning of this phrase.',acceptable:['when you lie down and when you rise up','when you lie down and rise up','lying down and rising up'],skill:'tanakh-typed-recall',competency:'translation',feedback:'Typing an answer from memory is a stronger test of durable mastery than recognizing it among choices.'}
]};
