window.SederCourse={stage:'gemara-reading-toolkit',completeTitle:'You have a working toolkit for entering a Gemara argument.',completeCopy:'You can now predict whether a line introduces a teaching, objection, distinction, proof, or conclusion. Use these signals as you enter longer Berakhot and tractate units. A related toolkit is ready next: <a href="gemara-middot.html">meet six of the Torah\'s own thirteen reasoning tools →</a>',nextUrl:'berakhot-unit-2.html',nextLabel:'Use the toolkit in Berakhot',steps:[
{short:'Connector: but',mode:'CONNECTOR',title:'A small word changes direction',ref:'Common Gemara connector',hebrew:'אֶלָּא',translation:'Rather / rather than.',prompt:'What should you expect when a discussion says ela?',answers:['A previous framing is being revised or replaced.','A verse is being quoted.','The sugya has ended.'],correct:0,skill:'connector-ela',competency:'translation',feedback:'Good. A connector can tell you that the argument is turning.'},
{short:'Cited teaching',mode:'BARAITA',title:'A teaching enters the sugya',ref:'Common Gemara signal',hebrew:'תַּנְיָא',translation:'It was taught.',prompt:'What function does this signal usually have?',answers:['It introduces a cited teaching that can support, clarify, or challenge.','It announces a final decision.','It gives a personal reflection.'],correct:0,skill:'baraita-signal',competency:'sourceReasoning',feedback:'Exactly. Ask what the cited teaching contributes to the current question.'},
{short:'Objection',mode:'CHALLENGE',title:'An answer is tested',ref:'Common Gemara signal',hebrew:'מֵיתִיבֵי',translation:'They raise an objection.',prompt:'What is happening to the preceding claim?',answers:['A source is being brought to put pressure on it.','It is being accepted as final.','It is being translated into Hebrew.'],correct:0,skill:'objection-signal',competency:'argument',feedback:'Right. An objection creates a problem the sugya must address.'},
{short:'Distinction',mode:'DISTINCTION',title:'A difference may resolve a problem',ref:'Common Gemara signal',hebrew:'לָא קַשְׁיָא',translation:'It is not difficult.',prompt:'What kind of move might follow this phrase?',answers:['A distinction that shows the sources apply in different situations.','A decision to ignore both sources.','A new unrelated Mishnah.'],correct:0,skill:'distinction-signal',competency:'argument',feedback:'Good. The Gemara can resolve a conflict by showing that the cases are not actually identical.'},
{short:'Clarification',mode:'CLARIFICATION',title:'Ask what the source teaches',ref:'Common Gemara signal',hebrew:'מַאי קָא מַשְׁמַע לָן?',translation:'What does this teach us?',prompt:'What does this question ask the reader to find?',answers:['The added insight or legal/conceptual consequence of a statement.','A new translation for every word.','A reason to leave the source.'],correct:0,skill:'clarification-signal',competency:'argument',feedback:'Exactly. A statement may be true but still need its point made explicit.'},
{short:'Proof',mode:'PROOF',title:'Invite evidence into the argument',ref:'Common Gemara signal',hebrew:'תָּא שְׁמַע',translation:'Come and hear.',prompt:'What should you expect next?',answers:['A source offered as evidence for the issue under discussion.','A personal opinion with no source.','The final end of the tractate.'],correct:0,skill:'proof-invitation',competency:'sourceReasoning',feedback:'Right. Read the next source by asking whether it truly answers the question.'},
{short:'Tentative answer',mode:'PROPOSAL',title:'An inference is offered',ref:'Common Gemara signal',hebrew:'לֵימָא',translation:'Let us say.',prompt:'How should a learner treat this phrase?',answers:['As a proposed inference that may still be tested or rejected.','As an unquestionable final ruling.','As an unrelated quotation.'],correct:0,skill:'tentative-inference',competency:'argument',feedback:'Good. Gemara often presents a possible reading before testing it.'},
{short:'Conclusion',mode:'CONCLUSION',title:'An inference is drawn',ref:'Common Gemara signal',hebrew:'שְׁמַע מִינָּהּ',translation:'Learn from it.',prompt:'What is the discussion doing here?',answers:['Drawing a conclusion from the sources just considered.','Beginning an objection.','Returning to a page number.'],correct:0,skill:'conclusion-signal',competency:'argument',feedback:'Exactly. The phrase marks a conclusion, but a careful reader still asks how strong the support is.'},
{short:'Unresolved difficulty',mode:'UNRESOLVED',title:'Not every question disappears',ref:'Common Gemara signal',hebrew:'קַשְׁיָא',translation:'A difficulty remains.',prompt:'What is the responsible response to this signal?',answers:['Keep the difficulty in view rather than pretending the argument is fully resolved.','Treat the issue as settled.','Skip the source entirely.'],correct:0,skill:'unresolved-signal',competency:'argument',feedback:'Maturity includes recognizing where a text leaves pressure or ambiguity.'},
{short:'Pressing the premise',mode:'CHALLENGE',title:'Accept it, then push it further',ref:'Common Gemara signal',hebrew:'אִי הָכִי',translation:'If so.',prompt:'What kind of move does this phrase usually introduce?',answers:['A challenge that accepts the prior claim for the sake of argument, then shows an uncomfortable consequence it seems to produce.','A flat rejection of the prior claim with no reasoning given.','A citation from the Torah with no connection to the discussion.'],correct:0,skill:'ee-hachi-signal',competency:'argument',feedback:'Right. “If so” grants the premise first — the pressure comes from where that premise leads.'},
{short:'A contradicting teaching',mode:'BARAITA',title:'A second source complicates the first',ref:'Common Gemara signal',hebrew:'וְהָתַנְיָא',translation:'But it was taught.',prompt:'What does this signal usually bring into the discussion?',answers:['A second cited teaching that appears to conflict with the position just stated.','A confirmation that no further sources are needed.','An unrelated story with no legal content.'],correct:0,skill:'vehatanya-signal',competency:'sourceReasoning',feedback:'Exactly. This phrase sets up real tension — expect the sugya to either distinguish the two teachings or revise one of them.'},
{short:'A corrected answer',mode:'PROPOSAL',title:'The first answer is replaced',ref:'Common Gemara signal',hebrew:'אֶלָּא אָמַר',translation:'Rather, he said.',prompt:'What has usually just happened when this phrase appears?',answers:['A previously offered answer has been found wanting, and a new one is being proposed in its place.','The discussion is ending with no further analysis.','A new, unrelated Mishnah is beginning.'],correct:0,skill:'ela-amar-signal',competency:'argument',feedback:'Good. This is the phrase that marks a sugya actually revising its own best answer — a sign of real argument, not decoration.'},
{short:'Independent map',mode:'INDEPENDENT READ',title:'Name the moves without a guide',ref:'Short sugya template',hebrew:'תַּנְיָא · מֵיתִיבֵי · לָא קַשְׁיָא',translation:'It was taught · they raise an objection · it is not difficult.',independent:true,prompt:'What is the most likely motion of this passage?',answers:['A teaching is cited, challenged by a source, then reconciled through a distinction.','A final ruling is repeated three times.','Three unrelated stories are introduced.'],correct:0,skill:'independent-sugya-toolkit',competency:'argument',feedback:'You can now read the architecture of an unfamiliar argument before filling in every detail.'},
{short:'Type the meaning',mode:'PRODUCTION CHECK',title:'Recall, don’t just recognize',ref:'Common Gemara connector',hebrew:'אֶלָּא',translation:'Rather.',independent:true,typed:true,prompt:'This one word overturns a failed answer and introduces its replacement. Type its English meaning.',acceptable:['rather','but rather','rather than','instead'],skill:'gemara-toolkit-typed-recall',competency:'translation',feedback:'Typing an answer from memory is a stronger test of durable mastery than recognizing it among choices.'}
]};
