window.SederCourse={stage:'gemara-middot-toolkit',completeTitle:'You can now recognize the Torah\'s own reasoning tools at work.',completeCopy:'You named six of the thirteen middot, saw one at work directly in the Torah\'s own text, and connected the idea of a "shared aspect" to a Mishnah you already know. These tools explain why a Gemara treats certain word choices and verse pairings as legally significant. One more foundation is ready: <a href="daf-literacy.html">learn to navigate a printed page of Talmud →</a>',nextUrl:'berakhot-unit-2.html',nextLabel:'Continue into Berakhot',steps:[
{short:'Name the baraita',mode:'CONCEPT',title:'A named list of reasoning tools',ref:'Sifra, Baraita d\'Rabbi Yishmael',hebrew:'רַבִּי יִשְׁמָעֵאל אוֹמֵר בִּשְׁלֹשׁ עֶשְׂרֵה מִדּוֹת הַתּוֹרָה נִדְרֶשֶׁת',translation:'Rabbi Yishmael says: the Torah is expounded through thirteen principles.',prompt:'What kind of text is this baraita?',answers:['A named list of reasoning tools through which the Torah\'s laws are derived, not a story or a ruling itself.','A single ruling about one specific case.','A historical account of Rabbi Yishmael\'s life.'],correct:0,skill:'middot-orient',competency:'recognition',feedback:'Right. This baraita is recited daily precisely because it names the toolkit, not because it settles any one law.'},
{short:'Light and heavy',mode:'CONCEPT',title:'Kal vachomer: an a fortiori step',ref:'Middah 1',hebrew:'קַל וָחֹמֶר',translation:'Light and heavy [an a fortiori inference].',prompt:'What does this reasoning tool let a reader do?',answers:['Infer that if a lenient case carries a given rule, a more severe case must carry at least the same rule (or the reverse, for a strict case implying a lenient one).','Prove that two completely unrelated laws are identical.','Replace the Torah\'s text with a new rule of the reader\'s choosing.'],correct:0,skill:'middot-kal-vachomer',competency:'argument',feedback:'Good. “Light and heavy” names the direction of the inference — from the more lenient case to the more severe, or vice versa.'},
{short:'See it in the Torah',mode:'PROOF',title:'God uses this exact inference',ref:'Numbers 12:14',hebrew:'וְאָבִיהָ יָרֹק יָרַק בְּפָנֶיהָ הֲלֹא תִכָּלֵם שִׁבְעַת יָמִים',translation:'If her father had but spit in her face, should she not bear her shame seven days?',prompt:'God answers Moses about Miriam\'s punishment with this line. What is the a fortiori step here?',answers:['If an ordinary father\'s rebuke earns seven days of shame, a far greater rebuke from God should reasonably require at least that much.','The verse proves fathers should never rebuke their children.','The verse has no connection to any legal reasoning pattern.'],correct:0,skill:'middot-kal-vachomer-source',competency:'sourceReasoning',feedback:'Right. This is a kal vachomer spoken by God directly in the text — the tool is not only a rabbinic invention layered onto the Torah.'},
{short:'An equal category',mode:'CONCEPT',title:'Gezeirah shavah: a shared word links two verses',ref:'Middah 2',hebrew:'גְּזֵרָה שָׁוָה',translation:'An equal category [verbal analogy].',prompt:'What does this tool do?',answers:['When the same distinctive word or phrase appears in two different Torah passages, a law explained in one context can be applied to the other.','It proves that any two verses using ordinary words must mean the same thing.','It cancels a law that happens to appear more than once in the Torah.'],correct:0,skill:'middot-gezeirah-shavah',competency:'argument',feedback:'Good. The shared word has to be distinctive, not a common word — otherwise nearly any two verses could be linked.'},
{short:'A paradigm case',mode:'CONCEPT',title:'Binyan av: one case models many',ref:'Middah 3',hebrew:'בִּנְיָן אָב',translation:'A building / paradigm case.',prompt:'What does this tool do?',answers:['It takes a rule clearly stated for one case and extends it to other cases that share the same underlying reason.','It requires every law to be restated in full for every case it applies to.','It only functions when a law appears exactly in four separate verses.'],correct:0,skill:'middot-binyan-av',competency:'argument',feedback:'Right. A binyan av asks what general principle is really behind a specific case, then extends that principle to similar settings.'},
{short:'General, then specific',mode:'COMPARISON',title:'Klal u\'frat: the specific narrows the general',ref:'Middah 4',hebrew:'כְּלָל וּפְרָט',translation:'General, then specific.',prompt:'When a broad statement is immediately followed by a narrower example, what does this tool conclude?',answers:['The law is limited to the scope of the specific example, not the full breadth of the general statement.','The specific example is irrelevant, and the general statement always wins.','The general statement and the specific example must describe two unrelated laws.'],correct:0,skill:'middot-klal-ufrat',competency:'argument',feedback:'Good. The order matters: general-then-specific narrows the law down to the example given.'},
{short:'Specific, then general',mode:'COMPARISON',title:'Prat u\'chlal: the general widens the specific',ref:'Middah 5',hebrew:'פְּרָט וּכְלָל',translation:'Specific, then general.',prompt:'When specific examples are followed by a broader general term, what does this tool conclude?',answers:['The law extends to the full general category, not only to the specific examples first listed.','The order makes no difference to the outcome.','Only the specific examples are ever included, and the closing general term is ignored.'],correct:0,skill:'middot-prat-uchlal',competency:'argument',feedback:'Exactly. Reversing the order of general and specific reverses the conclusion — this is why word order is never incidental in a Mishnah.'},
{short:'General, specific, general',mode:'COMPARISON',title:'A third pattern, a middle conclusion',ref:'Middah 6',hebrew:'כְּלָל וּפְרָט וּכְלָל',translation:'General, specific, general.',prompt:'What does this three-part pattern conclude, compared to the two simpler patterns before it?',answers:['The law extends to anything that shares the essential character of the specific example — wider than “specific only,” narrower than “fully general.”','It always produces the exact same result as klal u\'frat alone.','It cancels both the opening general statement and the specific example.'],correct:0,skill:'middot-klal-ufrat-uchlal',competency:'argument',feedback:'Right. This pattern is a genuine middle path, not simply one of the first two patterns repeated.'},
{short:'A familiar phrase, reused',mode:'TRANSFER',title:'“What they share,” inside a Mishnah',ref:'Mishnah Bava Kamma 1:1',hebrew:'הַצַּד הַשָּׁוֶה שֶׁבָּהֶן',translation:'What they share [literally: the equal side among them].',prompt:'You already read this exact phrase in Bava Kamma\'s opening Mishnah, naming what its four categories of damage share. What does this suggest about binyan av\'s idea of a “shared aspect”?',answers:['Identifying what several cases share in common is a reasoning move that shows up both as a formal hermeneutical tool and inside a Mishnah\'s own internal logic.','The Mishnah and the middot are always using the exact identical technical procedure with no distinction.','Shared language between two sources always means one source is quoting the other directly.'],correct:0,skill:'middot-transfer',competency:'sourceReasoning',feedback:'Good instinct, and a careful one: the underlying move — naming a shared aspect — recurs across contexts, even where the technical term is not identical.'},
{short:'Keep the boundary',mode:'RESPONSIBLE LEARNING',title:'Recognizing a tool is not wielding it',ref:'Jewish Learning Academy learning boundary',hebrew:'לִלְמוֹד · לְהָבִין · לִשְׁאוֹל',translation:'To learn · to understand · to ask.',prompt:'These tools were used by the Sages to derive real halakha. What is Jewish Learning Academy\'s appropriate role in teaching them?',answers:['Help learners recognize these reasoning patterns when they appear in a text, while recognizing that applying them to derive new halakha requires extensive training and rabbinic authority, not a beginner\'s course.','Encourage learners to derive their own new halakhic rulings using these tools.','Avoid teaching these tools at all, since they are only for expert use.'],correct:0,skill:'middot-non-psak-boundary',competency:'sourceReasoning',feedback:'Right. Naming a tool is not the same as being qualified to wield it — real halakhic derivation demands training this course does not provide.'},
{short:'Independent read',mode:'INDEPENDENT READ',title:'Spot the pattern on your own',ref:'Middot checkpoint',hebrew:'קַל וָחֹמֶר · גְּזֵרָה שָׁוָה · בִּנְיָן אָב · כְּלָל וּפְרָט',translation:'A fortiori · verbal analogy · paradigm case · general and specific.',independent:true,prompt:'What is the first independent-reading move when you notice one of these patterns in a text?',answers:['Name which specific tool is at work, then ask exactly what it does and does not license you to conclude.','Assume all thirteen tools always produce the same kind of conclusion.','Skip the reasoning and jump straight to the stated ruling.'],correct:0,skill:'middot-independent-map',competency:'sourceReasoning',feedback:'You can now recognize several of the Torah\'s own reasoning tools instead of treating every inference as unexplained.'},
{short:'Type the meaning',mode:'PRODUCTION CHECK',title:'Recall, don\'t just recognize',ref:'Sifra, Baraita d\'Rabbi Yishmael',hebrew:'קַל וָחֹמֶר',translation:'Light and heavy.',independent:true,typed:true,prompt:'Type the English name or meaning of this reasoning tool in a few words.',acceptable:['a fortiori','light and heavy','from light to heavy','from minor to major','from lenient to severe'],skill:'middot-typed-recall',competency:'translation',feedback:'Typing an answer from memory is a stronger test of durable mastery than recognizing it among choices.'}
]};
// Two high-risk inference questions now offer substantive near-misses instead of a length cue.
const middotSteps=window.SederCourse.steps;
middotSteps[1].answers=['Infer that if a lenient case carries a given rule, a more severe case must carry at least the same rule (or the reverse, for a strict case implying a lenient one).','Treat any two laws as identical whenever one of them seems more severe than the other.','Create a new legal rule without first tracing the relation between the two stated cases.'];
middotSteps[2].answers=['If an ordinary father’s rebuke earns seven days of shame, a far greater rebuke from God should reasonably require at least that much.','The verse compares two punishments but refuses to draw any inference from the greater case.','The verse offers a family image without making a claim about the relation between cases.'];
middotSteps[2].answers[2]='The verse offers a family image without making a claim about the relation between the two cases it names.';
middotSteps[4].answers=['It takes a rule clearly stated for one case and extends it to other cases that share the same underlying reason.','It requires every law to be restated in full for each later case before the rule can apply.','It only functions when a law appears exactly in four separate verses with identical wording.'];

// [rebalance] distractor lengths evened so the correct answer is not the longest option
window.SederCourse.steps[0].answers[1]="A single fixed ruling that settles only one specific case and derives nothing further at all from it.";
window.SederCourse.steps[0].answers[2]="A historical account of the life and the teachings of Rabbi Yishmael and his many rabbinic colleagues.";
window.SederCourse.steps[1].answers[1]="Treat any two laws as fully identical whenever one of them merely seems more severe than the other, ignoring the reasoning that links them.";
window.SederCourse.steps[1].answers[2]="Create an entirely new legal rule of one's own without first tracing the relation between the two cases the Torah actually states.";
window.SederCourse.steps[3].answers[1]="It proves that any two verses which happen to share even ordinary, common words must therefore carry one and the same meaning.";
window.SederCourse.steps[3].answers[2]="It cancels or overrides any law that simply happens to appear more than once across different passages of the Torah.";
window.SederCourse.steps[6].answers[1]="The order of the general and the specific terms makes no real difference to the conclusion the reader finally reaches.";
window.SederCourse.steps[7].answers[1]="It always produces the exact same result as the simpler klal u'frat pattern does, adding nothing genuinely new to it.";
window.SederCourse.steps[7].answers[2]="It cancels both the opening general statement and the specific example, leaving behind no operative rule at all.";
window.SederCourse.steps[8].answers[1]="The Mishnah and the middot must always be using the exact identical technical procedure, with no distinction between them at all.";
window.SederCourse.steps[8].answers[2]="Shared language between two different sources always means that the one source is directly quoting the other word for word.";
window.SederCourse.steps[9].answers[1]="Encourage learners to go ahead and derive their own new halakhic rulings directly from these tools, treating recognition as full mastery.";
window.SederCourse.steps[9].answers[2]="Avoid teaching these reasoning tools at all, on the grounds that they belong strictly to expert use and have no place in a beginner's course.";
window.SederCourse.steps[10].answers[1]="Assume that all thirteen of the reasoning tools always produce the very same kind of conclusion as one another.";
window.SederCourse.steps[10].answers[2]="Skip over the reasoning entirely and jump straight ahead to whatever ruling the text happens to state at the end.";
