window.SederCourse={stage:'gittin-tractate-arc',completeTitle:'You can now read Gittin through document, agency, and delivery.',completeCopy:'You traced how a get becomes a legal document through writing, representation, intent, and delivery while keeping historical study distinct from present-day legal advice. Continue into the Gittin source workspace.',nextUrl:'lab.html?tractate=gittin',nextLabel:'Open the Gittin source workspace',steps:[
{short:'Name the document',mode:'DOCUMENT ORIENTATION',title:'A get is a defined legal instrument',ref:'Mishnah Gittin 1:1',hebrew:'A get from overseas',translation:'A divorce document brought from overseas.',prompt:'What is the opening Mishnah asking you to notice?',answers:['The document has a defined legal identity and a delivery problem that must be solved.','Any private note automatically dissolves a marriage.','The messenger can replace the document entirely.'],correct:0,skill:'gittin-document-identity',competency:'recognition',feedback:'Right. Gittin begins by distinguishing a formal instrument from an ordinary message.'},
{short:'Locate the agency',mode:'REPRESENTATION',title:'Who can speak for the sender?',ref:'Mishnah Gittin 1:1',hebrew:'The agent says: Before me it was written and before me it was signed',translation:'The agent testifies about the writing and signatures.',prompt:'Why does the agent matter in this opening case?',answers:['The agent supplies a defined procedural testimony that connects the document to its origin.','Any traveler may change the document while carrying it.','The recipient must personally witness the original writing.'],correct:0,skill:'gittin-agency',competency:'sourceReasoning',feedback:'Exactly. Agency is structured: the messenger has a role and a limited statement to make.'},
{short:'Check validity',mode:'VALIDITY CONDITIONS',title:'Writing and signatures do legal work',ref:'Gittin 21b',hebrew:'And he shall write for her a document of severance',translation:'He shall write for her a document of severance.',prompt:'What kind of question should a reader ask about the document?',answers:['Which writing, signature, and authorization conditions make the document valid for its purpose.','Whether attractive handwriting makes every document valid.','Whether the document can be replaced by an oral promise.'],correct:0,skill:'gittin-validity-conditions',competency:'argument',feedback:'Good. Validity is a source-defined set of conditions, not a matter of appearance.'},
{short:'Trace delivery',mode:'DELIVERY MAP',title:'The document must reach its legal destination',ref:'Mishnah Gittin 2:5',hebrew:'The hand of the woman',translation:'The document enters her possession.',prompt:'What changes when delivery occurs?',answers:['The document moves from the sender’s control into the recipient’s legally recognized possession.','The messenger remains the permanent owner of the document.','Delivery is irrelevant once the document has been written.'],correct:0,skill:'gittin-delivery',competency:'sourceReasoning',feedback:'Yes. Delivery is a legal transition, not merely a change of physical location.'},
{short:'Separate intent',mode:'INTENT',title:'Action and intention must be read together',ref:'Gittin 2a',hebrew:'For her sake',translation:'For her purpose / for her sake.',prompt:'What does an intent requirement prevent?',answers:['It prevents a document or act from being treated as interchangeable when its legally relevant purpose is missing.','It makes the recipient’s intention irrelevant.','It turns every mistaken act into a valid divorce.'],correct:0,skill:'gittin-intent',competency:'argument',feedback:'Right. Gittin trains you to ask what purpose the act was performed for.'},
{short:'Limit representation',mode:'AGENCY LIMITS',title:'An agent is not the principal',ref:'Gittin 64b',hebrew:'A person’s agent is like the person himself',translation:'An agent can act in the person’s place within the assigned mandate.',prompt:'What is the careful boundary around agency?',answers:['An agent can transmit or perform an assigned act, but the source still defines the mandate and its limits.','An agent can invent new terms for the principal.','Any bystander becomes an agent by observing the transaction.'],correct:0,skill:'gittin-agency-limits',competency:'sourceReasoning',feedback:'Exactly. Representation extends action without erasing the boundaries of authorization.'},
{short:'Keep the boundary',mode:'HISTORICAL STUDY',title:'Historical law needs present-day care',ref:'Seder learning boundary',hebrew:'To learn · to understand · not to issue a ruling',translation:'Study to understand; do not treat this lesson as a personal ruling.',prompt:'What is Seder’s responsible stance?',answers:['Study document and agency categories historically while directing personal legal concerns to qualified authorities.','Apply an ancient divorce procedure directly to a contemporary case.','Avoid the tractate because its subject is difficult.'],correct:0,skill:'gittin-historical-boundary',competency:'sourceReasoning',feedback:'Serious study can be precise about the past without pretending to replace present-day guidance.'},
{short:'Map a case',mode:'INDEPENDENT READ',title:'Read an unfamiliar Gittin passage',ref:'Gittin transfer checkpoint',hebrew:'Document · agent · intent · delivery · recipient',translation:'Document · agency · intent · delivery · recipient.',independent:true,prompt:'What is the best first map for an unfamiliar passage?',answers:['Identify the instrument, authorized actor, purpose, delivery act, recipient, and remaining validity question.','Begin with a modern verdict before locating the source’s categories.','Treat writing, agency, and delivery as one undifferentiated act.'],correct:0,skill:'gittin-independent-map',competency:'sourceReasoning',feedback:'You can now read Gittin through document identity, agency, intent, validity, and delivery.'}
]};
const gittinSteps=window.SederCourse.steps;
gittinSteps.push({short:'Explain the transfer',mode:'SOURCE CHECK',title:'Produce the reading move',ref:'Gittin transfer checkpoint',hebrew:'כתב Â· שליח Â· לשמה Â· נתינה',translation:'Writing Â· agent Â· for her sake Â· delivery.',independent:true,prompt:'Which explanation best transfers the Gittin reading method to a new document case?',answers:['Name the document, test its purpose and authorization, then trace how delivery changes its legal status.','Start with the outcome that seems fairest, then fit the document and messenger into that conclusion afterward.','Treat a valid writing as sufficient by itself, without asking who authorized delivery or what purpose governed it.'],correct:0,skill:'gittin-source-transfer-check',competency:'sourceReasoning',feedback:'This source check makes you produce the sequence of document identity, authorization, purpose, and delivery rather than merely recognize terms.'});
const gittinNearMisses=[
['It treats the document as a private message whose meaning is supplied by the traveler, rather than as a formal instrument with defined delivery conditions.','It treats the document as complete once written, so the recipient’s possession and the messenger’s mandate no longer matter to validity.'],
['It treats the messenger as an unrestricted substitute who may alter the document, rather than as an agent whose testimony and mandate connect it to the sender.','It treats agency as unnecessary because only the recipient’s encounter with the paper matters, leaving the origin of writing and signatures unexamined.'],
['It treats valid writing as a matter of visual appearance or handwriting quality, rather than asking which source-defined authorization and signature conditions serve the document’s purpose.','It treats an oral promise as interchangeable with the written instrument, ignoring the Mishnah’s insistence that the document itself carry the legal act.'],
['It treats delivery as mere travel of paper while leaving control and possession unchanged, rather than identifying the moment the recipient acquires the document in the legally relevant way.','It treats writing as the entire act, so reaching the recipient adds no distinct legal transition and no new question about control.'],
['It treats intention as whatever the recipient later imagines, rather than testing whether the act was performed for the legally relevant purpose named by the source.','It treats every mistake of purpose as harmless because the physical document exists, collapsing the source’s distinction between an act and its intent.'],
['It treats an agent’s authority as unlimited, allowing the messenger to add terms or redefine the assignment rather than transmitting the principal’s specified mandate.','It treats mere observation as enough to create agency, replacing an assigned role with the presence of any bystander at the transaction.'],
['It treats the historical categories as a ready-made contemporary divorce procedure, rather than as a source to study while directing personal cases to qualified authorities.','It treats the subject’s difficulty as a reason to avoid study altogether, rather than preserving both serious textual learning and a boundary against personal rulings.'],
['It begins by deciding a modern outcome, then forces the unfamiliar passage into that verdict instead of mapping the instrument, actor, purpose, delivery, and recipient first.','It merges writing, agency, intent, and delivery into one event, so a reader cannot see which condition the passage is actually testing.']];
gittinNearMisses.forEach((pair,i)=>{gittinSteps[i].answers[1]=pair[0];gittinSteps[i].answers[2]=pair[1];});
