window.SederCourse={stage:'language-grammar-mastery',completeTitle:'You can now use grammar as a reading tool.',completeCopy:'You learned to identify action, subject, condition, connector, question form, and source signal inside short lines. Keep using the tools on a live argument map.',nextUrl:'source-map.html',nextLabel:'Map a source directly',steps:[
{short:'Action word',mode:'GRAMMAR TOOL',title:'Find what happens',ref:'Mishnah Berakhot 1:1',hebrew:'קוֹרִין אֶת שְׁמַע',translation:'They recite Shema.',prompt:'What is the action word doing?',answers:['It names what is being done.','It names who performs the action.','It marks where the action happens.'],correct:0,skill:'grammar-action',competency:'translation',feedback:'Start with action: it gives the sentence a center. Who and where are separate slots the sentence may fill elsewhere.'},
{short:'Condition',mode:'GRAMMAR TOOL',title:'Find when it applies',ref:'Mishnah Berakhot 1:1',hebrew:'בְּעַרְבִין',translation:'In the evenings.',prompt:'What work does this phrase do?',answers:['It sets the time or setting of the action.','It states the ruling for the case.','It names the actor the rule obligates.'],correct:0,skill:'grammar-condition',competency:'translation',feedback:'Conditions narrow the case and make a rule readable — this slot answers “when,” not “what follows” or “who.”'},
{short:'Question form',mode:'GRAMMAR TOOL',title:'Recognize a question shape',ref:'Mishnah Berakhot 1:1',hebrew:'מֵאֵימָתַי קוֹרִין',translation:'From when do they recite?',prompt:'What structure do you see?',answers:['A question signal followed by an action.','A condition followed by the ruling it produces.','A source signal followed by the verse it introduces.'],correct:0,skill:'grammar-question-form',competency:'translation',feedback:'You can now predict a sentence’s job from its first signal — this opens as a question, not as a case-and-ruling or a citation.'},
{short:'Connector',mode:'GRAMMAR TOOL',title:'A word can change direction',ref:'Common Gemara connector',hebrew:'אֶלָּא',translation:'Rather / rather than.',prompt:'What should this connector make you look for?',answers:['A revision or replacement of the previous framing.','A supporting proof for the previous framing.','A restatement of the framing in plainer words.'],correct:0,skill:'grammar-connector',competency:'argument',feedback:'Connectors are the road signs of a sugya — ela turns the argument; support and restatement travel under different words.'},
{short:'Source marker',mode:'GRAMMAR TOOL',title:'A form brings a verse',ref:'Common Gemara signal',hebrew:'דִּכְתִיב',translation:'As it is written.',prompt:'What is this form signaling?',answers:['A scriptural source is entering the argument.','A rabbinic teaching is entering the argument.','A practical sign is being offered as evidence.'],correct:0,skill:'grammar-source-marker',competency:'sourceReasoning',feedback:'Grammar and source reasoning meet here: dikhtiv announces Scripture. Rabbinic teachings arrive with tanya, and practical markers with siman.'},
{short:'Relationship word',mode:'GRAMMAR TOOL',title:'Notice a link between ideas',ref:'Common Gemara language',hebrew:'מִשּׁוּם',translation:'Because of / on account of.',prompt:'What question should follow this word?',answers:['What reason is being given, and what claim does it support?','What case is being introduced, and what ruling follows it?','What source is being cited, and which sage transmitted it?'],correct:0,skill:'grammar-reason-link',competency:'argument',feedback:'A reason word asks you to connect a claim to its support — a different task from mapping cases or tracking attributions.'},
{short:'Transfer',mode:'GRAMMAR TOOL',title:'Use the same tool in a new tractate',ref:'Mishnah Sukkah 1:1',hebrew:'סֻכָּה שֶׁהִיא גְבוֹהָה … פְּסוּלָה',translation:'A sukkah that is high … is invalid.',prompt:'What is the sentence skeleton?',answers:['Case or condition followed by a ruling.','Question followed by a verse-based answer.','Claim followed by an objection against it.'],correct:0,skill:'grammar-transfer',competency:'sourceReasoning',feedback:'You transferred a grammar map from Berakhot to Sukkah — the Mishnah states a case and rules on it; questions and objections have other shapes.'},
{short:'Independent grammar',mode:'INDEPENDENT READ',title:'Read form before full translation',ref:'Grammar checkpoint',hebrew:'מַאי טַעְמָא · דִּכְתִיב',translation:'What is the reason? · as it is written.',independent:true,prompt:'What map should you expect?',answers:['A reason-question followed by a scriptural source.','A timing question followed by a practical sign.','An objection followed by a distinction between cases.'],correct:0,skill:'grammar-independent',competency:'sourceReasoning',feedback:'Grammar has become a way to predict the argument’s motion — mai taama asks why, and dikhtiv answers from Scripture.'},
{short:'Type the meaning',mode:'PRODUCTION CHECK',title:'Recall, don’t just recognize',ref:'Mishnah Berakhot 1:1',hebrew:'בְּעַרְבִין',translation:'In the evenings.',independent:true,typed:true,prompt:'Type the English meaning of this word.',acceptable:['in the evenings','in the evening','at evening','evenings'],skill:'grammar-typed-recall',competency:'translation',feedback:'Typing an answer from memory is a stronger test of durable mastery than recognizing it among choices.'}
]};
