window.SederCourse={stage:'language-grammar-mastery',completeTitle:'You can now use grammar as a reading tool.',completeCopy:'You learned to identify action, subject, condition, connector, question form, and source signal inside short lines. Keep using the tools on a live argument map.',nextUrl:'source-map.html',nextLabel:'Map a source directly',steps:[
{short:'Action word',mode:'GRAMMAR TOOL',title:'Find what happens',ref:'Mishnah Berakhot 1:1',hebrew:'קוֹרִין אֶת שְׁמַע',translation:'They recite Shema.',prompt:'What is the action word doing?',answers:['It names what is being done.','It names a place.','It introduces a proof.'],correct:0,skill:'grammar-action',competency:'translation',feedback:'Start with action: it gives the sentence a center.'},
{short:'Condition',mode:'GRAMMAR TOOL',title:'Find when it applies',ref:'Mishnah Berakhot 1:1',hebrew:'בְּעַרְבִין',translation:'In the evenings.',prompt:'What work does this phrase do?',answers:['It sets the time or setting of the action.','It gives a conclusion.','It introduces an objection.'],correct:0,skill:'grammar-condition',competency:'translation',feedback:'Conditions narrow the case and make a rule readable.'},
{short:'Question form',mode:'GRAMMAR TOOL',title:'Recognize a question shape',ref:'Mishnah Berakhot 1:1',hebrew:'מֵאֵימָתַי קוֹרִין',translation:'From when do they recite?',prompt:'What structure do you see?',answers:['A question signal followed by an action.','A proof followed by a conclusion.','A cited teaching followed by an objection.'],correct:0,skill:'grammar-question-form',competency:'translation',feedback:'You can now predict a sentence’s job from its first signal.'},
{short:'Connector',mode:'GRAMMAR TOOL',title:'A word can change direction',ref:'Common Gemara connector',hebrew:'אֶלָּא',translation:'Rather / rather than.',prompt:'What should this connector make you look for?',answers:['A revision or replacement of the previous framing.','A final source citation.','A person’s name.'],correct:0,skill:'grammar-connector',competency:'argument',feedback:'Connectors are the road signs of a sugya.'},
{short:'Source marker',mode:'GRAMMAR TOOL',title:'A form brings a verse',ref:'Common Gemara signal',hebrew:'דִּכְתִיב',translation:'As it is written.',prompt:'What is this form signaling?',answers:['A scriptural source is entering the argument.','A disagreement is over.','A condition is being set.'],correct:0,skill:'grammar-source-marker',competency:'sourceReasoning',feedback:'Grammar and source reasoning meet here: the word tells you what kind of text arrives next.'},
{short:'Relationship word',mode:'GRAMMAR TOOL',title:'Notice a link between ideas',ref:'Common Gemara language',hebrew:'מִשּׁוּם',translation:'Because of / on account of.',prompt:'What question should follow this word?',answers:['What reason is being given, and what claim does it support?','Which page is next?','Who is being named?'],correct:0,skill:'grammar-reason-link',competency:'argument',feedback:'A reason word asks you to connect a claim to its support.'},
{short:'Transfer',mode:'GRAMMAR TOOL',title:'Use the same tool in a new tractate',ref:'Mishnah Sukkah 1:1',hebrew:'סֻכָּה שֶׁהִיא גְבוֹהָה … פְּסוּלָה',translation:'A sukkah that is high … is invalid.',prompt:'What is the sentence skeleton?',answers:['Case or condition followed by a ruling.','Question followed by a proof.','Objection followed by a source.'],correct:0,skill:'grammar-transfer',competency:'sourceReasoning',feedback:'You transferred a grammar map from Berakhot to Sukkah.'},
{short:'Independent grammar',mode:'INDEPENDENT READ',title:'Read form before full translation',ref:'Grammar checkpoint',hebrew:'מַאי טַעְמָא · דִּכְתִיב',translation:'What is the reason? · as it is written.',independent:true,prompt:'What map should you expect?',answers:['A reason-question followed by a scriptural source.','A final ruling with no argument.','A new narrative unrelated to the question.'],correct:0,skill:'grammar-independent',competency:'sourceReasoning',feedback:'Grammar has become a way to predict the argument’s motion.'}
]};
