window.SederCourse={stage:'horayot-tractate-arc',completeTitle:'You can now read an erroneous ruling through authority, reliance, and repair.',completeCopy:'You mapped the court\'s error, the community\'s reliance, the responsibility that follows, and the limits of historical precedent. Continue into the Horayot source workspace.',nextUrl:'lab.html?tractate=horayot',nextLabel:'Open the Horayot source workspace',steps:[
{short:'Locate the error',mode:'CASE ORIENTATION',title:'A court can rule in error',ref:'Mishnah Horayot 1:1',hebrew:'horaat bet din be-shogeg',translation:'An erroneous ruling of the court.',prompt:'What should a reader notice first?',answers:['The source distinguishes an institutional ruling from an individual mistake.','The text says every disagreement is automatically a court error.','The ruling has no legal consequences because it was unintentional.'],correct:0,skill:'horayot-court-error',competency:'recognition',feedback:'Right. Horayot begins by asking what happens when an authorized court reaches a mistaken ruling.'},
{short:'Name authority',mode:'AUTHORITY MAP',title:'Who issued the ruling?',ref:'Mishnah Horayot 1:1',hebrew:'bet din ha-gadol',translation:'The high court.',prompt:'Why identify the court before judging the outcome?',answers:['Authority and jurisdiction help determine whether reliance and atonement rules apply.','Any speaker has exactly the same institutional status.','Authority is irrelevant once a mistake is discovered.'],correct:0,skill:'horayot-authority',competency:'sourceReasoning',feedback:'Exactly. The tractate makes authority a condition of the legal analysis.'},
{short:'Trace reliance',mode:'COMMUNAL EFFECT',title:'A community follows the ruling',ref:'Mishnah Horayot 1:1',hebrew:'ve-asah ha-am al pihem',translation:'The people acted on their instruction.',prompt:'What changes when the public acts on the court\'s instruction?',answers:['The source must account for good-faith reliance and communal consequences, not only the court\'s intent.','Reliance turns every later action into deliberate rebellion.','The court\'s responsibility disappears because others acted.'],correct:0,skill:'horayot-communal-reliance',competency:'argument',feedback:'Good. Horayot tracks how institutional speech travels into communal action.'},
{short:'Ask the trigger',mode:'GEMARA QUESTION',title:'What kind of error triggers liability?',ref:'Horayot 2a',hebrew:'mai taima de-shagagu',translation:'What is the reason they erred?',prompt:'What does the Gemara\'s question invite?',answers:['Separate the court\'s type of error, the issue ruled upon, and the acts that followed.','Assume that every mistake has the same legal result.','Replace the source question with a modern political judgment.'],correct:0,skill:'horayot-error-trigger',competency:'argument',feedback:'Right. The Gemara asks for a precise map of error rather than a blanket label.'},
{short:'Keep roles apart',mode:'ROLE DISTINCTION',title:'Court, public, and individual',ref:'Horayot 2a',hebrew:'bet din · tzibbur · yachid',translation:'Court · community · individual.',prompt:'Why distinguish these actors?',answers:['Different actors may carry different obligations when a mistaken ruling is followed.','The categories are rhetorical and can be collapsed.','Only the individual matters once an outcome occurs.'],correct:0,skill:'horayot-role-distinction',competency:'sourceReasoning',feedback:'Yes. Responsibility is distributed by role, authority, and reliance.'},
{short:'Plan correction',mode:'REPAIR MAP',title:'Correction is part of responsibility',ref:'Horayot source map',hebrew:'teshuvah · hodaah · tikun',translation:'Return · acknowledgment · repair.',prompt:'What is the best response after discovering a mistaken institutional ruling?',answers:['Acknowledge the error, stop extending it, and map the appropriate repair within the source\'s categories.','Hide the error so institutional authority appears perfect.','Treat correction as proof that all authority is illegitimate.'],correct:0,skill:'horayot-correction',competency:'argument',feedback:'Exactly. Responsible authority includes correction, not only initial confidence.'},
{short:'Set a boundary',mode:'HISTORICAL STUDY',title:'Ancient authority is not a present ruling',ref:'Seder Horayot boundary',hebrew:'limmud historii · lo horaah lemaaseh',translation:'Historical study · not a practical ruling.',prompt:'What is Seder\'s responsible stance?',answers:['Study the tractate\'s institutional categories historically without presenting them as a current legal decision.','Use an ancient court case to authorize a present action automatically.','Avoid the tractate because institutional error is uncomfortable to examine.'],correct:0,skill:'horayot-historical-boundary',competency:'sourceReasoning',feedback:'Serious learning preserves historical precision and distinguishes study from contemporary authority.'},
{short:'Transfer the map',mode:'INDEPENDENT READ',title:'Map an institutional mistake',ref:'Horayot transfer checkpoint',hebrew:'reshut · taat · הסתמכות · tikun',translation:'Authority · error · reliance · repair.',independent:true,prompt:'What is the best first map for an unfamiliar institutional ruling?',answers:['Identify authority, jurisdiction, type of error, who relied on it, and what correction follows.','Begin with a verdict about whether institutions are trustworthy.','Treat every mistaken ruling as intentional wrongdoing.'],correct:0,skill:'horayot-independent-map',competency:'sourceReasoning',feedback:'You can now read Horayot through authority, reliance, responsibility, and repair.'}
]};
const horayotSteps=window.SederCourse.steps;
horayotSteps[0].hebrew='הוֹרוּ בֵּית דִּין לַעֲבוֹר עַל אַחַת מִכָּל מִצְוֹת הָאֲמוּרוֹת בַּתּוֹרָה';
horayotSteps[1].hebrew='בֵּית דִּין הַגָּדוֹל';
horayotSteps[2].hebrew='וְעָשָׂה הָעָם עַל פִּיהֶם';
horayotSteps[3].hebrew='מַאי טַעְמָא דְּשָׁגְגוּ';
horayotSteps[4].hebrew='בֵּית דִּין · צִבּוּר · יָחִיד';
horayotSteps[5].hebrew='הוֹדָאָה · תְּשׁוּבָה · תִּקּוּן';
horayotSteps[6].hebrew='לִמּוּד הִיסְטוֹרִי · לֹא הוֹרָאָה לְמַעֲשֶׂה';
horayotSteps[7].hebrew='רְשׁוּת · טָעוּת · הִסְתַּמְּכוּת · תִּקּוּן';
horayotSteps.push({short:'Explain correction',mode:'SOURCE CHECK',title:'Produce the institutional map',ref:'Horayot transfer checkpoint',hebrew:'הוראה Â· סמכות Â· הסתמכות Â· תיקון',translation:'Ruling Â· authority Â· reliance Â· correction.',independent:true,prompt:'Which explanation best transfers Horayot’s reading method to a new institutional error?',answers:['Identify the authority and jurisdiction, describe the error and reliance, then specify what source-grounded correction follows.','Begin by defending or condemning the institution, then treat the factual error and public reliance as details that cannot change the verdict.','Treat the discovery of an error as enough to assign blame, without distinguishing who ruled, who relied, or what repair the source requires.'],correct:0,skill:'horayot-source-transfer-check',competency:'sourceReasoning',feedback:'This source check makes you produce Horayot’s sequence of authority, error, reliance, and repair rather than merely recognize its vocabulary.'});
const horayotNearMisses=[
['It treats every disagreement as a court error, without distinguishing an authorized institutional ruling from an individual’s mistaken judgment.','It treats an unintentional ruling as consequence-free, leaving no room for the tractate’s analysis of authority, reliance, and atonement.'],
['It treats authority as a label that any speaker can claim, rather than a jurisdictional condition that determines which reliance rules apply.','It treats later discovery as making jurisdiction irrelevant, even though the source asks who had standing to issue the ruling.'],
['It treats public reliance as deliberate rebellion, rather than asking how good-faith action on an authorized instruction changes the analysis.','It treats communal action as removing the court’s responsibility, rather than tracing how institutional speech creates consequences beyond intent.'],
['It assumes every mistake receives the same outcome, instead of separating the type of error, the issue ruled upon, and the acts that followed.','It replaces the Gemara’s source question with a present political judgment, skipping the textual trigger that defines the liability problem.'],
['It collapses court, community, and individual into one actor, so the source cannot assign distinct obligations to authority, reliance, and action.','It treats only the individual as relevant once an outcome occurs, erasing the institutional roles that make Horayot’s case distinctive.'],
['It hides the error to preserve authority, rather than acknowledging it, stopping its extension, and mapping a repair within the source’s categories.','It treats correction as proof that all authority is illegitimate, rather than as part of responsible authority after a mistaken ruling.'],
['It treats an ancient court category as an automatic present legal decision, rather than as historical study that must remain distinct from contemporary authority.','It avoids the tractate because institutional error is difficult, sacrificing precise learning instead of maintaining a responsible study boundary.'],
['It begins by deciding whether institutions deserve trust, instead of mapping jurisdiction, error, reliance, and correction in the new source.','It treats every mistaken ruling as intentional wrongdoing, ignoring how Horayot distinguishes authority, intent, good-faith reliance, and repair.']];
horayotNearMisses.forEach((pair,i)=>{horayotSteps[i].answers[1]=pair[0];horayotSteps[i].answers[2]=pair[1];});
