window.SederCourse={stage:'independent-reading-checkpoint',completeTitle:'You read unfamiliar lines by function.',completeCopy:'Translation confirmed your reading rather than replacing it. Return to a tractate lab and use the same approach on a fuller source page.',nextUrl:'shas-map-v2.html',nextLabel:'Choose a tractate lab',steps:[
{short:'Question signal',mode:'UNFAMILIAR SOURCE',title:'Find the question',ref:'Gemara reading checkpoint',hebrew:'מַאי טַעְמָא?',translation:'What is the reason?',independent:true,prompt:'What should you expect the next lines to supply?',answers:['A reason or principle behind an earlier statement.','A new tractate without connection.','A final ruling with no explanation.'],correct:0,skill:'independent-question-signal',competency:'argument',feedback:'You recognized a question before needing the translation.'},
{short:'Cited teaching',mode:'UNFAMILIAR SOURCE',title:'Locate the evidence',ref:'Gemara reading checkpoint',hebrew:'תַּנְיָא',translation:'It was taught.',independent:true,prompt:'What is the line likely doing?',answers:['Introducing a teaching to test, support, or clarify the issue.','Announcing the end of debate.','Giving a personal reflection.'],correct:0,skill:'independent-cited-teaching',competency:'sourceReasoning',feedback:'A cited teaching is evidence with a job inside the argument.'},
{short:'Objection',mode:'UNFAMILIAR SOURCE',title:'See the pressure',ref:'Gemara reading checkpoint',hebrew:'מֵיתִיבֵי',translation:'They raise an objection.',independent:true,prompt:'What should a learner look back for?',answers:['The previous claim that this source threatens.','A page number in the margin.','An English translation of every word.'],correct:0,skill:'independent-objection',competency:'argument',feedback:'Objections only make sense in relation to the claim they press.'},
{short:'Distinction',mode:'UNFAMILIAR SOURCE',title:'Preserve two sources',ref:'Gemara reading checkpoint',hebrew:'הָא בְּ… הָא בְּ…',translation:'This is in one case; that is in another.',independent:true,prompt:'What type of solution is being offered?',answers:['A distinction between cases that dissolves an apparent conflict.','A rejection of all prior evidence.','A new philosophical claim.'],correct:0,skill:'independent-distinction',competency:'argument',feedback:'You identified a core move of Talmudic analysis.'},
{short:'Conclusion',mode:'UNFAMILIAR SOURCE',title:'Name the inference',ref:'Gemara reading checkpoint',hebrew:'שְׁמַע מִינָּהּ',translation:'Learn from it.',independent:true,prompt:'What should you ask before accepting the conclusion?',answers:['Which sources support this inference and whether competing evidence remains.','Whether the page looks difficult.','Which answer position is usually correct.'],correct:0,skill:'independent-conclusion',competency:'sourceReasoning',feedback:'Independent reading is active: you can recognize a conclusion and evaluate how it was reached.'},
{short:'Type the meaning',mode:'PRODUCTION CHECK',title:'Recall, don’t just recognize',ref:'Gemara reading checkpoint',hebrew:'מֵיתִיבֵי',translation:'They raise an objection.',independent:true,typed:true,prompt:'Type the English meaning of this word in one or two words.',acceptable:['they raise an objection','raise an objection','objection','they object'],skill:'independent-typed-recall',competency:'translation',feedback:'Typing an answer from memory is a stronger test of durable mastery than recognizing it among choices.'}
]};
// Each alternative represents a distinct reading mistake, not a cue from answer length.
const independentSteps=window.SederCourse.steps;
independentSteps[0].answers=['A reason or principle behind an earlier statement.','A change of tractate that does not answer the earlier statement.','A final ruling presented without a reason or argument.'];
independentSteps[1].answers=['Introducing a teaching to test, support, or clarify the issue.','Announcing that the discussion has ended without needing further evidence.','Introducing a personal reflection that does not bear on the argument.'];
independentSteps[2].answers=['The previous claim that this source threatens.','The margin detail that identifies the printing but not the argument.','An English gloss for every word before asking what the source challenges.'];
independentSteps[3].answers=['A distinction between cases that dissolves an apparent conflict.','A rejection of the earlier evidence rather than an account of its different case.','A new philosophical claim that does not address the two sources in tension.'];
independentSteps[4].answers=['Which sources support this inference and whether competing evidence remains.','Whether the conclusion appears near the bottom of the printed page.','Which option seems familiar without tracing the sources that led to it.'];
