window.SederCourse={stage:'keritot-tractate-arc',completeTitle:'You can now distinguish serious liability from the conditions that shape atonement.',completeCopy:'You tracked a fixed transgression category, the role of knowledge and intention, the offering assigned by Torah, and the limits that keep separate cases separate. Continue into the Keritot source workspace.',nextUrl:'lab.html?tractate=keritot',nextLabel:'Open the Keritot source workspace',steps:[
{short:'Locate the category',mode:'CASE ORIENTATION',title:'A counted field of liability',ref:'Mishnah Keritot 1:1',hebrew:'keret · shogeg · chatat',translation:'karet · inadvertence · sin-offering',prompt:'What pressure does the opening Mishnah create?',answers:['It gathers grave transgressions into a defined category and asks what liability follows when one acts inadvertently.','It says every mistake carries the same penalty regardless of the act.','It treats the list as a narrative with no legal categories.'],correct:0,skill:'keritot-liability-category',competency:'recognition',feedback:'Right. Keritot begins with a counted legal field: serious acts, a defined consequence, and a question about inadvertent performance.'},
{short:'Count the field',mode:'LEGAL CATEGORY',title:'Why thirty-six?',ref:'Mishnah Keritot 1:1',hebrew:'shloshim veshesh · avot melachot',translation:'thirty-six · principal categories',prompt:'What should a reader preserve when the Mishnah counts the transgressions?',answers:['The number is a boundary marker: it defines which grave acts belong to this liability system.','The count is only a mnemonic and has no interpretive force.','Every prohibited act automatically belongs in the same count.'],correct:0,skill:'keritot-counted-field',competency:'sourceReasoning',feedback:'Good. A counted list is an argument about scope, not merely a memory aid.'},
{short:'Name knowledge',mode:'FACT PATTERN',title:'Knowing and not knowing',ref:'Keritot 2a',hebrew:'yedi·ah · shegagah · mezid',translation:'knowledge · inadvertence · deliberate act',prompt:'Why does the source track what the person knew?',answers:['Knowledge and intention distinguish an inadvertent act, which can generate an offering, from a deliberate act with a different path.','Knowledge never changes the legal analysis.','Any act called accidental receives the same consequence even when the person knew the rule.'],correct:0,skill:'keritot-knowledge-intent',competency:'sourceReasoning',feedback:'Exactly. Keritot makes mental state a legal fact: ignorance, recognition, and deliberate action cannot be collapsed.'},
{short:'Separate atonement',mode:'DISTINCTION MAP',title:'Liability is not the offering',ref:'Keritot source map',hebrew:'chiyuv · kaparah · korban',translation:'liability · atonement · offering',prompt:'What distinction should remain visible?',answers:['First identify the liability; then ask which atonement or offering the Torah assigns to that case.','The offering itself determines whether an act was prohibited.','A person can choose any offering once liability is established.'],correct:0,skill:'keritot-liability-atonement',competency:'argument',feedback:'Right. A careful map separates the act, the liability, and the prescribed means of atonement.'},
{short:'Find the source',mode:'GEMARA QUESTION',title:'Which verse fixes the case?',ref:'Keritot 2a',hebrew:'mai taama · minayin',translation:'what is the reason · from where',prompt:'What does a Gemara source-question invite here?',answers:['Ask which scriptural phrase makes the knowledge condition and offering assignment legally decisive.','Replace the verse with a modern intuition about intent.','Ignore the wording because the list is self-explanatory.'],correct:0,skill:'keritot-proof-source',competency:'argument',feedback:'Good. The Gemara tests the list against its textual basis and asks how the verse controls the case.'},
{short:'Test the scope',mode:'SOURCE MAP',title:'One act, more than one condition',ref:'Keritot 3a',hebrew:'safek · yedi·ah · tinok shenishbah',translation:'doubt · knowledge · captive child',prompt:'What should a reader test after finding the rule?',answers:['Which conditions alter liability or atonement, and which facts leave the original category intact.','Whether one offering must cover every possible knowledge state.','Whether uncertainty can be ignored once an act is named.'],correct:0,skill:'keritot-scope-conditions',competency:'argument',feedback:'Yes. Scope work follows the conditions: doubt, later knowledge, and constrained knowledge can change the legal path.'},
{short:'Keep the boundary',mode:'RESPONSIBLE LEARNING',title:'Historical atonement categories',ref:'Seder Keritot boundary',hebrew:'lilmod · lehavin · lishol',translation:'to learn · to understand · to ask',prompt:'What is the responsible use of these offering sources?',answers:['Study their categories and reasoning as historical textual literacy, not as current ritual instruction.','Treat the ancient offering system as a present-day procedure.','Avoid the legal reasoning because the Temple setting is historical.'],correct:0,skill:'keritot-learning-boundary',competency:'sourceReasoning',feedback:'Serious study honors the precision of the source while distinguishing historical sacrificial law from present practice.'},
{short:'Transfer',mode:'SOURCE CHECK',title:'Map liability with care',ref:'Keritot transfer checkpoint',hebrew:'maaseh · yedi·ah · chiyuv · kaparah',translation:'act · knowledge · liability · atonement',independent:true,prompt:'What is the best first map for a new Keritot case?',answers:['Name the act, establish knowledge and intention, identify the liability, then test the prescribed atonement and its limits.','Choose an offering first and infer the person’s mental state afterward.','Treat liability, knowledge, and atonement as interchangeable labels.'],correct:0,skill:'keritot-independent-map',competency:'sourceReasoning',feedback:'You can now read Keritot by tracking act, mental state, liability, atonement, and boundary in order.'}]};
window.SederCourse.steps[0].hebrew='שְׁלֹשִׁים וְשֵׁשׁ כְּרֵתוֹת בַּתּוֹרָה';
window.SederCourse.steps[0].translation='Thirty-six excisions are in the Torah.';
window.SederCourse.steps[1].hebrew='שְׁלֹשִׁים וְשֵׁשׁ כְּרֵתוֹת';
window.SederCourse.steps[1].translation='Thirty-six excisions.';
window.SederCourse.steps[2].hebrew='יְדִיעָה · שְׁגָגָה · מֵזִיד';
window.SederCourse.steps[3].hebrew='חִיּוּב · כַּפָּרָה · קָרְבָּן';
window.SederCourse.steps[4].hebrew='מַאי טַעְמָא · מִנַּיִן';
window.SederCourse.steps[5].hebrew='סָפֵק · יְדִיעָה · תִּינוֹק שֶׁנִּשְׁבָּה';
window.SederCourse.steps[6].hebrew='לִלְמוֹד · לְהָבִין · לִשְׁאוֹל';
window.SederCourse.steps[7].hebrew='מַעֲשֶׂה · יְדִיעָה · חִיּוּב · כַּפָּרָה';
// Keep the recognition alternatives substantive enough to test a real near-miss,
// not reward the shortest distractor. Each pair elaborates that step's own wrong
// reading (the horayot near-miss pattern); a shared boilerplate suffix would hand
// the learner a stronger tell than the length bias it was meant to remove.
const keritotNearMisses=[
['It assigns one identical penalty to every mistake, so the difference between deliberate and inadvertent action does no legal work.','It opens with a narrative list that carries no legal categories, so the count of transgressions has no bearing on liability.'],
['The count is only a mnemonic device for memorization, with no interpretive force about which acts belong inside the category.','Every prohibited act in the Torah automatically joins the same count, so the number thirty-six marks no real boundary at all.'],
['Knowledge never changes the legal analysis, since the act alone settles both the liability and the path of atonement.','Any act called accidental receives the same consequence even when the person knew the rule, so mental state is not a legal fact.'],
['The offering itself determines whether the act was prohibited, so atonement defines liability rather than following from it.','Once liability is established a person may choose any offering, since the Torah does not match specific offerings to cases.'],
['Replace the verse with a modern intuition about intent, since present moral judgment outweighs the source\'s exact wording.','Ignore the wording because the counted list is self-explanatory and needs no scriptural basis to control the case.'],
['Whether one offering must cover every possible knowledge state, since conditions like doubt cannot change the legal path.','Whether uncertainty can be ignored once an act is named, because the initial classification settles every later question.'],
['Treat the ancient offering system as a present-day procedure that a modern reader could carry out from these sources.','Avoid the legal reasoning entirely because the Temple setting is historical and therefore has nothing to teach a reader.'],
['Choose an offering first and infer the person\'s mental state afterward, letting the atonement determine what the act must have been.','Treat liability, knowledge, and atonement as interchangeable labels for one idea that any of the three can stand in for.']];
keritotNearMisses.forEach((pair,i)=>{const step=window.SederCourse.steps[i];step.answers[1]=pair[0];step.answers[2]=pair[1];});
