window.SederCourse={stage:'ketubot-tractate-arc',completeTitle:'You can now read a fixed detail as a door into institutional reasoning.',completeCopy:'You separated a Mishnah\'s schedule from its reason, traced that reason to a concrete institutional practice, weighed it against a second real concern, and kept the line between study and practical guidance. These skills carry into any tractate where a fixed detail conceals a functional reason.',nextUrl:'lab.html?tractate=ketubot',nextLabel:'Practice on the Ketubot working Daf',steps:[
{short:'Read the schedule',mode:'CASE ORIENTATION',title:'A Mishnah sets a schedule',ref:'Mishnah Ketubot 1:1',hebrew:'בְּתוּלָה נִשֵּׂאת לְיוֹם הָרְבִיעִי וְאַלְמָנָה לַחֲמִישִׁי',translation:'A virgin is married on Wednesday, and a widow on Thursday.',prompt:'What kind of information does this opening line provide?',answers:['A fixed schedule for two different kinds of marriage, stated before any reason is given.','A list of witnesses required at a wedding.','A biblical quotation about marriage.'],correct:0,skill:'ketubot-schedule',competency:'recognition',feedback:'Right. The Mishnah states a schedule first — the reason behind it is exactly what the Gemara will investigate.'},
{short:'Look for a reason',mode:'CASE ORIENTATION',title:'A schedule invites a question',ref:'Ketubot 2a',hebrew:'מַאי שְׁנָא יוֹם הָרְבִיעִי',translation:'Why specifically Wednesday?',prompt:'What is the Gemara likely to investigate here?',answers:['Why this particular day serves some purpose the Mishnah has not yet explained.','How to spell Wednesday in Hebrew.','Whether the Mishnah has a printing error.'],correct:0,skill:'ketubot-reason-question',competency:'sourceReasoning',feedback:'Exactly. The Gemara often turns a fixed, unexplained detail into a question about institutional purpose.'},
{short:'Trace the court-access answer',mode:'SOURCE LAYER',title:'A fixed day, a working court',ref:'Ketubot 2a',hebrew:'בָּתֵּי דִינִין יוֹשְׁבִין בָּעֲיָירוֹת בַּשֵּׁנִי וּבַחֲמִישִׁי',translation:'Courts sit in the towns on Monday and Thursday.',prompt:'How does this fact answer the “why Wednesday” question?',answers:['A groom with a claim about the marriage could reach a sitting court the very next morning, on Thursday.','It proves the Mishnah is unrelated to courts at all.','It shows that courts never sat on a fixed schedule.'],correct:0,skill:'ketubot-court-access',competency:'sourceReasoning',feedback:'Right. Marrying on Wednesday night placed any urgent claim one morning away from a functioning court — the schedule serves a real institutional need.'},
{short:'Weigh a second concern',mode:'DISTINCTION',title:'Court access alone would allow Sunday',ref:'Ketubot 2a',hebrew:'כְּבוֹדָהּ',translation:'Her honor / dignity.',prompt:'If reaching a sitting court were the only concern, a Sunday wedding would also work, with Monday available for any claim. Why does the Gemara prefer Wednesday over Sunday?',answers:['Sunday leaves no ordinary weekday before it for preparing a fitting wedding feast, since it follows Shabbat — so Wednesday balances court access against the bride’s dignity.','The Gemara has no interest in the bride’s experience at all.','Sunday weddings were legally forbidden outright.'],correct:0,skill:'ketubot-second-concern',competency:'argument',feedback:'Good. A single schedule can serve two real values at once — evidentiary access and human dignity — and naming both keeps the reading honest.'},
{short:'Name the move',mode:'LEGAL CATEGORY',title:'Keep the structure visible',ref:'Ketubot 2a reading habit',hebrew:'מִשְׁנָה · שְׁאֵלָה · טַעַם',translation:'Mishnah · question · reason.',prompt:'Which sequence describes what you just traced across these sources?',answers:['A fixed rule, a question about why it exists, then an answer built from real institutional and social concerns.','A final ruling with no discussion at all.','A verse followed by an unrelated story.'],correct:0,skill:'ketubot-structure',competency:'argument',feedback:'Good. Naming the sequence — rule, question, reason — is a skill that transfers to nearly every opening sugya in Shas.'},
{short:'Keep the boundary',mode:'RESPONSIBLE LEARNING',title:'Sensitive material needs a clear line',ref:'Jewish Learning Academy learning boundary',hebrew:'לִלְמוֹד · לְהָבִין · לִשְׁאוֹל',translation:'To learn · to understand · to ask.',prompt:'Ketubot opens with claims that touch a couple’s private life. What is Jewish Learning Academy’s appropriate role here?',answers:['Support careful reading of the sugya’s structure and reasoning while directing any real personal or marital question to qualified guidance.','Use the Mishnah to answer a real question about someone’s marriage.','Avoid the tractate because the subject is sensitive.'],correct:0,skill:'ketubot-non-psak-boundary',competency:'sourceReasoning',feedback:'Right. A tractate can be studied seriously and responsibly without ever standing in for a rabbi, court, or counselor.'},
{short:'Transfer the habit',mode:'TRANSFER',title:'A measurement had a reason too',ref:'Mishnah Eruvin 1:1',hebrew:'מִשּׁוּם דְּלֹא שָׁלְטָא בֵּיהּ עֵינָא',translation:'Because the eye does not take hold of it.',prompt:'You already learned that Eruvin’s twenty-cubit measure has a functional reason. What does that skill let you expect from any fixed detail in a Mishnah?',answers:['That a specific number, day, or measure is rarely arbitrary — it is worth asking what real concern it was built to serve.','That every measurement in the Mishnah is decorative.','That reasons behind Mishnaic details are never recoverable.'],correct:0,skill:'ketubot-transfer',competency:'sourceReasoning',feedback:'The same habit — treat a fixed detail as a question, not a given — reads Eruvin’s cubits and Ketubot’s weekday with the same discipline.'},
{short:'Independent read',mode:'INDEPENDENT READ',title:'Map the schedule on your own',ref:'Ketubot 2a reading checkpoint',hebrew:'בְּתוּלָה נִשֵּׂאת לְיוֹם הָרְבִיעִי · מַאי שְׁנָא · בָּתֵּי דִינִין',translation:'A virgin is married on Wednesday · why different · courts sit.',independent:true,prompt:'What is the first independent-reading move across these three fragments?',answers:['Name the schedule, ask why it is fixed this way, then look for the institutional or social reason behind it.','Assume the schedule needs no explanation.','Guess the reason before reading the Gemara’s own answer.'],correct:0,skill:'ketubot-independent-map',competency:'sourceReasoning',feedback:'You can now enter a schedule-and-reason sugya with a concrete map.'},
{short:'Type the meaning',mode:'PRODUCTION CHECK',title:'Recall, don’t just recognize',ref:'Ketubot 2a',hebrew:'מַאי שְׁנָא',translation:'Why is it different? / What is different?',independent:true,typed:true,prompt:'Type the English meaning of this phrase in a few words.',acceptable:['why is it different','what is different','why different','why is this different'],skill:'ketubot-typed-recall',competency:'translation',feedback:'Typing an answer from memory is a stronger test of durable mastery than recognizing it among choices.'}
]};
// Alternatives diagnose schedule-reading errors without turning answer length into a shortcut.
const ketubotSteps=window.SederCourse.steps;
ketubotSteps[0].answers=['A fixed schedule for two different kinds of marriage, stated before any reason is given.','A list of required witnesses arranged by day, rather than a schedule that differentiates two categories.','A biblical teaching about marriage that the Mishnah quotes without creating an institutional timetable.'];
ketubotSteps[1].answers=['Why this particular day serves some purpose the Mishnah has not yet explained.','How the Hebrew name for Wednesday was spelled by the court that heard marriage claims.','Whether the Mishnah contains a copying error rather than an institutional reason for the day.'];

// [rebalance] distractor lengths evened so the correct answer is not the longest option
window.SederCourse.steps[2].answers[1]="It proves that the Mishnah is entirely unrelated to courts or their sittings at all.";
window.SederCourse.steps[2].answers[2]="It shows that the courts of that era never once sat on any fixed schedule.";
window.SederCourse.steps[3].answers[1]="The Gemara has no real interest in the bride's own experience of the wedding at all, only in the court's own sitting schedule.";
window.SederCourse.steps[3].answers[2]="Sunday weddings were simply forbidden outright by the law, which is the only real reason another day of the week was chosen.";
window.SederCourse.steps[4].answers[1]="A single final ruling stated flatly, with no surrounding discussion of it at all.";
window.SederCourse.steps[4].answers[2]="A Torah verse that is simply followed by an entirely unrelated narrative story.";
window.SederCourse.steps[5].answers[1]="Use the Mishnah directly to try to answer a real, live question about someone's actual marriage.";
window.SederCourse.steps[5].answers[2]="Avoid the tractate altogether simply on the grounds that its subject matter is a sensitive one.";
window.SederCourse.steps[6].answers[1]="That every single measurement stated in the Mishnah is essentially just decorative.";
window.SederCourse.steps[6].answers[2]="That the reasons standing behind Mishnaic details can never really be recovered at all.";
window.SederCourse.steps[7].answers[1]="Assume that the fixed wedding schedule needs no explanation of any real kind at all.";
window.SederCourse.steps[7].answers[2]="Guess at the reason yourself before ever reading the Gemara's own stated answer.";
