window.SederCourse={stage:'kiddushin-tractate-arc',completeTitle:'You can now read Kiddushin through acquisition, consent, and status.',completeCopy:'You traced how Kiddushin names the acts, agents, conditions, and status effects that organize a marriage category while keeping historical study distinct from present-day guidance. Continue into the Kiddushin source workspace.',nextUrl:'lab.html?tractate=kiddushin',nextLabel:'Open the Kiddushin source workspace',steps:[
{short:'Name acquisition',mode:'CATEGORY ORIENTATION',title:'Acquisition has defined forms',ref:'Mishnah Kiddushin 1:1',hebrew:'האשה נקנית בשלש דרכים',translation:'A woman is acquired through three ways.',prompt:'What does the opening Mishnah ask you to notice?',answers:['The source organizes kiddushin through specified acquisition categories rather than an undefined private gesture.','Any gift automatically creates every marriage status.','The categories are only poetic descriptions with no legal work.'],correct:0,skill:'kiddushin-acquisition-categories',competency:'recognition',feedback:'Right. Kiddushin begins by naming the forms through which a status-changing act is recognized.'},
{short:'Locate agency',mode:'CONSENT AND AGENCY',title:'An act needs an authorized actor',ref:'Mishnah Kiddushin 2a',hebrew:'האיש מקדש בו ובשלוחו',translation:'A man betroths directly or through his agent.',prompt:'Why does the source distinguish direct action from agency?',answers:['It maps who may perform the act and how an authorized agent can stand in for the principal.','Any observer becomes an agent merely by being present.','Agency removes the need for any defined act or recipient.'],correct:0,skill:'kiddushin-consent-agency',competency:'sourceReasoning',feedback:'Exactly. Agency extends action through a mandate; it does not erase authorization.'},
{short:'Check status',mode:'STATUS EFFECT',title:'A category changes personal status',ref:'Kiddushin 2b',hebrew:'מקודשת לי',translation:'You are set apart / betrothed to me.',prompt:'What should a reader track after the formal act?',answers:['Which status the source says follows, and which conditions make that status effective.','Whether the phrase sounds emotionally sincere to a modern listener.','Whether every relationship now has the same legal status.'],correct:0,skill:'kiddushin-status-effects',competency:'argument',feedback:'Good. The tractate keeps the speech-act and its status consequence connected but distinct.'},
{short:'Test conditions',mode:'VALIDITY CONDITIONS',title:'Objects and measures matter',ref:'Mishnah Kiddushin 1:1',hebrew:'בכסף בשוה פרוטה',translation:'With money worth at least a perutah.',prompt:'Why does the source specify a measure?',answers:['A defined threshold separates a recognized acquisition act from an insufficient or ambiguous transfer.','Any object has identical force regardless of value.','The measure is optional once the parties agree privately.'],correct:0,skill:'kiddushin-validity-conditions',competency:'sourceReasoning',feedback:'Yes. Torah categories often work through concrete thresholds that make status legible.'},
{short:'Read conditions',mode:'CONDITIONAL LANGUAGE',title:'A condition can shape the outcome',ref:'Kiddushin 61b',hebrew:'על מנת כן',translation:'On the condition that…',prompt:'How should a reader approach conditional language?',answers:['Identify the condition, when it must be met, and whether the source treats the status as dependent on it.','Assume every condition is merely rhetorical emphasis.','Ignore the condition once the initial words were spoken.'],correct:0,skill:'kiddushin-conditional-language',competency:'argument',feedback:'Right. Conditional language requires a sequence: act, condition, fulfillment, and status effect.'},
{short:'Limit representation',mode:'REPRESENTATION LIMITS',title:'A representative carries a defined mandate',ref:'Kiddushin 41a',hebrew:'שלוחו של אדם כמותו',translation:'A person’s agent is like the person himself.',prompt:'What boundary keeps agency precise?',answers:['The agent acts within the principal’s assigned purpose and cannot invent a new status or term.','The agent may change the recipient or condition at will.','Any third party can ratify an act without authorization.'],correct:0,skill:'kiddushin-representation',competency:'sourceReasoning',feedback:'Exactly. Representation transmits an authorized act; it does not create unlimited power.'},
{short:'Keep the boundary',mode:'HISTORICAL STUDY',title:'Status categories need present-day care',ref:'Jewish Learning Academy Kiddushin boundary',hebrew:'ללמוד ולהבין · לא להורות למעשה',translation:'Study to understand; do not treat this lesson as a practical ruling.',prompt:'What is Jewish Learning Academy’s responsible stance?',answers:['Study ancient status and agency categories historically while directing personal questions to qualified contemporary authorities.','Apply a source excerpt directly to a present relationship without context.','Avoid the tractate because its status language is difficult.'],correct:0,skill:'kiddushin-historical-boundary',competency:'sourceReasoning',feedback:'Serious study preserves the text’s categories and acknowledges the limits of an educational lesson.'},
{short:'Map a case',mode:'INDEPENDENT READ',title:'Read an unfamiliar Kiddushin passage',ref:'Kiddushin transfer checkpoint',hebrew:'מעשה · סוכן · תנאי · מעמד',translation:'Act · agent · condition · status.',independent:true,prompt:'What is the best first map for an unfamiliar passage?',answers:['Identify the acquisition form, actor and agency, condition, measure, and resulting status before evaluating the dispute.','Begin with a modern conclusion before locating the source categories.','Collapse consent, agency, and status into one undifferentiated idea.'],correct:0,skill:'kiddushin-independent-map',competency:'sourceReasoning',feedback:'You can now read Kiddushin through acquisition categories, agency, conditions, and status effects.'}
]};
const kiddushinSteps=window.SederCourse.steps;
kiddushinSteps.push({short:'Explain the status act',mode:'SOURCE CHECK',title:'Produce the category map',ref:'Kiddushin transfer checkpoint',hebrew:'קנין · שליח · תנאי · מעמד',translation:'Acquisition · agent · condition · status.',independent:true,prompt:'Which explanation best transfers the Kiddushin reading method to a new status-changing act?',answers:['Identify the recognized form, authorized actor, measure or condition, and status effect before evaluating the dispute.','Begin with the relationship outcome that seems intuitive, then fit the source’s categories into that conclusion afterward.','Treat consent, agency, value, and status as one undifferentiated event whose separate conditions need no analysis.'],correct:0,skill:'kiddushin-source-transfer-check',competency:'sourceReasoning',feedback:'This source check makes you produce Kiddushin’s sequence of form, agency, condition, and status rather than merely recognize its vocabulary.'});
const kiddushinNearMisses=[
['It treats the opening phrase as poetic language with no defined acquisition categories, so any private gesture would appear to create the same status.','It treats every gift as carrying every marriage status, ignoring the Mishnah’s careful list of recognized forms.'],
['It treats any observer as an agent merely by being present, rather than requiring an authorized mandate that connects the act to a principal.','It treats agency as removing the need for a defined actor, act, or recipient, so authorization no longer limits the status effect.'],
['It treats status as whatever a modern listener feels the phrase expresses, rather than tracking the source’s formal consequence and its conditions.','It treats every relationship as producing the same status, collapsing the distinctions that Kiddushin asks the reader to follow.'],
['It treats the measure as optional once the parties agree, rather than as a concrete threshold separating a recognized act from an insufficient transfer.','It treats every object as legally identical regardless of value, erasing the source’s work of making status legible through a specified measure.'],
['It treats conditional language as rhetorical emphasis, rather than asking what must occur, when it must occur, and whether status depends on fulfillment.','It treats the condition as irrelevant once the first words are spoken, collapsing the source’s sequence of act, condition, and effect.'],
['It treats the agent’s mandate as unlimited, allowing a representative to change the recipient or terms instead of transmitting the principal’s assigned purpose.','It treats third-party presence as enough to ratify an act, replacing authorization with observation and erasing agency’s defined limits.'],
['It treats ancient status categories as a direct contemporary ruling, rather than studying their historical structure while directing personal questions to qualified authorities.','It treats the subject’s complexity as a reason to avoid learning, rather than preserving serious study alongside a clear boundary against personal guidance.'],
['It begins with a modern conclusion and forces the passage into it, instead of mapping acquisition form, actor, condition, measure, and status first.','It merges consent, agency, and status into one event, so the reader cannot identify which condition the source is actually disputing.']];
kiddushinNearMisses.forEach((pair,i)=>{kiddushinSteps[i].answers[1]=pair[0];kiddushinSteps[i].answers[2]=pair[1];});
