window.SederCourse={stage:'megillah-tractate-arc',completeTitle:'You can now read a public schedule as a source map.',completeCopy:'You mapped a reading range, its communities, its exception, and the Gemara’s practical explanation. Continue into the visible Megillah source workspace.',nextUrl:'megillah-daf-workbench.html',nextLabel:'Open the Megillah source workspace',steps:[
{short:'Orient the range',mode:'CASE ORIENTATION',title:'Five possible days, one bounded window',ref:'Megillah 2a',hebrew:'מגילה נקראת באחד עשר בשנים עשר בשלשה עשר בארבעה עשר ובחמשה עשר',translation:'The Megillah is read on the eleventh, twelfth, thirteenth, fourteenth, or fifteenth.',prompt:'What does this opening range tell a careful reader?',answers:['The source establishes a bounded reading window whose different dates will need explanation.','The date of reading is completely unstructured.','Five unrelated holidays are being named.'],correct:0,skill:'megillah-reading-window',competency:'recognition',feedback:'Right. A range invites the reader to ask which communities receive which date and why.'},
{short:'Read the limit',mode:'BOUNDARY',title:'Flexibility has an edge',ref:'Megillah 2a',hebrew:'לא פחות ולא יותר',translation:'Not earlier and not later.',prompt:'What job does this phrase perform?',answers:['It marks that the range is deliberate and bounded, not an open-ended choice.','It says every community reads on exactly the same day.','It removes the need to explain the range.'],correct:0,skill:'megillah-bounded-range',competency:'sourceReasoning',feedback:'Exactly. The Mishnah gives flexibility a defined limit.'},
{short:'Map a community',mode:'PLACE AND TIME',title:'Walled cities receive a distinct date',ref:'Megillah 2a',hebrew:'כרכין המוקפין חומה מימות יהושע בן נון קורין בחמשה עשר',translation:'Cities walled from the days of Joshua son of Nun read on the fifteenth.',prompt:'What should you map before trying to explain this rule?',answers:['The community category, its historical anchor, and the date attached to it.','Only the number fifteen.','A modern ruling for every walled city.'],correct:0,skill:'megillah-walled-city-map',competency:'sourceReasoning',feedback:'Good. Keep category, anchor, and assigned date together.'},
{short:'Locate the exception',mode:'COMMUNITY ACCOMMODATION',title:'Villages move to an assembly day',ref:'Megillah 2a',hebrew:'אלא שהכפרים מקדימין ליום הכניסה',translation:'Rather, the villages advance to the day of assembly.',prompt:'What kind of move is this?',answers:['A stated accommodation for one community within the Mishnah’s overall schedule.','A rejection of all dates in the Mishnah.','A personal suggestion without communal context.'],correct:0,skill:'megillah-village-accommodation',competency:'argument',feedback:'Right. The exception is structured: a named community, a particular kind of day, and a place in the larger schedule.'},
{short:'Ask the question',mode:'GEMARA QUESTION',title:'Gemara asks about the early date',ref:'Megillah 2a',hebrew:'מגילה נקראת באחד עשר, מנלן?',translation:'The Megillah is read on the eleventh—where do we derive this?',prompt:'What is the Gemara asking for?',answers:['Why the early eleventh-day reading belongs within the Mishnah’s stated window.','Whether the Megillah exists.','A way to ignore the Mishnah’s schedule.'],correct:0,skill:'megillah-early-reading-question',competency:'sourceReasoning',feedback:'Exactly. The Gemara targets the exceptional early reading, not the entire Mishnah.'},
{short:'Read the reason',mode:'FUNCTIONAL ANSWER',title:'Flexibility is connected to shared provision',ref:'Megillah 2a',hebrew:'כדי שיספקו מים ומזון לאחיהם שבכרכין',translation:'So that they could supply water and food to their brothers in the cities.',prompt:'What does this reason show about the earlier reading?',answers:['The accommodation is tied to a practical relationship between villages and cities.','The early date makes the observance less important.','The schedule has no connection to communal life.'],correct:0,skill:'megillah-community-function',competency:'argument',feedback:'Right. The Gemara explains the date through an ordinary communal function.'},
{short:'Transfer the map',mode:'INDEPENDENT READ',title:'Map a flexible public rule',ref:'Megillah source-transfer checkpoint',hebrew:'זמן · מקום · קהילה · צורך',translation:'Time · place · community · need.',independent:true,prompt:'How should you first read a new source with a main rule and a special schedule for one group?',answers:['Name the default schedule, identify the community exception, and ask what need or function explains it.','Assume the exception erases the main rule.','Treat the source as individual advice.'],correct:0,skill:'megillah-independent-map',competency:'sourceReasoning',feedback:'You can now read a public schedule as a map of categories, accommodations, and stated reasons.'},
{short:'Choose the move',mode:'SOURCE CHECK',title:'Recall the Gemara’s focus',ref:'Megillah 2a',hebrew:'מנלן?',translation:'From where do we derive this?',independent:true,prompt:'What does this question ask a learner to seek?',answers:['The basis or explanation for a specific feature the source has just stated.','The easiest date to choose today.','A reason to stop mapping the Mishnah.'],correct:0,skill:'megillah-source-question',competency:'translation',feedback:'Good. The question directs attention back to the source feature that needs grounding.'}
]};
// Near-misses distinguish schedule, category, and explanation instead of signaling by length.
const megillahSteps=window.SederCourse.steps;
megillahSteps[0].answers=['The source establishes a bounded reading window whose different dates will need explanation.','The source names several dates but leaves each community free to choose any date without a category.','The source lists a bounded set of dates while treating them as separate observances rather than one schedule.'];
megillahSteps[1].answers=['It marks that the range is deliberate and bounded, not an open-ended choice.','It requires every community to read on the same date, regardless of the categories the Mishnah names.','It makes the range optional, so no date needs a source-based explanation or communal context.'];

// [rebalance] distractor lengths evened so the correct answer is not the longest option
window.SederCourse.steps[2].answers[1]="Only the single number fifteen and nothing else at all that surrounds it.";
window.SederCourse.steps[2].answers[2]="A modern-day binding ruling that applies to every walled city today.";
window.SederCourse.steps[3].answers[1]="A flat rejection of every single one of the dates the Mishnah has listed.";
window.SederCourse.steps[3].answers[2]="A merely personal suggestion offered without any communal context at all.";
window.SederCourse.steps[4].answers[1]="Whether the Megillah even exists as a text in the very first place.";
window.SederCourse.steps[4].answers[2]="A convenient way to simply ignore the Mishnah's stated schedule entirely.";
window.SederCourse.steps[5].answers[1]="The early reading date somehow makes the whole observance less important.";
window.SederCourse.steps[5].answers[2]="The schedule has no real connection to communal life of any kind at all.";
window.SederCourse.steps[6].answers[1]="Assume that the stated exception simply erases the main rule it was carved out of.";
window.SederCourse.steps[6].answers[2]="Treat the source as though it were a piece of individual, personal advice.";
window.SederCourse.steps[7].answers[1]="Whichever one of the dates happens to be the easiest to choose today.";
window.SederCourse.steps[7].answers[2]="A good enough reason to simply stop mapping the rest of the Mishnah.";
