window.SederCourse={stage:'meilah-tractate-arc',completeTitle:'You can now distinguish misuse, awareness, and restitution in consecrated property.',completeCopy:'You tracked how sacred status persists, how inadvertent and intentional misuse differ, and how restitution responds to the breach. Continue into the Meilah source workspace.',nextUrl:'lab.html?tractate=meilah',nextLabel:'Open the Meilah source workspace',steps:[
{short:'Locate the breach',mode:'CASE ORIENTATION',title:'Using what is not yours',ref:'Mishnah Meilah 1:1',hebrew:'meilah · hekdesh · shogeg',translation:'misuse · consecrated property · inadvertence',prompt:'What pressure does the opening case create?',answers:['It asks what happens when someone derives benefit from property whose sacred status still governs it.','It says sacred property becomes ordinary once someone touches it.','It treats every use as intentional theft.'],correct:0,skill:'meilah-misuse-case',competency:'recognition',feedback:'Right. Meilah begins with benefit from consecrated property and asks what legal breach follows.'},
{short:'Preserve sanctity',mode:'LEGAL CATEGORY',title:'Disqualification does not erase holiness',ref:'Mishnah Meilah 1:1',hebrew:'kodesh · pasul · kedushah',translation:'sacred · disqualified · sanctity',prompt:'What should a reader keep distinct?',answers:['A disqualified offering can remain sacred; validity and sanctity are separate legal questions.','Once an offering is disqualified, every sacred status disappears.','Sanctity is only a description of ritual quality.'],correct:0,skill:'meilah-sanctity-validity',competency:'sourceReasoning',feedback:'Good. Meilah requires the reader to preserve sanctity even when an offering is no longer valid for its original use.'},
{short:'Track awareness',mode:'FACT PATTERN',title:'Accident and intention',ref:'Meilah 2a',hebrew:'shogeg · mezid · yedi’ah',translation:'inadvertence · deliberate act · knowledge',prompt:'Why does the source track what the person knew?',answers:['Awareness separates inadvertent misuse, with its prescribed liability, from deliberate misuse with a different legal path.','Knowledge never changes the consequence of using sacred property.','Calling an act accidental makes the mental state irrelevant.'],correct:0,skill:'meilah-awareness-intent',competency:'sourceReasoning',feedback:'Exactly. Meilah makes knowledge a legal fact: inadvertence and deliberate misuse cannot be collapsed.'},
{short:'Separate effect',mode:'DISTINCTION MAP',title:'Benefit is not ownership',ref:'Meilah source map',hebrew:'hanaah · reshut · hekdesh',translation:'benefit · possession · consecrated property',prompt:'What distinction should remain visible?',answers:['Receiving benefit can trigger meilah even though the property never becomes ordinary private ownership.','Any benefit automatically transfers ownership from the sacred treasury.','Only physical theft can count as misuse.'],correct:0,skill:'meilah-benefit-ownership',competency:'argument',feedback:'Right. The legal issue is unauthorized benefit, not a simple transfer of ownership.'},
{short:'Find the source',mode:'GEMARA QUESTION',title:'Why does restitution follow?',ref:'Meilah 2a',hebrew:'mai taama · asham · chamesh',translation:'what is the reason · guilt-offering · fifth',prompt:'What does a Gemara source-question invite here?',answers:['Ask which verse makes restitution and the added fifth responsive to the sacred breach.','Replace the verse with a general rule about property damage.','Ignore the wording because restitution is only a practical custom.'],correct:0,skill:'meilah-proof-restitution',competency:'argument',feedback:'Good. The Gemara presses for the textual basis of returning value and adding the prescribed fifth.'},
{short:'Test the scope',mode:'SOURCE MAP',title:'What counts as benefit?',ref:'Meilah 3a',hebrew:'shiur · hanaah · davar sheyesh bo mamash',translation:'measure · benefit · tangible object',prompt:'What should a reader test after finding the rule?',answers:['Which measurable benefit and conditions make the misuse liable, and which cases remain outside the rule.','Whether every contact with sacred property creates identical liability.','Whether the value or context of the benefit can be ignored.'],correct:0,skill:'meilah-scope-conditions',competency:'argument',feedback:'Yes. Scope work asks what benefit occurred, whether it reaches the measure, and which conditions qualify the rule.'},
{short:'Keep the boundary',mode:'RESPONSIBLE LEARNING',title:'Historical sacred-property categories',ref:'Jewish Learning Academy Meilah boundary',hebrew:'lilmod · lehavin · lishol',translation:'to learn · to understand · to ask',prompt:'What is the responsible use of these sources?',answers:['Study their categories and reasoning as historical textual literacy, not as current Temple-treasury procedure.','Treat the ancient restitution system as a present-day ritual instruction.','Avoid the legal reasoning because the Temple setting is historical.'],correct:0,skill:'meilah-learning-boundary',competency:'sourceReasoning',feedback:'Serious study honors the precision of the source while distinguishing historical Temple law from present practice.'},
{short:'Transfer',mode:'SOURCE CHECK',title:'Map misuse with care',ref:'Meilah transfer checkpoint',hebrew:'maaseh · yedi’ah · hanaah · hashavah',translation:'act · knowledge · benefit · restitution',independent:true,prompt:'What is the best first map for a new Meilah case?',answers:['Name the sacred property, identify the benefit and awareness, then determine liability, restitution, and the boundary.','Choose restitution first and infer whether benefit occurred afterward.','Treat inadvertent and intentional misuse as interchangeable.'],correct:0,skill:'meilah-independent-map',competency:'sourceReasoning',feedback:'You can now read Meilah by tracking status, benefit, awareness, restitution, and boundary in order.'}]};
// [rebalance] keep distractors plausible without making the correct answer the longest option
window.SederCourse.steps[0].answers[1]="It says sacred property becomes ordinary once someone touches it, so the sacred status no longer matters to the case.";
window.SederCourse.steps[0].answers[2]="It treats every use as intentional theft, without distinguishing benefit, sacred status, or the person’s awareness.";
window.SederCourse.steps[1].answers[1]="Once an offering is disqualified, every sacred status disappears, so invalidity and loss of sanctity are the same legal conclusion.";
window.SederCourse.steps[1].answers[2]="Sanctity is only a description of ritual quality, not a status that can remain when an offering is no longer valid.";
window.SederCourse.steps[2].answers[1]="Knowledge never changes the consequence of using sacred property, even when the source distinguishes an inadvertent act from a deliberate one.";
window.SederCourse.steps[2].answers[2]="Calling an act accidental makes the mental state irrelevant, because every form of misuse follows the same legal path regardless of awareness.";
window.SederCourse.steps[3].answers[1]="Any benefit automatically transfers ownership from the sacred treasury, so benefit and possession are identical legal effects.";
window.SederCourse.steps[3].answers[2]="Only physical theft can count as misuse, because receiving benefit without taking possession cannot matter to the source.";
