window.SederCourse={stage:'niddah-tractate-arc',completeTitle:'You can now hold a three-way dispute without flattening it.',completeCopy:'You traced a genuine three-way Tannaitic dispute about how far back uncertainty reaches, held all three positions without collapsing them into one, connected a separate presumption correctly to its real source, and kept the line between careful study and practical guidance. These skills carry into any tractate organized around a live machloket.',nextUrl:'lab.html?tractate=niddah',nextLabel:'Practice on the Niddah working Daf',steps:[
{short:'Read the opening position',mode:'CASE ORIENTATION',title:'A tractate can open with a dispute',ref:'Mishnah Niddah 1:1',hebrew:'שַׁמַּאי אוֹמֵר דַּיָּהּ שְׁעָתָהּ',translation:'Shammai says: her time suffices.',prompt:'What does it mean that Niddah opens with a named position rather than an agreed rule?',answers:['The tractate begins in the middle of a live disagreement about how far back a period of uncertainty should reach.','The Mishnah is quoting Shammai only to reject him without discussion.','There is no real disagreement; this is simply the accepted rule.'],correct:0,skill:'niddah-opening-position',competency:'recognition',feedback:'Right. Opening with “Shammai says” signals a dispute the Mishnah expects you to track, not a settled ruling.'},
{short:'Find the counter-position',mode:'COMPARISON',title:'Hillel answers differently',ref:'Mishnah Niddah 1:1',hebrew:'וּבֵית הִלֵּל אוֹמְרִים מִפְּקִידָה לִפְקִידָה',translation:'And Beit Hillel say: from examination to examination.',prompt:'How does Hillel’s position differ in structure from Shammai’s?',answers:['Shammai measures uncertainty from the moment of discovery forward; Hillel measures it backward to the last time she checked, however long ago that was.','Hillel agrees completely with Shammai but uses different words.','Hillel’s position removes the concept of uncertainty entirely.'],correct:0,skill:'niddah-counter-position',competency:'argument',feedback:'Exactly. Two real positions, calculating the same uncertainty from two different reference points — a genuine, recorded machloket.'},
{short:'Find the middle path',mode:'COMPARISON',title:'A third position, not just a vote',ref:'Mishnah Niddah 1:1',hebrew:'וַחֲכָמִים אוֹמְרִים … מֵעֵת לְעֵת מְמַעֵט עַל יַד מִפְּקִידָה לִפְקִידָה',translation:'And the Sages say: a twenty-four hour span reduces the count compared to from-examination-to-examination.',prompt:'What kind of position do the Sages take here?',answers:['A structured middle position that uses whichever of the two measures is shorter, rather than simply picking one side.','An exact repetition of Beit Hillel’s position.','A rejection of the entire question as unanswerable.'],correct:0,skill:'niddah-middle-position',competency:'argument',feedback:'Good. A third Tannaitic voice is not always a compromise vote — here it constructs its own rule from parts of both earlier positions.'},
{short:'Hold three positions without flattening',mode:'RESPONSIBLE READING',title:'Three real positions, not one blurred answer',ref:'Mishnah Niddah 1:1',hebrew:'שַׁמַּאי · הִלֵּל · חֲכָמִים',translation:'Shammai · Hillel · the Sages.',prompt:'What does a disciplined reading of this three-way dispute require?',answers:['Naming what each position actually measures, without assuming one obviously wins or that all three are secretly saying the same thing.','Picking whichever position sounds simplest and ignoring the other two.','Concluding that Tannaitic disputes are never worth tracking in detail.'],correct:0,skill:'niddah-hold-three',competency:'argument',feedback:'This is what careful machloket-reading looks like: three distinct measuring points, each preserved on its own terms.'},
{short:'Meet a separate principle',mode:'CONCEPT',title:'A presumption from later in the tractate',ref:'Mishnah Niddah 2:4',hebrew:'כָּל הַנָּשִׁים בְּחֶזְקַת טָהֳרָה לְבַעֲלֵיהֶן',translation:'All women are presumed to be in a state of purity for their husbands.',prompt:'This is a different Mishnah from the opening dispute. What should a careful reader do before connecting the two?',answers:['Check the actual citation and confirm what this presumption applies to before assuming it settles the earlier dispute.','Assume both lines are the same Mishnah since they discuss the same tractate.','Ignore the citation, since exact chapter and verse never matter.'],correct:0,skill:'niddah-presumption-source',competency:'sourceReasoning',feedback:'Good instinct. This principle comes from Mishnah Niddah 2:4, not the opening Mishnah — precise citation is part of responsible source work.'},
{short:'Connect presumption to dispute',mode:'DISTINCTION',title:'A presumption still needs a measuring rule',ref:'Mishnah Niddah 1:1 · 2:4',hebrew:'דַּיָּהּ שְׁעָתָהּ · בְּחֶזְקַת טָהֳרָה',translation:'Her time suffices · presumed pure.',prompt:'How do the opening dispute and this later presumption relate?',answers:['The presumption tells you the default status; the opening dispute tells you how far back to recalculate that status once uncertainty arises.','The presumption makes the entire opening dispute irrelevant.','They contradict each other and cannot both be true.'],correct:0,skill:'niddah-connect-principle',competency:'argument',feedback:'Right. A general presumption and a specific measuring rule can operate together without collapsing into a single idea.'},
{short:'Keep the boundary',mode:'RESPONSIBLE LEARNING',title:'Sensitive material needs a clear line',ref:'Jewish Learning Academy learning boundary',hebrew:'לִלְמוֹד · לְהָבִין · לִשְׁאוֹל',translation:'To learn · to understand · to ask.',prompt:'Niddah addresses deeply personal and halakhically consequential material. What is Jewish Learning Academy’s appropriate role?',answers:['Support careful reading of the sugya’s structure and reasoning while directing any real personal question to a qualified rabbinic authority.','Use the Mishnah’s positions to answer a real personal question directly.','Avoid the tractate entirely because the subject is sensitive.'],correct:0,skill:'niddah-non-psak-boundary',competency:'sourceReasoning',feedback:'Right. A tractate this consequential can be studied seriously and responsibly without ever standing in for qualified guidance.'},
{short:'Transfer the habit',mode:'TRANSFER',title:'You have held a real machloket before',ref:'Sifra on Leviticus 19:18 · Genesis 5:1',hebrew:'כְּלָל גָּדוֹל · בְּדֶמוּת אֱלֹהִים',translation:'A great principle · in the likeness of God.',prompt:'You already learned to hold Rabbi Akiva’s and Ben Azzai’s positions without flattening one into the other. What does that habit add here?',answers:['A recorded machloket with named positions is not a problem to resolve quickly — it rewards tracking exactly what each side measures or claims.','Machlokot always have one obviously correct side that the other named sages simply missed.','Once one machloket is understood, all others in Shas work identically.'],correct:0,skill:'niddah-transfer',competency:'sourceReasoning',feedback:'The same discipline — preserve each position’s real claim — reads a values-dispute in Chassidus and a measuring-rule dispute in Niddah alike.'},
{short:'Independent read',mode:'INDEPENDENT READ',title:'Map the dispute on your own',ref:'Niddah 1:1 reading checkpoint',hebrew:'דַּיָּהּ שְׁעָתָהּ · מִפְּקִידָה לִפְקִידָה · מֵעֵת לְעֵת',translation:'Her time suffices · from examination to examination · a twenty-four hour span.',independent:true,prompt:'What is the first independent-reading move across these three fragments?',answers:['Name each position, identify exactly what point in time each one measures from, then compare them without merging them.','Pick whichever fragment is shortest and treat it as the ruling.','Assume all three fragments say the same thing in different words.'],correct:0,skill:'niddah-independent-map',competency:'sourceReasoning',feedback:'You can now enter a three-way measuring-rule dispute with a concrete map.'},
{short:'Type the meaning',mode:'PRODUCTION CHECK',title:'Recall, don’t just recognize',ref:'Mishnah Niddah 1:1',hebrew:'מִפְּקִידָה לִפְקִידָה',translation:'From examination to examination.',independent:true,typed:true,prompt:'Type the English meaning of this phrase in a few words.',acceptable:['from examination to examination','from checking to checking','from one examination to another','from inspection to inspection'],skill:'niddah-typed-recall',competency:'translation',feedback:'Typing an answer from memory is a stronger test of durable mastery than recognizing it among choices.'}
]};
// Alternatives protect the careful distinction among positions without using answer length as a cue.
const niddahSteps=window.SederCourse.steps;
niddahSteps[0].answers=['The tractate begins in the middle of a live disagreement about how far back a period of uncertainty should reach.','The Mishnah introduces Shammai’s words only to dismiss them before any other position can be considered.','The named position is the settled rule, so the reader need not track a dispute or its measuring point.'];
niddahSteps[1].answers=['Shammai measures uncertainty from the moment of discovery forward; Hillel measures it backward to the last time she checked, however long ago that was.','Hillel agrees with Shammai’s measuring point but supplies a different label for the same temporal rule.','Hillel removes uncertainty from the discussion, so no point in time needs to be measured at all.'];
niddahSteps[2].answers=['A structured middle position that uses whichever of the two measures is shorter, rather than simply picking one side.','An exact repetition of Beit Hillel’s position, expressed through a different calculation of the same interval.','A refusal to measure the uncertainty at all because the original question is treated as unanswerable.'];

// [rebalance] distractor lengths evened so the correct answer is not the longest option
window.SederCourse.steps[1].answers[2]="Hillel removes all uncertainty from the discussion, so that no point in time ever needs to be measured at all.";
window.SederCourse.steps[3].answers[1]="Picking out whichever one of the positions happens to sound simplest and quietly ignoring the other two.";
window.SederCourse.steps[3].answers[2]="Concluding that Tannaitic disputes like this one are simply never worth tracking in any real detail.";
window.SederCourse.steps[4].answers[1]="Assume that both of the lines must be the very same Mishnah, since they discuss the same tractate.";
window.SederCourse.steps[4].answers[2]="Ignore the citation entirely, on the assumption that exact chapter and verse never really matter.";
window.SederCourse.steps[5].answers[1]="The presumption simply makes the entire opening dispute irrelevant and altogether beside the point.";
window.SederCourse.steps[5].answers[2]="The two of them flatly contradict one another and so cannot possibly both be true at the same time.";
window.SederCourse.steps[6].answers[1]="Use the Mishnah's stated positions to try to answer a real, personal question directly and on one's own.";
window.SederCourse.steps[6].answers[2]="Avoid studying the tractate entirely, simply because its subject matter happens to be a sensitive one.";
window.SederCourse.steps[7].answers[1]="Machlokot always have one plainly correct side that all the other named sages involved simply missed.";
window.SederCourse.steps[7].answers[2]="Once a single machloket has been understood, all of the others across Shas work in an identical way.";
window.SederCourse.steps[8].answers[1]="Pick out whichever of the fragments happens to be the shortest and treat that one as the ruling.";
window.SederCourse.steps[8].answers[2]="Assume that all three of the fragments are really saying the same thing in slightly different words.";
