window.SederCourse={stage:'sanhedrin-tractate-arc',completeTitle:'You can read a repeated Mishnah phrase as a real Gemara question.',completeCopy:'You mapped a legal category and its examples, followed the Gemara’s challenge about apparent repetition, and distinguished a reading proposal from practical authority. These habits transfer whenever a source names both a broad class and specific cases.',nextUrl:'flagship-daf-workbench.html?tractate=sanhedrin',nextLabel:'Build the Sanhedrin source map',steps:[
{short:'Map the category',mode:'CASE ORIENTATION',title:'A Mishnah begins with a category',ref:'Mishnah Sanhedrin 1:1',hebrew:'דִּינֵי מָמוֹנוֹת בִּשְׁלֹשָׁה',translation:'Cases concerning monetary law are adjudicated by three.',prompt:'What does this first phrase give a reader?',answers:['A broad case category together with the court number the Mishnah assigns to it.','A personal instruction for resolving a present-day dispute.','A claim that every legal matter is identical.'],correct:0,skill:'sanhedrin-category-map',competency:'recognition',feedback:'Right. Begin by separating the field named from the number attached to it.'},
{short:'Read the examples',mode:'CASE ORIENTATION',title:'The Mishnah specifies cases',ref:'Mishnah Sanhedrin 1:1',hebrew:'גְּזֵילוֹת וַחֲבָלוֹת בִּשְׁלֹשָׁה',translation:'Cases of robbery and personal injury are adjudicated by three.',prompt:'How should a careful reader relate this phrase to the category that came before it?',answers:['As named cases that appear to sit inside the broader monetary-law category, with the same stated number.','As proof that robbery and injury cannot be monetary cases.','As a new personal ruling that replaces the Mishnah’s opening phrase.'],correct:0,skill:'sanhedrin-category-example',competency:'sourceReasoning',feedback:'Good. The category and the named cases are not yet the same kind of statement; their relation is exactly what the Gemara will probe.'},
{short:'Notice the pressure',mode:'QUESTION SIGNAL',title:'A repeated detail can create a question',ref:'Sanhedrin 2a',hebrew:'אַטּוּ גְּזֵילוֹת וַחֲבָלוֹת לָאו דִּינֵי מָמוֹנוֹת נִינְהוּ?',translation:'Are robbery and personal-injury cases not monetary-law cases?',prompt:'What pressure does the Gemara put on the Mishnah’s wording?',answers:['If the named cases already belong to the broad category, why does the Mishnah specify them separately?','Whether robbery and injury are ordinary Hebrew words.','Whether a learner may decide a court case from this page.'],correct:0,skill:'sanhedrin-wording-question',competency:'argument',feedback:'Exactly. The Gemara assumes deliberate wording and asks what the added specification accomplishes.'},
{short:'Name the question',mode:'GEMARA MOVE',title:'The question is about wording, not the result',ref:'Sanhedrin 2a',hebrew:'לָאו דִּינֵי מָמוֹנוֹת נִינְהוּ?',translation:'Are they not monetary-law cases?',prompt:'Which paraphrase preserves the Gemara’s actual question?',answers:['Why list robbery and injury separately if they are already cases of monetary law?','Are robbery and injury ever important subjects?','Which litigant should win a robbery case today?'],correct:0,skill:'sanhedrin-question-paraphrase',competency:'argument',feedback:'Right. Keep a textual question about specification separate from any live legal conclusion.'},
{short:'Meet a reading proposal',mode:'EXPLANATION',title:'The Gemara proposes a way to read the Mishnah',ref:'Sanhedrin 2a',hebrew:'מָה הֵן קָתָנֵי, מָה הֵן דִּינֵי מָמוֹנוֹת? גְּזֵילוֹת וַחֲבָלוֹת',translation:'It teaches: what are these monetary-law cases? Robbery and personal-injury cases.',prompt:'What does this proposal do to the Mishnah’s two phrases?',answers:['It reads the second phrase as specifying which cases the first category is talking about.','It erases the first phrase as meaningless.','It turns the Mishnah into an instruction for a modern court.'],correct:0,skill:'sanhedrin-reading-proposal',competency:'sourceReasoning',feedback:'Good. “What are these?” is a reading proposal: a category followed by its specification.'},
{short:'Keep a limit visible',mode:'DISTINCTION',title:'A specification can narrow a category',ref:'Sanhedrin 2a',hebrew:'אֲבָל הוֹדָאוֹת וְהַלְוָאוֹת לָא',translation:'But admissions and loans, no.',prompt:'What reading habit does this limit reinforce?',answers:['A broad label may be clarified or narrowed by the cases a source explicitly specifies.','A category label always includes every imaginable case without qualification.','A learner should infer a practical legal rule without further study.'],correct:0,skill:'sanhedrin-category-limit',competency:'argument',feedback:'Exactly. A close reader tracks both what a category includes and the limits a source itself marks.'},
{short:'Trace a source layer',mode:'SOURCE LAYER',title:'The Gemara grounds a case in Torah language',ref:'Exodus 22:7 · Sanhedrin 2a',hebrew:'וְנִקְרַב בַּעַל הַבַּיִת אֶל הָאֱלֹהִים',translation:'The owner of the house shall come near the court.',prompt:'What should a learner ask when the Gemara brings a Torah phrase into its explanation?',answers:['What role the verse is playing in the Gemara’s account of this category, before claiming more than the source says.','Which current dispute the verse settles immediately.','Whether the verse makes the Mishnah unnecessary.'],correct:0,skill:'sanhedrin-source-layer',competency:'sourceReasoning',feedback:'Right. Source tracing asks how a cited text functions in the argument; it is not a shortcut to practical judgment.'},
{short:'Keep the boundary',mode:'RESPONSIBLE LEARNING',title:'Court sources require a firm boundary',ref:'Seder learning boundary',hebrew:'לִלְמוֹד · לְהָבִין · לִשְׁאוֹל',translation:'To learn · to understand · to ask.',prompt:'What is Seder’s responsible role when studying Sanhedrin?',answers:['Teach the Mishnah and Gemara’s textual structure while directing real legal questions to qualified authorities and appropriate institutions.','Use an ancient court text to decide a learner’s dispute.','Avoid all court texts because they can never be studied responsibly.'],correct:0,skill:'sanhedrin-study-boundary',competency:'sourceReasoning',feedback:'Correct. The seriousness of the material calls for more careful study, not simulated legal authority.'},
{short:'Transfer the move',mode:'TRANSFER',title:'A category and its cases appear elsewhere',ref:'Mishnah Bava Kamma 1:1',hebrew:'אַרְבָּעָה אָבוֹת נְזִיקִין',translation:'There are four primary categories of damage.',prompt:'What can the Sanhedrin reading habit help you do in this new Mishnah?',answers:['Ask how the named categories, examples, and any shared principle relate before treating the list as a flat set of facts.','Assume every category-list means exactly what Sanhedrin means.','Skip the source because categories are only vocabulary lists.'],correct:0,skill:'sanhedrin-transfer-map',competency:'argument',feedback:'Good transfer. Structural habits travel, while each new source still needs its own close reading.'},
{short:'Recall the phrase',mode:'PRODUCTION CHECK',title:'Recall, don’t just recognize',ref:'Sanhedrin 2a',hebrew:'מָה הֵן',translation:'What are these?',independent:true,typed:true,prompt:'Type the English meaning of מָה הֵן in a few words.',acceptable:['what are these','what are they'],skill:'sanhedrin-typed-recall',competency:'translation',feedback:'You recalled the phrase that introduces the Gemara’s category-and-specification reading.'}
]};
// Alternatives preserve the distinction between category, court number, and practical authority.
const sanhedrinSteps=window.SederCourse.steps;
sanhedrinSteps[0].answers=['A broad case category together with the court number the Mishnah assigns to it.','A personal instruction for resolving a present-day dispute without locating the Mishnah’s category.','A claim that every legal matter is identical, regardless of category or assigned court number.'];
