window.SederCourse={stage:'shabbat-tractate-arc',completeTitle:'You can now enter a case-based legal sugya.',completeCopy:'You identified a counted Mishnah, domains, action, category, distinction, and source map. Continue through the complete Shabbat mastery loop.',nextUrl:'tractate-mastery.html?tractate=shabbat',nextLabel:'Open the Shabbat mastery loop',steps:[
{short:'Counted Mishnah',mode:'CASE ORIENTATION',title:'A number opens a legal field',ref:'Mishnah Shabbat 1:1',hebrew:'יְצִיאוֹת הַשַּׁבָּת שְׁתַּיִם שֶׁהֵן אַרְבַּע',translation:'The acts of carrying out on Shabbat are two that are four.',prompt:'What should this opening make a learner expect?',answers:['Basic cases and related extensions that require careful sorting.','One simple story with no distinctions.','A final ruling with no examples.'],correct:0,skill:'shabbat-counted-mishnah',competency:'recognition',feedback:'A counted Mishnah signals that the learner must track categories and cases.'},
{short:'Domains',mode:'CASE ORIENTATION',title:'Location changes a case',ref:'Mishnah Shabbat 1:1',hebrew:'בִּפְנִים · בַּחוּץ',translation:'Inside · outside.',prompt:'Why do these words matter?',answers:['They distinguish domains that shape the legal case.','They name two historical figures.','They conclude the discussion.'],correct:0,skill:'shabbat-domains',competency:'translation',feedback:'Legal reasoning often begins by locating where an action occurs.'},
{short:'Action',mode:'CASE MAP',title:'Find what each person does',ref:'Mishnah Shabbat 1:1',hebrew:'הֶעָנִי עוֹמֵד בַּחוּץ וּבַעַל הַבַּיִת בִּפְנִים',translation:'The poor person stands outside and the homeowner stands inside.',prompt:'What must a learner map before deciding the outcome?',answers:['Who acts, where each person stands, and what moves between domains.','Which person is more sympathetic.','A final result without looking at the case.'],correct:0,skill:'shabbat-case-map',competency:'sourceReasoning',feedback:'Good. Case mapping keeps legal reasoning concrete.'},
{short:'Category',mode:'LEGAL CATEGORY',title:'A case points toward a category',ref:'Mishnah Shabbat 1:1',hebrew:'הוֹצָאָה',translation:'Carrying out / transfer.',prompt:'What is the learning task after seeing several cases?',answers:['Ask what shared category organizes them and where their differences matter.','Memorize the people without the action.','Treat every case as unrelated.'],correct:0,skill:'shabbat-category',competency:'argument',feedback:'A category makes several cases intelligible as part of one legal field.'},
{short:'Distinction',mode:'DISTINCTION',title:'Similar cases can differ',ref:'Shabbat case reasoning',hebrew:'הָא בִּפְנִים · הָא בַּחוּץ',translation:'This is inside · that is outside.',prompt:'What kind of reasoning move is this?',answers:['A distinction that explains why superficially similar cases may differ.','A source proof from a verse.','A final conclusion with no analysis.'],correct:0,skill:'shabbat-distinction',competency:'argument',feedback:'Right. Legal mastery depends on seeing the feature that changes the category.'},
{short:'Source and practice',mode:'SOURCE CHAIN',title:'Study does not become a personal ruling automatically',ref:'Seder Shabbat boundary',hebrew:'לִלְמוֹד · לְהָבִין · לִשְׁאוֹל',translation:'To learn · to understand · to ask.',prompt:'What is the responsible use of this learning?',answers:['Understand source structure while bringing personal practical questions to qualified guidance.','Treat every practice screen as individual psak.','Avoid primary sources entirely.'],correct:0,skill:'shabbat-learning-boundary',competency:'sourceReasoning',feedback:'Serious learning includes knowing the boundary between text study and personal decision.'},
{short:'A new topic begins',mode:'CASE ORIENTATION',title:'One tractate, more than one subject',ref:'Mishnah Shabbat 1:2',hebrew:'לֹא יֵשֵׁב אָדָם לִפְנֵי הַסַּפָּר סָמוּךְ לַמִּנְחָה',translation:'A person should not sit before the barber close to the time of Mincha.',prompt:'Mishnah 1:1 discussed domains and transfer. What does the very next Mishnah do?',answers:['Move to a completely different topic — timing restrictions before the afternoon prayer — while remaining in the same tractate.','Continue explaining the exact same domains case in more depth.','Repeat the previous Mishnah word for word.'],correct:0,skill:'shabbat-new-topic',competency:'recognition',feedback:'Right. A tractate is organized by broad subject, not one continuous argument — expect real topic shifts between Mishnayot.'},
{short:'Find the reason',mode:'SOURCE LAYER',title:'A timing rule has its own concern',ref:'Shabbat 9b',hebrew:'שֶׁמָּא יִשְׁכַּח וְלֹא יִתְפַּלֵּל',translation:'Lest he forget and not pray.',prompt:'What kind of concern explains this pre-Mincha restriction?',answers:['A concern that an absorbing activity could cause someone to miss a fixed prayer time entirely.','A concern about the barber’s profession.','A concern that has nothing to do with prayer.'],correct:0,skill:'shabbat-timing-reason',competency:'sourceReasoning',feedback:'Good. Even a rule that looks unrelated to prayer can turn out to be a safeguard built around it.'},
{short:'Transfer',mode:'TRANSFER',title:'Move from Shabbat to Eruvin',ref:'Mishnah Eruvin 1:1',hebrew:'מָבוֹי שֶׁהוּא גָבוֹהַּ',translation:'An alleyway that is high.',prompt:'What Shabbat skill transfers to this new source?',answers:['Map the physical case and ask which feature creates the legal category.','Assume every tractate uses identical vocabulary.','Ignore the concrete details.'],correct:0,skill:'shabbat-transfer',competency:'sourceReasoning',feedback:'You can carry case mapping into a new legal world.'},
{short:'Independent case map',mode:'INDEPENDENT READ',title:'Read the case before the ruling',ref:'Shabbat 2a reading checkpoint',hebrew:'עָנִי · בַּעַל הַבַּיִת · בִּפְנִים · בַּחוּץ',translation:'Poor person · homeowner · inside · outside.',independent:true,prompt:'What is the first independent-reading move?',answers:['Map people, domains, action, and relation before deciding what category is at stake.','Guess the ruling from one word.','Skip the case and look for a later conclusion.'],correct:0,skill:'shabbat-independent-map',competency:'sourceReasoning',feedback:'You can now enter a case-based sugya with a concrete map.'},
{short:'Type the map',mode:'PRODUCTION CHECK',title:'Recall the source roles',ref:'Mishnah Shabbat 1:1',hebrew:'עָנִי · בַּעַל הַבַּיִת',translation:'Poor person · homeowner.',typed:true,independent:true,prompt:'Type the two people whose positions organize the opening case.',acceptable:['poor person and homeowner','the poor person and the homeowner','poor man and homeowner','the poor man and the homeowner'],skill:'shabbat-typed-recall',competency:'translation',feedback:'A source map becomes durable when you can reconstruct its essential actors without answer choices.'}
]};
