window.SederCourse={stage:'sotah-tractate-arc',completeTitle:'You can now read Sotah through testimony, procedure, and evidentiary limits.',completeCopy:'You traced how a warning, witnesses, ritual procedure, and uncertainty interact in Sotah while keeping historical study distinct from present-day advice. Continue into the Sotah source workspace.',nextUrl:'lab.html?tractate=sotah',nextLabel:'Open the Sotah source workspace',steps:[
{short:'Count the witnesses',mode:'EVIDENCE ORIENTATION',title:'A warning is not yet proof',ref:'Mishnah Sotah 1:1',hebrew:'קִנּוּי עַל פִּי שְׁנַיִם',translation:'A warning is made in the presence of two witnesses.',prompt:'What does the opening requirement establish?',answers:['The warning is a formal evidentiary act requiring two witnesses, not merely a private suspicion.','Any rumor automatically begins the ritual.','The witnesses decide the outcome before the procedure begins.'],correct:0,skill:'sotah-two-witness-warning',competency:'recognition',feedback:'Right. Sotah begins by specifying the evidence needed even to initiate the formal process.'},
{short:'Separate warning from seclusion',mode:'PROCEDURE MAP',title:'Two stages carry different work',ref:'Mishnah Sotah 1:1',hebrew:'קִנּוּי וּסְתִירָה',translation:'Warning and seclusion.',prompt:'Why keep these stages distinct?',answers:['The warning creates a formal condition, while subsequent seclusion supplies a different procedural fact.','The two terms are interchangeable names for one accusation.','Seclusion alone proves guilt without any prior warning.'],correct:0,skill:'sotah-procedure-stages',competency:'sourceReasoning',feedback:'Exactly. The Mishnah builds a sequence; each stage has its own evidentiary role.'},
{short:'Test testimony',mode:'TESTIMONY LIMITS',title:'What can witnesses establish?',ref:'Numbers 5:13',hebrew:'וְעֵד אֵין בָּהּ',translation:'There is no witness against her.',prompt:'What is the careful question to ask about testimony?',answers:['Identify what the witnesses saw and which procedural condition that observation can establish.','Treat every witness statement as proof of the entire underlying event.','Ignore the witness requirement once the ritual is mentioned.'],correct:0,skill:'sotah-testimony-scope',competency:'argument',feedback:'Good. Evidence has scope: a witness can establish a condition without supplying every conclusion.'},
{short:'Read the ritual',mode:'RITUAL PROCEDURE',title:'The ritual has ordered steps',ref:'Mishnah Sotah 2:2-3',hebrew:'מַיִם הַמָּרִים',translation:'The bitter waters.',prompt:'Why does the ritual sequence matter for reading the source?',answers:['The ordered acts and materials define the textual procedure; they are not interchangeable symbols.','Any meaningful substitute preserves the same legal procedure.','The ritual details are later decoration with no interpretive force.'],correct:0,skill:'sotah-ritual-sequence',competency:'sourceReasoning',feedback:'Yes. Sotah trains attention to how material and sequence carry the procedure.'},
{short:'Ask about uncertainty',mode:'GEMARA QUESTION',title:'What if the evidence is incomplete?',ref:'Sotah 2a',hebrew:'מַאי טַעְמָא',translation:'What is the reason?',prompt:'What kind of problem does the Gemara raise around uncertain evidence?',answers:['It asks how the ritual framework responds when the required facts or testimony do not line up cleanly.','It assumes uncertainty has no effect on the process.','It replaces the source with a modern intuition about trust.'],correct:0,skill:'sotah-uncertainty-question',competency:'argument',feedback:'Right. The Gemara makes evidentiary uncertainty an explicit question rather than silently resolving it.'},
{short:'Limit the inference',mode:'EVIDENTIARY REASONING',title:'Suspicion is not a verdict',ref:'Numbers 5:13-14',hebrew:'וְנִסְתְּרָה וְעֵד אֵין בָּהּ',translation:'She secluded herself and there is no witness.',prompt:'What boundary follows from the source?',answers:['Distinguish suspicion, witnessed conditions, and the ritual’s procedural result instead of treating them as identical.','A suspicion is enough to announce guilt publicly.','The absence of a witness proves the accusation false.'],correct:0,skill:'sotah-inference-limit',competency:'sourceReasoning',feedback:'Exactly. The text preserves uncertainty and channels it through a defined procedure.'},
{short:'Keep the boundary',mode:'HISTORICAL STUDY',title:'Sensitive law needs careful boundaries',ref:'Seder learning boundary',hebrew:'לִלְמוֹד · לְהָבִין · לֹא לִפְסוֹק',translation:'To learn · to understand · not to issue a ruling.',prompt:'What is Seder’s responsible stance?',answers:['Study testimony and ritual historically while directing any personal, pastoral, or legal concern to qualified authorities.','Apply the ancient procedure directly to a contemporary relationship.','Avoid the tractate because its subject is difficult.'],correct:0,skill:'sotah-historical-boundary',competency:'sourceReasoning',feedback:'Serious study can hold difficult sources with precision without pretending to replace guidance.'},
{short:'Transfer the map',mode:'INDEPENDENT READ',title:'Map a disputed evidentiary case',ref:'Sotah transfer checkpoint',hebrew:'הַתְרָאָה · עֵדִים · סְתִירָה · סָפֵק',translation:'Warning · witnesses · seclusion · uncertainty.',independent:true,prompt:'What is the best first map for an unfamiliar Sotah passage?',answers:['List the warning, witness requirement, subsequent condition, ritual step, and remaining uncertainty before drawing a conclusion.','Begin with a verdict based on the emotional plausibility of the story.','Treat every element as one undifferentiated accusation.'],correct:0,skill:'sotah-independent-map',competency:'sourceReasoning',feedback:'You can now read Sotah through evidence, procedure, uncertainty, and responsible boundaries.'}
]};
// Production/source checks: distractors are substantive near-misses, not short strawmen.
const sotahSteps=window.SederCourse.steps;
sotahSteps[0].answers[1]='A rumor or private suspicion automatically begins the ritual, even without the Mishnah\'s formal witness requirement.';
sotahSteps[0].answers[2]='The two witnesses decide the final outcome before warning, seclusion, or the later procedural stages have occurred.';
sotahSteps[1].answers[1]='The two terms are interchangeable names for one accusation, so the source does not require a sequence of distinct stages.';
sotahSteps[1].answers[2]='Seclusion alone establishes guilt, even when the prior warning and its formal conditions are absent.';
sotahSteps[2].answers[1]='Treat every witness statement as proof of the entire underlying event, rather than asking what condition that witness observed.';
sotahSteps[2].answers[2]='Ignore the witness requirement once the ritual is mentioned, since material procedure replaces evidentiary analysis.';
sotahSteps[3].answers[1]='Any meaningful substitute preserves the same legal procedure, even when the ordered materials and acts named by the Mishnah change.';
sotahSteps[3].answers[2]='The ritual details are later decoration with no interpretive force, so sequence and material distinctions can be set aside.';
sotahSteps[4].answers[1]='It assumes uncertainty has no effect on the process, because once suspicion exists the source treats every fact as settled.';
sotahSteps[4].answers[2]='It replaces the source with a modern intuition about trust instead of asking how the text handles incomplete evidence.';
sotahSteps[5].answers[1]='A suspicion is enough to announce guilt publicly, even before witnesses and the source\'s defined procedure establish anything further.';
sotahSteps[5].answers[2]='The absence of a witness proves the accusation false, rather than preserving an unresolved condition for the procedure to address.';
sotahSteps[6].answers[1]='Apply the ancient procedure directly to a contemporary relationship, treating historical ritual law as immediate personal guidance.';
sotahSteps[6].answers[2]='Avoid the tractate because its subject is difficult, rather than studying its evidence categories with qualified guidance available.';
sotahSteps[7].answers[1]='Begin with a verdict based on the emotional plausibility of the story, before listing the warning, witnesses, conditions, and uncertainty.';
sotahSteps[7].answers[2]='Treat every element as one undifferentiated accusation, so that procedural stages and remaining uncertainty no longer matter.';
sotahSteps.push({short:'Choose the source move',mode:'SOURCE CHECK',title:'Produce the evidentiary reading move',ref:'Sotah 2a',hebrew:'ספק · עדים · סתירה',translation:'Uncertainty · witnesses · contradiction.',prompt:'Which account best explains the source-grounded reading move in this sugya?',answers:['Separate what each witness establishes from what remains uncertain, then follow the procedure the source itself defines.','Treat the presence of witnesses as a complete verdict, without checking what they actually establish or what procedure follows.','Replace the sugya\'s categories with a broad judgment about character, since uncertainty makes textual precision unnecessary.'],correct:0,skill:'sotah-source-check',competency:'sourceReasoning',feedback:'You produced the reading move: scope the evidence, preserve uncertainty, and follow the source\'s procedure rather than importing a verdict.'});
