const sources=[
{id:'berakhot-opening-map',ref:'BERAKHOT 2A',title:'The opening sugya',lines:[
{hebrew:'מֵאֵימָתַי קוֹרִין אֶת שְׁמַע בְּעַרְבִין?',translation:'From when do we recite Shema in the evenings?',kind:'Case / question',skill:'map-case-question',explanation:'The Mishnah opens the field with a practical timing question.'},
{hebrew:'תַּנָּא הֵיכָא קָאֵי דְּקָתָנֵי מֵאֵימָתַי?',translation:'What is the Mishnah addressing that it begins “From when?”',kind:'Context question',skill:'map-context-question',explanation:'The Gemara asks what prior source or problem gives the Mishnah’s opening its sense.'},
{hebrew:'תַּנָּא אַקְרָא קָאֵי, דִּכְתִיב: בְּשָׁכְבְּךָ וּבְקוּמֶךָ',translation:'The Mishnah relies on the verse: when you lie down and when you rise up.',kind:'Proof / answer',skill:'map-proof-answer',explanation:'The Gemara answers with a Torah verse that explains why evening comes before morning.'},
{hebrew:'מִשְׁנָה · שְׁאֵלָה · תְּשׁוּבָה מִן הַכָּתוּב',translation:'Mishnah · question · answer from a verse.',kind:'Conclusion',skill:'map-structure-conclusion',explanation:'The learner can now name the full movement of the opening sugya.'}]},
{id:'berakhot-proof-map',ref:'BERAKHOT 2B',title:'A word, an answer, and evidence',lines:[
{hebrew:'וּמַאי וְטָהֵר?',translation:'What does “and it is purified” mean?',kind:'Question',skill:'map-word-question',explanation:'The Gemara focuses on a specific word in a source.'},
{hebrew:'טָהֵר יוֹמָא',translation:'The day becomes clear.',kind:'Answer',skill:'map-proposed-answer',explanation:'An interpretation is proposed.'},
{hebrew:'סִימָן לַדָּבָר: צֵאת הַכּוֹכָבִים',translation:'A sign for the matter: the emergence of the stars.',kind:'Evidence',skill:'map-evidence',explanation:'A practical indicator helps clarify the proposed reading.'},
{hebrew:'וְאוֹמֵר',translation:'And it says.',kind:'Second proof',skill:'map-second-proof',explanation:'A second source is brought to strengthen or clarify the support.'}]},
{id:'dispute-map',ref:'GEMARA ARGUMENT TEMPLATE',title:'Challenge and distinction',lines:[
{hebrew:'תַּנְיָא',translation:'It was taught.',kind:'Cited teaching',skill:'map-baraita',explanation:'A teaching enters the discussion and must be read for its role.'},
{hebrew:'מֵיתִיבֵי',translation:'They raise an objection.',kind:'Objection',skill:'map-objection',explanation:'A source places pressure on a previous claim.'},
{hebrew:'לָא קַשְׁיָא',translation:'It is not difficult.',kind:'Distinction / response',skill:'map-distinction',explanation:'The Gemara signals that an apparent conflict can be resolved by distinguishing cases.'},
{hebrew:'שְׁמַע מִינָּהּ',translation:'Learn from it.',kind:'Conclusion',skill:'map-conclusion',explanation:'A conclusion is drawn from the argument that survived the pressure.'}]}
];
const choiceKinds=['Case / question','Context question','Question','Answer','Proof / answer','Evidence','Second proof','Cited teaching','Objection','Distinction / response','Conclusion'];let source=sources[Math.floor(Math.random()*sources.length)],index=0,answered=false,xp=0;const learnerId=Seder.currentLearnerId();const $=s=>document.querySelector(s);
$('#ref').textContent=source.ref;$('#sourceTitle').textContent=source.title;$('#legend').innerHTML=choiceKinds.map(k=>`<div class="legend-item">${k}</div>`).join('');
function render(){const active=source.lines[index];answered=false;$('#progress').textContent=`LINE ${index+1} OF ${source.lines.length}`;$('#bar').style.width=`${(index+1)/source.lines.length*100}%`;$('#lines').innerHTML=source.lines.map((line,i)=>`<article class="line ${i===index?'active':''} ${i<index?'mapped':''} ${i>index?'dim':''}">${i<index?`<small>${line.kind.toUpperCase()}</small>`:''}${line.hebrew}</article>`).join('');const options=[active.kind,...choiceKinds.filter(k=>k!==active.kind).sort(()=>Math.random()-.5).slice(0,4)].sort(()=>Math.random()-.5);$('#choices').innerHTML=options.map(kind=>`<button type="button" data-kind="${kind}">${kind}</button>`).join('');$('#reveal').hidden=true;document.querySelectorAll('#choices button').forEach(b=>b.addEventListener('click',()=>answer(b,b.dataset.kind===active.kind,active)))}
function answer(button,correct,line){if(answered)return;answered=true;document.querySelectorAll('#choices button').forEach(b=>b.disabled=true);button.classList.add(correct?'correct':'incorrect');$('#explanation').textContent=correct?line.explanation:`Not quite. ${line.explanation}`;$('#translation').textContent=line.translation;$('#reveal').hidden=false;Seder.api(`/api/learners/${learnerId}/events`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'source_annotation',skillId:line.skill,competency:['Case / question','Question','Context question'].includes(line.kind)?'argument':'sourceReasoning',correct,sourceContext:source.ref})}).then(r=>r.ok?r.json():null).then(l=>{if(l){xp=l.xp||xp;$('#xp').textContent=`${xp} XP`}}).catch(()=>{})}
$('#continue').addEventListener('click',()=>{if(!answered)return;if(index<source.lines.length-1){index++;render();return}Seder.api(`/api/learners/${learnerId}/events`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'stage_mastered',stageId:'source-annotation'})}).catch(()=>{});$('#choices').innerHTML='';$('#reveal').hidden=false;$('#explanation').textContent='You built a full argument map directly on the source. Revisit the map later in retrieval, then try another tractate passage.';$('#translation').textContent='Case / question → pressure → answer or evidence → conclusion.';$('#continue').textContent='Open independent reading →';$('#continue').onclick=()=>location.href='independent-read.html'});
Seder.api(`/api/learners/${learnerId}`).then(r=>r.ok?r.json():null).then(l=>{if(l){xp=l.xp||0;$('#xp').textContent=`${xp} XP`}}).catch(()=>{});render();
