window.SederCourse={stage:'sukkah-tractate-arc',completeTitle:'You can now read a measure-and-dispute sugya.',completeCopy:'You identified a structure, its measurement, the ruling that follows, a reason worth asking for, and a distinction that resolves an apparent dispute. These skills carry into Sukkah and every tractate organized around physical validity.',nextUrl:'lab.html?tractate=sukkah',nextLabel:'Open the Sukkah working Daf',steps:[
{short:'Find the measure',mode:'CASE ORIENTATION',title:'What is being measured?',ref:'Mishnah Sukkah 1:1',hebrew:'סֻכָּה שֶׁהִיא גְבוֹהָה לְמַעְלָה מֵעֶשְׂרִים אַמָּה',translation:'A sukkah that is higher than twenty cubits.',prompt:'What concrete feature does the Mishnah place before the reader?',answers:['The height of a sukkah.','The time of a festival meal.','The owner of a field.'],correct:0,skill:'sukkah-case-measure',competency:'recognition',feedback:'Good. Begin with the physical case before asking why the measure matters.'},
{short:'Read the measurement',mode:'CASE ORIENTATION',title:'A measurement is a boundary',ref:'Mishnah Sukkah 1:1',hebrew:'לְמַעְלָה מֵעֶשְׂרִים אַמָּה',translation:'Higher than twenty cubits.',prompt:'What job does this measurement phrase do in the sentence?',answers:['It defines the specific boundary condition the ruling depends on.','It names the builder of the sukkah.','It has no effect on the ruling that follows.'],correct:0,skill:'sukkah-measure-vocab',competency:'translation',feedback:'Right. A measurement is not decoration; it creates the boundary a Mishnah will reason about.'},
{short:'Name the structure',mode:'CASE MAP',title:'Know what you are measuring',ref:'Mishnah Sukkah 1:1',hebrew:'סֻכָּה',translation:'Sukkah / booth.',prompt:'Before applying any rule, what must a learner identify about the structure itself?',answers:['What physical feature is being measured and why that feature might matter halakhically.','The name of the festival the structure is used for.','Whether the structure has ever been rebuilt.'],correct:0,skill:'sukkah-structure-vocab',competency:'sourceReasoning',feedback:'Exactly. Naming the object precisely is the first step before reasoning about its validity.'},
{short:'Read the ruling',mode:'LEGAL CATEGORY',title:'What does the Mishnah say?',ref:'Mishnah Sukkah 1:1',hebrew:'פְּסוּלָה',translation:'It is invalid.',prompt:'What kind of statement is this, following the case just described?',answers:['A ruling about the described case.','A question about a verse.','A description of a custom.'],correct:0,skill:'sukkah-ruling',competency:'argument',feedback:'Exactly. The Mishnah’s short ruling gives the Gemara something precise to investigate.'},
{short:'Ask for the reason',mode:'REASON AND PROOF',title:'What comes next?',ref:'Sukkah reasoning habit',hebrew:'מַאי טַעְמָא',translation:'What is the reason?',prompt:'What productive question does this phrase invite after a bare ruling like פְּסוּלָה?',answers:['Why does this height affect the validity of the sukkah?','Who built the first sukkah?','Which word is easiest to translate?'],correct:0,skill:'sukkah-reason-proof',competency:'argument',feedback:'Right. A measurement becomes a Gemara question when the reader asks what principle explains it.'},
{short:'Read a distinction',mode:'DISPUTE',title:'Two sources, two cases',ref:'Sukkah case reasoning',hebrew:'הָא בְּ… הָא בְּ…',translation:'This is in one case; that is in another.',prompt:'If two sources seemed to disagree about a sukkah’s valid height, what move would a careful reader look for first?',answers:['A distinction showing the sources describe genuinely different cases, not a real disagreement.','A decision to discard one of the two sources.','A translation exercise unrelated to the disagreement.'],correct:0,skill:'sukkah-dispute',competency:'argument',feedback:'Good. Legal mastery depends on seeing the feature that changes the category.'},
{short:'Transfer the skeleton',mode:'TRANSFER',title:'Condition, then consequence',ref:'Mishnah grammar checkpoint',hebrew:'לְמַעְלָה מֵעֶשְׂרִים אַמָּה … פְּסוּלָה',translation:'Higher than twenty cubits … it is invalid.',prompt:'This is the same skeleton read earlier in Mishnah grammar. What should transfer from Sukkah to any new tractate?',answers:['A described case or measurement followed directly by its practical consequence.','A question followed by an unrelated answer.','Two facts placed together by coincidence.'],correct:0,skill:'sukkah-transfer',competency:'sourceReasoning',feedback:'Once you can name a sentence’s skeleton, it becomes visible across many different Mishnayot.'},
{short:'Independent case map',mode:'INDEPENDENT READ',title:'Map the case on your own',ref:'Sukkah 2a reading checkpoint',hebrew:'סֻכָּה · לְמַעְלָה מֵעֶשְׂרִים אַמָּה · פְּסוּלָה',translation:'Sukkah · higher than twenty cubits · it is invalid.',independent:true,prompt:'What is the first independent-reading move with this case?',answers:['Identify the structure, its measurement, and the ruling that follows before asking why.','Guess the ruling from the first word alone.','Assume the case has already been fully explained.'],correct:0,skill:'sukkah-independent-map',competency:'sourceReasoning',feedback:'You can now enter a measure-and-validity sugya with a concrete map.'},
{short:'Type the meaning',mode:'PRODUCTION CHECK',title:'Recall, don’t just recognize',ref:'Sukkah reasoning habit',hebrew:'מַאי טַעְמָא',translation:'What is the reason?',independent:true,typed:true,prompt:'Type the English meaning of this phrase in a few words.',acceptable:['what is the reason','what is the reason for it','what reason','what is the reason why'],skill:'sukkah-typed-recall',competency:'translation',feedback:'Typing an answer from memory is a stronger test of durable mastery than recognizing it among choices.'}
]};
