window.SederCourse={stage:'taanit-tractate-arc',completeTitle:'You can now follow a timing dispute through its reason.',completeCopy:'You mapped the question, positions, challenge, distinction, and the Gemara’s placement question. Continue into the visible Taanit source workspace.',nextUrl:'taanit-daf-workbench.html',nextLabel:'Open the Taanit source workspace',steps:[
{short:'Open the question',mode:'TIMING QUESTION',title:'When does the mention begin?',ref:'Taanit 2a',hebrew:'מאימתי מזכירין גבורות גשמים?',translation:'From when do we mention the might of the rains?',prompt:'What kind of problem opens the tractate?',answers:['A question about when a named source practice begins.','A report of current weather.','A final ruling without a question.'],correct:0,skill:'taanit-timing-question',competency:'recognition',feedback:'Right. The source opens with a timing question, so expect positions and reasons.'},
{short:'Map a first voice',mode:'POSITION',title:'Rabbi Eliezer begins earlier',ref:'Taanit 2a',hebrew:'רבי אליעזר אומר מיום טוב הראשון של חג',translation:'Rabbi Eliezer says: From the first festival day.',prompt:'What must a reader preserve?',answers:['This is one position with a specific starting point.','It is automatically the only view in the Mishnah.','The festival date is unrelated to the question.'],correct:0,skill:'taanit-first-position',competency:'sourceReasoning',feedback:'Good. Begin by attaching the speaker to the claim.'},
{short:'Map a second voice',mode:'DISPUTE MAP',title:'Rabbi Yehoshua begins later',ref:'Taanit 2a',hebrew:'רבי יהושע אומר מיום טוב האחרון של חג',translation:'Rabbi Yehoshua says: From the last festival day.',prompt:'What makes this a real disagreement?',answers:['The two voices assign different starting points to the same practice.','They discuss unrelated topics.','The later date erases the first position from the source.'],correct:0,skill:'taanit-second-position',competency:'argument',feedback:'Exactly. Keep the shared question and differing answers in view.'},
{short:'Read the challenge',mode:'STATED REASON',title:'A timing claim has a concern behind it',ref:'Taanit 2a',hebrew:'הואיל ואין הגשמים אלא סימן קללה בחג',translation:'Since rain during the festival is only a sign of a curse.',prompt:'What work does this line do?',answers:['It supplies a reason that challenges beginning the mention at the start of the festival.','It gives personal weather advice.','It removes the need to map the disagreement.'],correct:0,skill:'taanit-timing-reason',competency:'argument',feedback:'Right. The source argues from the relation between the timing and the festival context.'},
{short:'Notice a distinction',mode:'DISTINCTION',title:'Mentioning is not the same as requesting',ref:'Taanit 2a',hebrew:'אף אני לא אמרתי לשאול אלא להזכיר',translation:'I did not say to request, but only to mention.',prompt:'What move does this reply make?',answers:['It distinguishes two related practices rather than denying the concern.','It abandons the timing question.','It gives a modern prayer instruction.'],correct:0,skill:'taanit-mention-request-distinction',competency:'argument',feedback:'Good. A distinction can preserve part of a claim while narrowing what is actually at issue.'},
{short:'Follow the Gemara',mode:'PLACEMENT QUESTION',title:'Why does this tractate begin here?',ref:'Taanit 2a',hebrew:'וליתני התם? מאי שנא דשבקיה עד הכא?',translation:'Let it be taught there; what is different that it was left until here?',prompt:'What is the Gemara asking about?',answers:['Why this topic is placed in Taanit rather than where a related prayer topic appeared earlier.','Which modern community should follow which date.','Whether the Mishnah has any structure.'],correct:0,skill:'taanit-placement-question',competency:'sourceReasoning',feedback:'Exactly. The Gemara treats editorial placement as a question worth explaining.'},
{short:'Transfer the habit',mode:'SOURCE CHECK',title:'Read timing without flattening it',ref:'Taanit source-transfer checkpoint',hebrew:'זמן · קול · טעם · הבחנה',translation:'Time · voice · reason · distinction.',independent:true,prompt:'What is the best first map for a new timing dispute?',answers:['State the shared question, map each voice, locate the reason, and watch for distinctions.','Choose a date before reading the reasons.','Treat the source as direct personal guidance.'],correct:0,skill:'taanit-independent-map',competency:'sourceReasoning',feedback:'You can now read a timing dispute as a structured argument, not a bare list of dates.'}
]};
// Each near-miss preserves a real source-reading confusion while removing answer-length cues.
const taanitSteps=window.SederCourse.steps;
taanitSteps[0].answers=['A question about when a named source practice begins.','A report about whether rain is falling at the present moment.','A final ruling that gives no reason or competing starting point.'];
taanitSteps[1].answers=['This is one position with a specific starting point.','This is the Mishnah’s final ruling, so later voices only repeat it.','The festival date appears, but it has no bearing on the stated practice.'];
taanitSteps[2].answers=['The two voices assign different starting points to the same practice.','The two voices discuss different festival practices and never share a question.','The later date removes the earlier view from the Mishnah rather than answering it.'];
taanitSteps[3].answers=['It supplies a reason that challenges beginning the mention at the start of the festival.','It gives practical weather advice for a traveler who expects rain during the festival.','It shows that timing is irrelevant, so the disagreement no longer needs a reason.'];
taanitSteps[4].answers=['It distinguishes two related practices rather than denying the concern.','It accepts the concern but changes the question into one about a different festival.','It turns an ancient distinction into a direct instruction for a learner’s own prayer.'];
taanitSteps[5].answers=['Why this topic is placed in Taanit rather than where a related prayer topic appeared earlier.','Which current community should select which date, without reference to the source’s placement.','Whether Mishnah arrangement is arbitrary, so no editorial question can be asked.'];
taanitSteps[6].answers=['State the shared question, map each voice, locate the reason, and watch for distinctions.','Choose the date that sounds most familiar before identifying the voices or their reasons.','Treat the source as direct personal guidance rather than a structured dispute to read.'];
