window.SederCourse={stage:'tefillah-siddur-arc',completeTitle:'You can now enter the Siddur with a map.',completeCopy:'You recognized the Shema as Torah language, identified praise, petition, and thanks as different liturgical moves, and saw how prayer is discussed in Gemara and structured in practice. Return to the Siddur with understanding, attention, and curiosity.',nextUrl:'berakhot-arc.html',nextLabel:'Study prayer in Berakhot',steps:[
{short:'Enter the service',mode:'LITURGICAL ORIENTATION',title:'A service has a shape',ref:'Siddur navigation',hebrew:'שֶׁמַע · תְּפִלָּה · הוֹדָיָה',translation:'Shema · prayer · thanksgiving.',prompt:'What is the most useful first way to enter an unfamiliar service?',answers:['Identify the major sections and ask what each is meant to do.','Memorize every word before noticing structure.','Assume all prayer sections have the same purpose.'],correct:0,skill:'tefillah-service-map',competency:'recognition',feedback:'Good. Structure gives a learner orientation before fluency.'},
{short:'Read Torah language',mode:'SOURCE LANGUAGE',title:'The Shema begins in Torah',ref:'Deuteronomy 6:4',hebrew:'שְׁמַע יִשְׂרָאֵל ה׳ אֱלֹהֵינוּ ה׳ אֶחָד',translation:'Hear, O Israel: the Lord is our God, the Lord is one.',prompt:'What does this source contribute to the service?',answers:['A foundational biblical declaration that the liturgy receives and repeats.','A later legal code with no biblical connection.','A private instruction unrelated to communal prayer.'],correct:0,skill:'tefillah-torah-source',competency:'sourceReasoning',feedback:'Exactly. The Siddur often brings biblical language into recurring communal practice.'},
{short:'Name praise',mode:'LITURGICAL MOVE',title:'A blessing can begin with praise',ref:'Opening of Amidah',hebrew:'בָּרוּךְ אַתָּה ה׳',translation:'Blessed are You, Lord.',prompt:'What kind of liturgical move is this formula making?',answers:['Addressing God in a language of blessing and praise.','Asking a Gemara objection.','Giving a legal case.'],correct:0,skill:'tefillah-praise',competency:'translation',feedback:'Good. Naming the move helps the learner hear what a section is doing.'},
{short:'Name petition',mode:'LITURGICAL MOVE',title:'Some prayer asks',ref:'Amidah, understanding blessing',hebrew:'חָנֵּנוּ מֵאִתְּךָ דֵּעָה בִּינָה וְהַשְׂכֵּל',translation:'Grant us knowledge, understanding, and discernment.',prompt:'What makes this a petition?',answers:['It asks for a human need in direct address to God.','It narrates a past event only.','It introduces a source challenge.'],correct:0,skill:'tefillah-petition',competency:'translation',feedback:'Right. Petition is one distinct mode of prayer, not the whole service.'},
{short:'Name thanks',mode:'LITURGICAL MOVE',title:'Some prayer gives thanks',ref:'Amidah, thanksgiving blessing',hebrew:'מוֹדִים אֲנַחְנוּ לָךְ',translation:'We give thanks to You.',prompt:'What is the central action of this phrase?',answers:['Expressing gratitude.','Asking for a ruling.','Comparing two legal categories.'],correct:0,skill:'tefillah-thanksgiving',competency:'recognition',feedback:'Exactly. Learners can begin to navigate prayer by noticing praise, petition, and thanks.'},
{short:'Meet Gemara',mode:'GEMARA CONNECTION',title:'Prayer becomes a question',ref:'Berakhot 26b',hebrew:'תְּפִלּוֹת אָבוֹת תִּקְּנוּם',translation:'The patriarchs instituted the prayers.',prompt:'What kind of question does this Gemara statement invite?',answers:['How prayer’s times and origins are understood and argued in rabbinic tradition.','Which person owns a disputed object.','Whether liturgy has any connection to source tradition.'],correct:0,skill:'tefillah-gemara-connection',competency:'sourceReasoning',feedback:'Good. Gemara turns familiar practice into a source-based discussion.'},
{short:'Practice and intention',mode:'INTENTION',title:'Words and attention both matter',ref:'Mishnah Berakhot 2:3',hebrew:'הַקּוֹרֵא אֶת שְׁמַע וְלֹא הִשְׁמִיעַ לְאָזְנוֹ',translation:'One who recites Shema but does not make it audible to their ear.',prompt:'What kind of study question can this open?',answers:['How words, attention, voice, and practice interact in the experience of prayer.','Whether source structure is unnecessary.','How to avoid asking any questions about liturgy.'],correct:0,skill:'tefillah-intention-question',competency:'sourceReasoning',feedback:'Right. Tefillah joins language, embodied practice, and intention without reducing any one of them to the others.'},
{short:'Keep the boundary',mode:'RESPONSIBLE LEARNING',title:'Understanding prayer is not a ruling',ref:'Seder learning boundary',hebrew:'לִלְמוֹד · לְהָבִין · לִשְׁאוֹל',translation:'To learn · to understand · to ask.',prompt:'You can now name praise, petition, and thanksgiving in the Siddur. What is Seder’s appropriate role here?',answers:['Help learners read and understand the liturgy while directing practical questions about prayer obligations to qualified guidance.','Issue a ruling about when or how a learner must pray.','Treat understanding the words as the same thing as knowing every practical requirement.'],correct:0,skill:'tefillah-non-psak-boundary',competency:'sourceReasoning',feedback:'Moral seriousness includes being clear that understanding what prayer means is not the same as resolving a practical question about performing it.'},
{short:'Independent liturgy map',mode:'INDEPENDENT READ',title:'Read the function before the translation',ref:'Siddur reading checkpoint',hebrew:'בָּרוּךְ · חָנֵּנוּ · מוֹדִים',translation:'Blessed · grant us · we give thanks.',independent:true,prompt:'What map should a learner recognize?',answers:['Praise, petition, and thanksgiving are different forms of address within prayer.','All three phrases are legal rulings.','The service has no discernible structure.'],correct:0,skill:'tefillah-independent-map',competency:'sourceReasoning',feedback:'You can now enter a new prayer section by asking what kind of address its language performs.'}
]};
