const learnerId = Seder.currentLearnerId();
const key = `seder-30-day-${learnerId}`;
const opened = new Set(JSON.parse(localStorage.getItem(key) || '[]'));
const sequence = [
  ['Hear the text','language.html'],['Shema: Torah words','source-reader.html?collection=shema'],['Blessing: source chain','source-reader.html?collection=blessings'],['Gemara: a question opens','tractate-mastery.html?tractate=berakhot'],['Retrieve','canon-vocabulary.html'],['Prayer: name a function','canon-course.html?course=tefillah-six'],['Freedom: define a claim','canon-course.html?course=freedom-six'],['Gemara: map a case','tractate-mastery.html?tractate=shabbat'],['History: context first','canon-course.html?course=history-six'],['Weekly review','weekly-review.html'],
  ['Covenant: memory and command','source-reader.html?collection=covenant'],['Blessings: communal practice','canon-course.html?course=blessings-six'],['Gemara: read a word-question','tractate-mastery.html?tractate=pesachim'],['Vocabulary retrieval','canon-vocabulary.html'],['Responsibility: source and practice','canon-course.html?course=responsibility-six'],['Unseen source check','independent-reading.html'],['Gemara: measure and reason','tractate-mastery.html?tractate=eruvin'],['Repair a weak move','mastery-loop.html'],['Source reflection','sugya-notebook.html'],['Weekly review','weekly-review.html'],
  ['Gemara: validity and purpose','tractate-mastery.html?tractate=sukkah'],['Freedom: revisit the tension','source-reader.html?collection=freedom'],['Unseen source check','independent-reading.html'],['Gemara: claims and evidence','tractate-mastery.html?tractate=bava-metzia'],['Vocabulary retrieval','canon-vocabulary.html'],['History and wider world','canon-course.html?course=history-six'],['Gemara: categories and principle','tractate-mastery.html?tractate=bava-kamma'],['Canon connection','course-dashboard.html'],['Independent synthesis','independent-reading.html'],['Thirty-day review','weekly-review.html']
];
const days = Array.from({length:30}, (_, index) => ({ day: index + 1, label: sequence[index][0], url: sequence[index][1] }));
function render() { document.querySelector('#progress').textContent = `${opened.size} / 30 days opened`; document.querySelector('#days').innerHTML = days.map((day) => `<article class="day ${opened.has(day.day) ? 'done' : ''}"><small>DAY ${day.day}</small><strong>${day.label}</strong><a data-day="${day.day}" href="${day.url}">${opened.has(day.day) ? 'Return to session' : 'Open session'} &rarr;</a></article>`).join(''); document.querySelectorAll('[data-day]').forEach((link) => { link.onclick = () => { opened.add(Number(link.dataset.day)); localStorage.setItem(key, JSON.stringify([...opened])); Seder.api(`/api/learners/${learnerId}/events`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ type: 'daily_program_opened', day: Number(link.dataset.day) }) }).catch(() => {}); }; }); }
render();
