const learnerId = Seder.currentLearnerId();
const id = new URLSearchParams(location.search).get('tractate') || 'shabbat';
const $ = (selector) => document.querySelector(selector);
const arcs = {
  shabbat: { title: 'Shabbat: cases, domains, and distinctions', description: 'Move from a counted Mishnah into a case-based sugya: map people, place, action, category, and the distinction that changes the result.', arc: 'shabbat-arc.html', lab: 'lab.html?tractate=shabbat', daf: 'daf-workbench.html?tractate=shabbat', skills: ['shabbat-counted-mishnah', 'shabbat-case-map', 'shabbat-category', 'shabbat-distinction', 'shabbat-independent-map'] },
  pesachim: { title: 'Pesachim: time, action, and ambiguous words', description: 'Read a time-based legal world by separating action, timing, instrument, and the short words whose meaning Gemara tests.', arc: 'pesachim-arc.html', lab: 'lab.html?tractate=pesachim', daf: 'daf-workbench.html?tractate=pesachim', skills: ['pesachim-action', 'pesachim-case-map', 'pesachim-ambiguous-word', 'pesachim-no-end-principle', 'pesachim-independent-map'] },
  eruvin: { title: 'Eruvin: boundaries, measures, and shared space', description: 'Read a boundary-and-measure sugya by mapping the physical case, the response it triggers, the reason for a threshold, and the distinction between positions.', arc: 'eruvin-arc.html', lab: 'lab.html?tractate=eruvin', daf: 'daf-workbench.html?tractate=eruvin', skills: ['eruvin-case-measure', 'eruvin-case-response', 'eruvin-purpose-of-limit', 'eruvin-shammai-hillel', 'eruvin-independent-map'] },
  sukkah: { title: 'Sukkah: physical validity and symbolic purpose', description: 'Read a validity sugya by joining a concrete structure and measure to the purpose a source gives that structure.', arc: 'sukkah-arc.html', lab: 'lab.html?tractate=sukkah', daf: 'daf-workbench.html?tractate=sukkah', skills: ['sukkah-structure', 'sukkah-measure', 'sukkah-reason', 'sukkah-dispute', 'sukkah-independent-map'] },
  'bava-metzia': { title: 'Bava Metzia: claims, evidence, and dispute', description: 'Enter civil-law reasoning by mapping parties, competing claims, a Mishnah response, the evidence behind it, and an independent dispute map.', arc: 'bava-metzia-arc.html', lab: 'lab.html?tractate=bava-metzia', daf: 'daf-workbench.html?tractate=bava', skills: ['bava-metzia-dispute', 'bava-metzia-two-claimants', 'bava-metzia-mishnah-response', 'bava-metzia-challenge-source', 'bava-metzia-independent-map'] },
  'bava-kamma': { title: 'Bava Kamma: categories, comparison, and responsibility', description: 'Read a damages sugya by distinguishing primary categories, comparing their differences, and locating the principle that makes responsibility intelligible.', arc: 'bava-kamma-arc.html', lab: 'lab.html?tractate=bava-kamma', daf: 'daf-workbench.html?tractate=bava-kamma', skills: ['bava-kamma-categories', 'bava-kamma-difference', 'bava-kamma-shared-principle', 'bava-kamma-responsibility', 'bava-kamma-independent-map'] },
  berakhot: { title: 'Berakhot: question, verse, and sugya flow', description: 'Learn the opening repertoire: a Mishnah question, Gemara pressure, a verse role, and an independent map of the argument.', arc: 'berakhot-mastery.html', lab: 'berakhot-lab.html', daf: 'daf-workbench.html?tractate=berakhot', skills: ['hebrew-question-words', 'gemara-context-question', 'berakhot-sugya-flow', 'proof-role', 'berakhot-independent-source'] },
  ketubot: { title: 'Ketubot: schedule, reason, and a second concern', description: 'Trace a fixed wedding schedule to its institutional reason, then weigh that reason against a second real concern it has to balance.', arc: 'ketubot-arc.html', lab: 'lab.html?tractate=ketubot', daf: 'daf-workbench.html?tractate=ketubot', skills: ['ketubot-schedule', 'ketubot-reason-question', 'ketubot-court-access', 'ketubot-second-concern', 'ketubot-independent-map'] },
  chullin: { title: 'Chullin: a rule read through its exception', description: 'Follow a broad rule, its narrowing exception, the exception’s own stated reason, and the condition that reopens it.', arc: 'chullin-arc.html', lab: 'lab.html?tractate=chullin', daf: 'daf-workbench.html?tractate=chullin', skills: ['chullin-subject', 'chullin-scope', 'chullin-exception', 'chullin-reason', 'chullin-independent-map'] },
  niddah: { title: 'Niddah: a three-way dispute, held carefully', description: 'Track three distinct Tannaitic positions in a live machloket, then connect a separately-sourced presumption without flattening any of them.', arc: 'niddah-arc.html', lab: 'lab.html?tractate=niddah', daf: 'daf-workbench.html?tractate=niddah', skills: ['niddah-opening-position', 'niddah-counter-position', 'niddah-middle-position', 'niddah-hold-three', 'niddah-independent-map'] }
};
const arc = arcs[id] || arcs.shabbat;
const stages = [['Source trail', arc.arc, 'Build the tractate-specific reading repertoire.'], ['Working Daf', arc.daf, 'Name the job each line performs on the visible page.'], ['Sugya notebook', 'sugya-notebook.html', 'Preserve the case, question, evidence, vocabulary, and your own explanation.'], ['Deliberate practice', arc.lab, 'Retrieve and apply the moves in a fresh source layout.'], ['Cumulative vocabulary', 'canon-vocabulary.html', 'Recall source words you saved while reading this and earlier tractates.'], ['Cross-tractate transfer', 'cross-tractate.html', 'Recognize the same move in a different legal world.'], ['Independent capstone', `tractate-capstone.html?tractate=${id}`, 'Explain a case, the reading move, and the evidence that makes the reasoning work.']];
Seder.api(`/api/learners/${learnerId}`).then((response) => response.json()).then((learner) => {
  const mastery = learner.mastery || {};
  const established = arc.skills.filter((skill) => (mastery[skill] || 0) >= .67).length;
  $('#eyebrow').textContent = `${id.toUpperCase()} · FULL MASTERY LOOP`;
  $('#title').textContent = arc.title;
  $('#description').textContent = arc.description;
  $('#summary').innerHTML = `<article><small>TRACTATE SKILLS ESTABLISHED</small><strong>${established} / ${arc.skills.length}</strong></article><article><small>PRIMARY TEXT</small><strong>Visible at every stage</strong></article><article><small>NEXT AIM</small><strong>${established === arc.skills.length ? 'Transfer' : 'Read the next move'}</strong></article>`;
  $('#steps').innerHTML = stages.map(([title, url, copy], index) => `<article class="course-card"><small>STAGE ${index + 1}</small><h2>${title}</h2><p>${copy}</p><a href="${url}">Open stage →</a></article>`).join('');
}).catch(() => { $('#title').textContent = arc.title; $('#description').textContent = arc.description; });
