window.SederCourse={stage:'widerworld-law-reason-arc',completeTitle:'You can now compare traditions without flattening them.',completeCopy:'You started from a Jewish source, named a shared question precisely, traced a linguistic encounter, connected law to public life, and asked how reason and revelation meet a wider canon.',nextUrl:'canon-arc.html?track=widerworld',nextLabel:'Continue the Wider World foundation',steps:[
{short:'Start from a Jewish source',mode:'COMPARATIVE ORIENTATION',title:'A Jewish source frames the question',ref:'Jeremiah 29:7',hebrew:'וּדְרְשׁוּ אֶת־שְׁלוֹם הָעִיר',translation:'Seek the welfare of the city.',prompt:'What comparative question can this open?',answers:['How Jewish communities understand responsibility toward the societies in which they live.','Whether all civilizations think the same way.','Which external canon replaces Jewish sources.'],correct:0,skill:'widerworld-law-start',competency:'sourceReasoning',feedback:'Good. Comparison starts from a real source and a precise question.'},
{short:'Name a shared question',mode:'COMPARISON',title:'Similarity is not identity',ref:'Comparative method',hebrew:'חָכְמָה · תּוֹרָה',translation:'Wisdom · Torah.',prompt:'What is a responsible first comparison?',answers:['Ask how two traditions define a shared word or question before declaring them equivalent.','Assume shared vocabulary proves shared meaning.','Ignore historical context.'],correct:0,skill:'widerworld-law-shared',competency:'argument',feedback:'Exactly. Shared questions can lead to very different conceptual worlds.'},
{short:'Trace an encounter',mode:'HISTORY',title:'Ideas travel through languages',ref:'Medieval Jewish intellectual history',hebrew:'עֲרָבִית · עִבְרִית · לָטִינִית',translation:'Arabic · Hebrew · Latin.',prompt:'What does this linguistic map make possible?',answers:['Study translation, exchange, disagreement, and adaptation across intellectual worlds.','Assume ideas never cross communities.','Reduce history to a list of dates.'],correct:0,skill:'widerworld-law-encounter',competency:'sourceReasoning',feedback:'Jewish thinkers often worked in multilingual intellectual settings.'},
{short:'Law in society',mode:'HALAKHA CONNECTION',title:'Practice meets public life',ref:'Halakhic comparative method',hebrew:'דִּין · קְהִלָּה · מְדִינָה',translation:'Law · community · polity.',prompt:'What kind of question belongs here?',answers:['How covenantal legal reasoning addresses institutions, commerce, medicine, or public responsibility.','Whether law and society are unrelated.','Whether an app can issue personal rulings.'],correct:0,skill:'widerworld-law-society',competency:'sourceReasoning',feedback:'This is a place where Halakha and wider civic worlds meet without becoming identical.'},
{short:'Reason meets revelation',mode:'PHILOSOPHY CONNECTION',title:'A wider canon, a shared vocabulary',ref:'Jewish Philosophy method',hebrew:'שֵׂכֶל · נְבוּאָה',translation:'Reason · prophecy.',prompt:'What is a careful learning question here?',answers:['How Jewish thinkers relate reason and revelation while engaging wider philosophical vocabularies.','Which tradition has no internal differences.','Why texts need no interpretation.'],correct:0,skill:'widerworld-law-reason',competency:'argument',feedback:'Good. Dialogue includes reception, disagreement, and creative reinterpretation.'},
{short:'Return to the source',mode:'COMPARATIVE ORIENTATION',title:'Read it again, with more in view',ref:'Jeremiah 29:7',hebrew:'וּדְרְשׁוּ אֶת־שְׁלוֹם הָעִיר',translation:'Seek the welfare of the city.',prompt:'Reading the verse again with law and reason in view, what comparative question opens?',answers:['How different legal and philosophical traditions each ground civic responsibility, and where they genuinely diverge.','Whether the verse has already been fully explained.','Whether comparison always erases disagreement.'],correct:0,skill:'widerworld-law-return',competency:'argument',feedback:'Right. A source can be reread productively once you have more categories to bring to it.'},
{short:'Transfer a map',mode:'TRANSFER',title:'A History move, a comparative question',ref:'Historical method',hebrew:'מָקוֹר · פֵּרוּשׁ · רְאָיָה',translation:'Source · interpretation · evidence.',prompt:'This map comes from History study. How does it help compare a Jewish and a non-Jewish source?',answers:['By separating what a source says from how it has been interpreted and what evidence supports that interpretation.','By proving one tradition is simply correct and the other is not.','By making close reading unnecessary.'],correct:0,skill:'widerworld-law-transfer',competency:'sourceReasoning',feedback:'A reasoning move built for one subject can sharpen comparative reading in another.'},
{short:'Independent comparison',mode:'INDEPENDENT READ',title:'Compare without flattening',ref:'Comparative reading checkpoint',hebrew:'מָקוֹר · הֶקְשֵׁר · הַשְׁוָאָה',translation:'Source · context · comparison.',independent:true,prompt:'What is the responsible order of comparative learning?',answers:['Read each source in context, name the shared question, then compare similarity and difference.','Start with a broad stereotype and fit the sources to it.','Assume comparison eliminates disagreement.'],correct:0,skill:'widerworld-law-independent',competency:'sourceReasoning',feedback:'You can now compare traditions with curiosity, accuracy, and respect for difference.'}
]};
