window.SederCourse={stage:'yevamot-tractate-arc',completeTitle:'You can now map Yevamot through obligation, exemption, and relationship categories.',completeCopy:'You distinguished the levirate obligation, its exemptions, prohibited relationships, and the boundaries between historical legal study and present-day advice. Continue into the Yevamot source workspace.',nextUrl:'lab.html?tractate=yevamot',nextLabel:'Open the Yevamot source workspace',steps:[
{short:'Count the categories',mode:'CASE ORIENTATION',title:'A list can carry a legal mechanism',ref:'Mishnah Yevamot 1:1',hebrew:'chamesh-esreh nashim potrot tzareihoten',translation:'Fifteen women exempt their co-wives and rival co-wives.',prompt:'What should a reader notice first?',answers:['The counted list is organized around an exemption mechanism, not merely a family tree.','The Mishnah treats every family relationship as identical.','The list is only a narrative opening with no legal work.'],correct:0,skill:'yevamot-category-count',competency:'recognition',feedback:'Right. Yevamot opens with a count whose structure tells you how the exemption operates.'},
{short:'Name the obligation',mode:'OBLIGATION MAP',title:'What does levirate obligation require?',ref:'Deuteronomy 25:5-10',hebrew:'yibbum o chalitzah',translation:'Levirate marriage or the release ceremony.',prompt:'Why identify both possible paths?',answers:['The source presents a defined obligation with two legally recognized ways its relationship can be resolved.','The two terms are interchangeable modern labels with no distinction.','Only marriage matters; the release ceremony is decorative.'],correct:0,skill:'yevamot-levirate-obligation',competency:'sourceReasoning',feedback:'Exactly. Yevamot asks the learner to keep yibbum and chalitzah distinct while seeing how both address the obligation.'},
{short:'Trace the exemption',mode:'EXEMPTION LOGIC',title:'Why can a relationship exempt another?',ref:'Mishnah Yevamot 1:1',hebrew:'potrot tzareihoten',translation:'They exempt their co-wives.',prompt:'What is the legal effect of the counted relationships?',answers:['A prohibited relationship can block the levirate bond and thereby exempt related women from the same obligation.','Any difficult relationship automatically creates a new marriage.','The exemption applies only because the family members disagree.'],correct:0,skill:'yevamot-exemption-mechanism',competency:'argument',feedback:'Good. The Mishnah builds a precise chain from prohibited kinship to exemption.'},
{short:'Separate prohibitions',mode:'RELATIONSHIP BOUNDARIES',title:'Not every prohibited relationship has the same scope',ref:'Mishnah Yevamot 2:1',hebrew:'issurei ervah',translation:'Forbidden kinship relationships.',prompt:'What does careful reading require?',answers:['Track which relationship is prohibited, to whom, and whether the prohibition affects the levirate obligation.','Collapse all prohibitions into one universal rule.','Ignore the relationship category once the word prohibited appears.'],correct:0,skill:'yevamot-prohibited-relationships',competency:'sourceReasoning',feedback:'Yes. Yevamot is a study in how relationship categories carry different legal consequences.'},
{short:'Ask the Gemara',mode:'GEMARA QUESTION',title:'What is the source of the exemption?',ref:'Yevamot 3a',hebrew:'mai taima',translation:'What is the reason?',prompt:'What kind of question is the Gemara asking?',answers:['It asks how the Torah source and the Mishnah mechanism fit together, including the scope of the exemption.','It assumes the Mishnah needs no source or explanation.','It replaces textual reasoning with a judgment about family custom.'],correct:0,skill:'yevamot-source-question',competency:'argument',feedback:'Right. The Gemara turns the list into a source-and-scope problem.'},
{short:'Map the release',mode:'PROCEDURE MAP',title:'Chalitzah is a procedure, not a metaphor',ref:'Deuteronomy 25:9',hebrew:'chaletzah naalo veyarkah befanav',translation:'She removes his shoe before him.',prompt:'Why attend to the procedure?',answers:['Concrete acts, witnesses, and sequence determine whether the release has occurred in the source’s legal frame.','The physical acts are symbols that can be rearranged freely.','Procedure matters only for modern ceremony, not for the text.'],correct:0,skill:'yevamot-chalitzah-procedure',competency:'sourceReasoning',feedback:'Exactly. Yevamot trains the reader to see how a procedure carries legal force.'},
{short:'Set a boundary',mode:'HISTORICAL STUDY',title:'Family law sources need careful boundaries',ref:'Jewish Learning Academy Yevamot boundary',hebrew:'limmud tarihi, lo etzaa mishpatit',translation:'Historical study, not legal advice.',prompt:'What is Jewish Learning Academy’s responsible stance?',answers:['Study the categories historically and distinguish them from present-day legal, pastoral, or personal advice.','Apply an ancient family-law rule automatically to a contemporary person.','Avoid difficult sources because their social setting is unfamiliar.'],correct:0,skill:'yevamot-historical-boundary',competency:'sourceReasoning',feedback:'Serious learning preserves historical precision and protects learners from mistaking study for advice.'},
{short:'Transfer the map',mode:'INDEPENDENT READ',title:'Map an unfamiliar family-law case',ref:'Yevamot transfer checkpoint',hebrew:'kinyan · issur · chovah · patur',translation:'Relationship · prohibition · obligation · exemption.',independent:true,prompt:'What is the best first map for an unfamiliar Yevamot case?',answers:['Identify the relationship category, the obligation, any prohibition, the exemption mechanism, and the procedure that resolves it.','Begin with a verdict based on modern family expectations.','Treat every relationship as either marriage or no relationship.'],correct:0,skill:'yevamot-independent-map',competency:'sourceReasoning',feedback:'You can now read Yevamot through relationship categories, obligation, exemption, and careful boundaries.'}
]};
// Production/source checks: near-misses preserve the real relationship-law distinctions.
const yevamotSteps=window.SederCourse.steps;
yevamotSteps[0].hebrew='חֲמֵשׁ עֶשְׂרֵה נָשִׁים פּוֹטְרוֹת צָרוֹתֵיהֶן';
yevamotSteps[1].hebrew='יִבּוּם אוֹ חֲלִיצָה';
yevamotSteps[2].hebrew='פּוֹטְרוֹת צָרוֹתֵיהֶן';
yevamotSteps[3].hebrew='אִיסּוּרֵי עֲרָיוֹת';
yevamotSteps[4].hebrew='מַאי טַעְמָא';
yevamotSteps[5].hebrew='וְחָלְצָה נַעֲלוֹ מֵעַל רַגְלוֹ';
yevamotSteps[6].hebrew='לִמּוּד הִיסְטוֹרִי, לֹא הוֹרָאָה לְמַעֲשֶׂה';
yevamotSteps[7].hebrew='קִנְיָן · אִיסּוּר · חוֹבָה · פְּטוֹר';
yevamotSteps[0].answers[1]='The Mishnah treats every family relationship as identical, so the counted list does not organize a legal exemption mechanism.';
yevamotSteps[0].answers[2]='The list is only a narrative opening with no legal work, rather than a structured account of which relationships block obligation.';
yevamotSteps[1].answers[1]='The two terms are interchangeable modern labels with no distinction in how the defined obligation is resolved.';
yevamotSteps[1].answers[2]='Only marriage matters; the release ceremony is decorative and does not count as a source-defined resolution of the obligation.';
yevamotSteps[2].answers[1]='Any difficult relationship automatically creates a new marriage, rather than affecting the existing levirate obligation through a defined exemption.';
yevamotSteps[2].answers[2]='The exemption applies only because the family members disagree, not because a prohibited relationship blocks the obligation in the Mishnah.';
yevamotSteps[3].answers[1]='Collapse all prohibitions into one universal rule, without tracking who is related to whom or what consequence follows from that category.';
yevamotSteps[3].answers[2]='Ignore the relationship category once the word prohibited appears, even though Yevamot makes category and scope carry different effects.';
yevamotSteps[4].answers[1]='Assume the Mishnah needs no source or explanation, so the Gemara\'s source-and-scope question adds no interpretive work.';
yevamotSteps[4].answers[2]='Replace textual reasoning with a judgment about family custom, rather than asking how the Torah source supports the exemption mechanism.';
yevamotSteps[5].answers[1]='The physical acts are symbols that can be rearranged freely, even though witnesses and sequence determine whether release occurred in the source\'s frame.';
yevamotSteps[5].answers[2]='Procedure matters only for modern ceremony, not for the text, so the Mishnah\'s concrete acts do not carry legal force.';
yevamotSteps[6].answers[1]='Apply an ancient family-law rule automatically to a contemporary person, treating historical categories as direct personal advice.';
yevamotSteps[6].answers[2]='Avoid difficult sources because their social setting is unfamiliar, rather than studying their categories with clear historical boundaries.';
yevamotSteps[7].answers[1]='Begin with a verdict based on modern family expectations, before identifying the relationship category, obligation, prohibition, and exemption.';
yevamotSteps[7].answers[2]='Treat every relationship as either marriage or no relationship, erasing the source\'s distinctions among obligation, prohibition, exemption, and procedure.';
yevamotSteps.push({short:'Choose the source move',mode:'SOURCE CHECK',title:'Produce the obligation map',ref:'Yevamot 3a',hebrew:'חובה · איסור · פטור',translation:'Obligation · prohibition · exemption.',prompt:'Which account best preserves the source-grounded move in an unfamiliar Yevamot case?',answers:['Classify the relationship first, then test prohibition, obligation, exemption, and the procedure that resolves the remaining duty.','Begin with a modern verdict and fit the relationship into it, without checking which source category creates or removes the obligation.','Treat yibbum and chalitzah as interchangeable labels, since the procedure cannot change the legal status of the relationship.'],correct:0,skill:'yevamot-source-check',competency:'sourceReasoning',feedback:'You produced the transferable move: classify the relationship, trace its legal effect, and only then map the resolving procedure.'});
